### ISSUE TITLE
More EuropePMC errors

### ISSUE THREAD

**Issue by kevinrutherford** [sciety/sciety#1041]
https://elifesciences.slack.com/archives/C01GMPQC8NS/p1629669534015300

TImebox investigation to 1 hour.

**Comment by erkannt** [comment]
There seem to have been 13 instances of us not being able to parse responses from EPMC over last 30 days: https://sciety.grafana.net/explore?orgId=1&left=%5B%22now-30d%22,%22now%22,%22grafanacloud-sciety-logs%22,%7B%22expr%22:%22%7Bapp_kubernetes_io_name%3D%5C%22sciety%5C%22,app_kubernetes_io_instance%3D%5C%22sciety--prod%5C%22%7D%5Cn%7C%20json%20%7C%20__error__%3D%5C%22%5C%22%5Cn%7C%20level%20%3D%20%5C%22error%5C%22%20%7C%20message%3D%5C%22Could%20not%20parse%20response%5C%22%22%7D%5D

**Comment by giorgiosironi** [comment]
Reproducible at first on:
http://localhost:8080/search?query=COVID-19&category=articles&cursor=AoJwgNTA/oCKDQ0MjUxOTgw&page=11
but not when getting at page 11 through the link on page 10:
http://localhost:8080/search?query=COVID-19&category=articles&cursor=AoJwgJn6jvsCKDQ0MjkwNzQ4&page=11

**Comment by giorgiosironi** [comment]
https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=(%222019-nCoV%22+OR+%222019nCoV%22+OR+%22COVID-19%22+OR+%22SARS-CoV-2%22+OR+%22COVID19%22+OR+%22COVID%22+OR+%22SARS-nCoV%22+OR+(%22wuhan%22+AND+%22coronavirus%22)+OR+%22Coronavirus%22+OR+%22Corona+virus%22+OR+%22corona-virus%22+OR+%22corona+viruses%22+OR+%22coronaviruses%22+OR+%22SARS-CoV%22+OR+%22Orthocoronavirinae%22+OR+%22MERS-CoV%22+OR+%22Severe+Acute+Respiratory+Syndrome%22+OR+%22Middle+East+Respiratory+Syndrome%22+OR+(%22SARS%22+AND+%22virus%22)+OR+%22soluble+ACE2%22+OR+(%22ACE2%22+AND+%22virus%22)+OR+(%22ARDS%22+AND+%22virus%22)+or+(%22angiotensin-converting+enzyme+2%22+AND+%22virus%22))+(PUBLISHER%3A%22bioRxiv%22+OR+PUBLISHER%3A%22medRxiv%22)+sort_date%3Ay&format=json&pageSize=20&resultType=core&cursorMark=AoJwwLadh%2FsCKDQ0MjcwMzkw
has a `%2F` in the cursor, but it works.

**Comment by kevinrutherford** [comment]
Most recent example: https://sciety.grafana.net/explore?orgId=1&left=%5B%22now-2d%22,%22now%22,%22grafanacloud-sciety-logs%22,%7B%22expr%22:%22%7Bapp_kubernetes_io_name%3D%5C%22sciety%5C%22,app_kubernetes_io_instance%3D%5C%22sciety--prod%5C%22%7D%5Cn%7C%20json%20%7C%20__error__%3D%5C%22%5C%22%5Cn%7C%20payload_requestId%20%3D%20%5C%220ac67810-0f1d-11ec-90cf-1353783449b7%5C%22%22%7D%5D

**Comment by giorgiosironi** [comment]
`2021-09-06T14:16:35.089Z` is the timestamp of page 16, the failing one. We can reproduce this locally, as expected.

**Comment by giorgiosironi** [comment]
By running:
https://sciety.grafana.net/explore?orgId=1&left=%5B%22now-2d%22,%22now%22,%22grafanacloud-sciety-logs%22,%7B%22expr%22:%22%7Bapp_kubernetes_io_name%3D%5C%22sciety%5C%22,app_kubernetes_io_instance%3D%5C%22sciety--prod%5C%22%7D%5Cn%7C%20json%20%7C%20__error__%3D%5C%22%5C%22%5Cn%7C%20payload_url%20%3D~%20%5C%22%2Fsearch%3Fquery%3DC.%2520elegans%26category%3Darticles%26cursor%3D%5B%5E%26%5D%2B%26page%3D16%5C%22%22%7D%5D
we found page 16 was loaded successfully a couple of hours later:
`2021-09-06T17:59:38.031Z`
and the cursor, 2 days later, still works:
http://localhost:8080/search?query=C.%20elegans&category=articles&cursor=AoJwgL2W5/UCKDQyNjM5MjUx&page=16

**Comment by giorgiosironi** [comment]
We think page 15 was loaded 30 seconds before the failing page 16:
https://sciety.grafana.net/explore?orgId=1&left=%5B%22now-2d%22,%22now%22,%22grafanacloud-sciety-logs%22,%7B%22expr%22:%22%7Bapp_kubernetes_io_name%3D%5C%22sciety%5C%22,app_kubernetes_io_instance%3D%5C%22sciety--prod%5C%22%7D%5Cn%7C%20json%20%7C%20__error__%3D%5C%22%5C%22%5Cn%7C%20payload_url%20%3D~%20%5C%22%2Fsearch%5C%5C%5C%5C%3Fquery%3DC.%2520elegans%26category%3Darticles%26cursor%3D%5B%5E%26%5D%2B%26page%3D15%5C%22%22%7D%5D
`2021-09-06T14:16:05.520Z`

**Comment by davidcmoulton** [comment]
Confirming pages 15 and 16 were requested by the same client https://sciety.grafana.net/explore?orgId=1&left=%5B%22now-2d%22,%22now%22,%22grafanacloud-sciety-logs%22,%7B%22expr%22:%22%7Bapp_kubernetes_io_name%3D%5C%22ingress-nginx%5C%22%7D%5Cn%7Cjson%5Cn%7C%20request%20%3D~%20%5C%22GET%20%2Fsearch%5C%5C%5C%5C%3Fquery%3DC.%2520elegans%26category%3Darticles%26cursor%3D%5B%5E%26%5D%2B%26page%3D1(5%7C6)%20.*%5C%22%22%7D%5D

**Comment by davidcmoulton** [comment]
When we now load page 15 with the original url `/search?query=C.%20elegans&category=articles&cursor=AoJwgM7P3fYCKDQyODkxNDY3&page=15`:
- it still works
- the cursor it returns for page 16 within `/search?query=C.%20elegans&category=articles&cursor=AoJwgP+ir/YCKDQyNzg1Mjky&page=16` is the same as the broken one that started this investigation, and it's still broken.

**Comment by giorgiosironi** [comment]
Page 15: https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=C.+elegans+%28PUBLISHER%3A%22bioRxiv%22+OR+PUBLISHER%3A%22medRxiv%22%29+sort_date%3Ay&format=json&pageSize=20&resultType=core&cursorMark=AoJwgM7P3fYCKDQyODkxNDY3
Page 16: https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=C.+elegans+%28PUBLISHER%3A%22bioRxiv%22+OR+PUBLISHER%3A%22medRxiv%22%29+sort_date%3Ay&format=json&pageSize=20&resultType=core&cursorMark=AoJwgP+ir%2FYCKDQyNzg1Mjky

**Comment by giorgiosironi** [comment]
Followed up on https://groups.google.com/a/ebi.ac.uk/g/epmc-webservices/c/7B-gzP5xcPE giving this to Europe PMC as a reproducible bug.

**Comment by giorgiosironi** [comment]
Still an error to be investigated after our fix was already deployed:
```
Today at 1:21 AM
{
    "errors": [
        "Invalid value undefined supplied to : { hitCount: number, nextCursorMark: Option<string>, resultList: { result: Array<{ doi: DoiFromString, title: string, authorList: { author: ReadonlyArray<({ fullName: string } | { collectiveName: string })> }, bookOrReportDetails: { publisher: (\"bioRxiv\" | \"medRxiv\") } }> } }/hitCount: number",
        "Invalid value undefined supplied to : { hitCount: number, nextCursorMark: Option<string>, resultList: { result: Array<{ doi: DoiFromString, title: string, authorList: { author: ReadonlyArray<({ fullName: string } | { collectiveName: string })> }, bookOrReportDetails: { publisher: (\"bioRxiv\" | \"medRxiv\") } }> } }/resultList: { result: Array<{ doi: DoiFromString, title: string, authorList: { author: ReadonlyArray<({ fullName: string } | { collectiveName: string })> }, bookOrReportDetails: { publisher: (\"bioRxiv\" | \"medRxiv\") } }> }"
    ],
    "url": "https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=C.+elegans+%28PUBLISHER%3A%22bioRxiv%22+OR+PUBLISHER%3A%22medRxiv%22%29+sort_date%3Ay&format=json&pageSize=20&resultType=core&cursorMark=AoJwgNqD+%2FQCKDQyMzYwMDg4",
    "requestId": "fc6c7690-11cc-11ec-8346-fbf8e30d3db3"
}
```

**Comment by giorgiosironi** [comment]
Also failing:
```
https://www.ebi.ac.uk/europepmc/webservices/rest/search?query=%28%222019-nCoV%22+OR+%222019nCoV%22+OR+%22COVID-19%22+OR+%22SARS-CoV-2%22+OR+%22COVID19%22+OR+%22COVID%22+OR+%22SARS-nCoV%22+OR+%28%22wuhan%22+AND+%22coronavirus%22%29+OR+%22Coronavirus%22+OR+%22Corona+virus%22+OR+%22corona-virus%22+OR+%22corona+viruses%22+OR+%22coronaviruses%22+OR+%22SARS-CoV%22+OR+%22Orthocoronavirinae%22+OR+%22MERS-CoV%22+OR+%22Severe+Acute+Respiratory+Syndrome%22+OR+%22Middle+East+Respiratory+Syndrome%22+OR+%28%22SARS%22+AND+%22virus%22%29+OR+%22soluble+ACE2%22+OR+%28%22ACE2%22+AND+%22virus%22%29+OR+%28%22ARDS%22+AND+%22virus%22%29+or+%28%22angiotensin-converting+enzyme+2%22+AND+%22virus%22%29%29+%28PUBLISHER%3A%22bioRxiv%22+OR+PUBLISHER%3A%22medRxiv%22%29+sort_date%3Ay&format=json&pageSize=20&resultType=core&cursorMark=AoJwgNTA%2FoCKDQ0MjUyMDA3
```
which is a very elaborate query.

**Comment by giorgiosironi** [comment]
Reproducing locally on:
```
/search?query=%20%28%22membrane*%22%20OR%20%22protein*%22%29%20AND%20%28%22membrane%20protein*%22%20OR%20%22ion%20channel*%22%20OR%20%22transporter*%22%20OR%20%22pump*%22%20OR%20%22gpcr*%22%20OR%20%22ligand*%22%20OR%20%22exchange*%22%20OR%20%22uniport*%22%20OR%20%22symport*%22%20OR%20%22antiport*%22%20OR%20%22solute%20carrier*%22%20OR%20%22atpase*%22%20OR%20%22atp%20synthase*%22%20OR%20%22rhodopsin%22%20OR%20%22patch*%22%20OR%20%22voltage*%22%20OR%20%22single-channel*%22%20OR%20%22anion*%22%20OR%20%22cation*%22%20OR%20%22gating%22%20OR%20%22activat*%22%20OR%20%22inactivat*%22%20OR%20%22selectiv*%22%29&category=articles&cursor=AoJwwKu+n/kCKDQzNzA0Mzkw&page=31
```
which happened this morning.

**Comment by giorgiosironi** [comment]
This looks like a bot refreshing its cached pages rather than something legitimately scrolling through search. Can only find two request logs for this query rather than 31 pages:
```
{
  "time_local": "21/Sep/2021:05:42:14 +0000",
  "remote_addr": "157.90.181.150",
  "request": "GET /search?query=%20%28%22membrane*%22%20OR%20%22protein*%22%29%20AND%20%28%22membrane%20protein*%22%20OR%20%22ion%20channel*%22%20OR%20%22transporter*%22%20OR%20%22pump*%22%20OR%20%22gpcr*%22%20OR%20%22ligand*%22%20OR%20%22exchange*%22%20OR%20%22uniport*%22%20OR%20%22symport*%22%20OR%20%22antiport*%22%20OR%20%22solute%20carrier*%22%20OR%20%22atpase*%22%20OR%20%22atp%20synthase*%22%20OR%20%22rhodopsin%22%20OR%20%22patch*%22%20OR%20%22voltage*%22%20OR%20%22single-channel*%22%20OR%20%22anion*%22%20OR%20%22cation*%22%20OR%20%22gating%22%20OR%20%22activat*%22%20OR%20%22inactivat*%22%20OR%20%22selectiv*%22%29&category=articles&cursor=AoJwwKu+n/kCKDQzNzA0Mzkw&page=31 HTTP/1.1",
  "http_referrer": "",
  "http_user_agent": "Mozilla/5.0 (compatible; BLEXBot/1.0; +http://webmeup-crawler.com/)",
  "status": "503",
  "proxy_upstream_name": "default-sciety--prod--frontend-http",
  "upstream_status": "503",
  "upstream_response_time": "0.420",
  "ingress_name": "sciety--prod--frontend",
  "namespace": "default"
}
{
  "time_local": "21/Sep/2021:05:42:11 +0000",
  "remote_addr": "157.90.181.150",
  "request": "GET /search?query=%20%28%22membrane*%22%20OR%20%22protein*%22%29%20AND%20%28%22membrane%20protein*%22%20OR%20%22ion%20channel*%22%20OR%20%22transporter*%22%20OR%20%22pump*%22%20OR%20%22gpcr*%22%20OR%20%22ligand*%22%20OR%20%22exchange*%22%20OR%20%22uniport*%22%20OR%20%22symport*%22%20OR%20%22antiport*%22%20OR%20%22solute%20carrier*%22%20OR%20%22atpase*%22%20OR%20%22atp%20synthase*%22%20OR%20%22rhodopsin%22%20OR%20%22patch*%22%20OR%20%22voltage*%22%20OR%20%22single-channel*%22%20OR%20%22anion*%22%20OR%20%22cation*%22%20OR%20%22gating%22%20OR%20%22activat*%22%20OR%20%22inactivat*%22%20OR%20%22selectiv*%22%29&category=articles&cursor=AoJwgOrnu/kCKDQzNzU1NjU3&page=29 HTTP/1.1",
  "http_referrer": "",
  "http_user_agent": "Mozilla/5.0 (compatible; BLEXBot/1.0; +http://webmeup-crawler.com/)",
  "status": "200",
  "proxy_upstream_name": "default-sciety--prod--frontend-http",
  "upstream_status": "200",
  "upstream_response_time": "3.032",
  "ingress_name": "sciety--prod--frontend",
  "namespace": "default"
}
```
