### ISSUE TITLE
Determine % visits resulting in breadcrumbs over time

### ISSUE THREAD

**Issue by erkannt** [sciety/sciety#1044]
- timeframe of interest: last six complete weeks
- week starts on monday

- [ ] elide redirects
- [ ] cope with raw log data files
- [ ] report the KPI: % of visits per week in which at least one breadcrumb was successfully left
- [ ] test with larger data sets

**Comment by giorgiosironi** [comment]
How to find users leaving at least a breadcrumb, per day:
```
cat events.json | jq -c '.[] | {date, user: .payload.userId}' | sed -e 's/T.*",/",/' | sort | uniq | sed -e 's/{"date":"//' | sed -e 's/","user":"/,/' | sed -e 's/"}//' > date-and-user-id.csv
```

**Comment by kevinrutherford** [comment]
To prepare nginx logs for parsing into visits:

- add a `,` at the end of each record
- wrap the whole set of records in `[` and `]`
- replace the first `;` in each `time_local` field by ` `

**Comment by giorgiosironi** [comment]
Spiking the processing of a raw file, cleaning up in TypeScript:
```
  TE.map((wholeFile) => wholeFile.split('\n')),
  TE.map(RA.filter((line) => line.startsWith('{'))),
  TE.map((lines) => lines.join(',')),
  TE.map((file) => `[${file}]`),
```
