### ISSUE TITLE
Promote Colab more on the landing page and groups page

### ISSUE THREAD

**Issue by BlueReZZ** [sciety/sciety#1059]
- [x] move colab up to the top of the groups directory page
- [x] add the evaluation from Colab to the landing page: https://sciety.org/articles/activity/10.1101/2021.07.05.451181

**Comment by giorgiosironi** [comment]
Taking out https://sciety.org/articles/activity/10.1101/2021.05.25.445589 to make space for one new card, as it has the oldest evaluation.
