### ISSUE TITLE
Filter the DocMaps index by updated date

### ISSUE THREAD

**Issue by hdrury1** [sciety/sciety#1099]
For new groups, communicate with bioRxiv when they get added.

Tell bioRxiv to use padding on the updated date, always request > updated date a few days in the past, to cover for us not running update scripts in time. They should then de-duplicate.

Unclear whether we can still remove reviews. At the moment bioRxiv doesn't remove them if they get removed from Hypothesis.

## Scenario that might break with too new updated dates

8am: review gets published by a group
10am: bioRxiv calls us (we don't have it)
12pm: we update the scripts
2pm: bioRxiv calls us again, saying updated > 10am

## Sample routes from Thomas at Review Commons

A `reviewing_service` is a group for us. Not meant to replicate this wholesale, just for comparison.

```
 @app.route('/api/v2/<reviewing_service>/docmap/<start_date>/<end_date>/<int:pagination>', methods=['GET', 'POST'])
# @app.route('/api/v2/docmap/<start_date>/<end_date>/<int:pagination>', methods=['GET', 'POST'])
# @app.route('/api/v2/<reviewing_service>/docmap/<int:N_most_recent>/<int:pagination>', methods=['GET', 'POST'])
# @app.route('/api/v2/<reviewing_service>/docmap/<int:days>d/<int:pagination>', methods=['GET', 'POST']) 
```

**Comment by BlueReZZ** [comment]
URL example that wasn't working: `https://sciety.org/docmaps/v1/index?updatedAfter=2021-09-01`
