### ISSUE TITLE
Set the correct occurredAt date for file-based events

### ISSUE THREAD

**Issue by kevinrutherford** [sciety/sciety#1326]

**Comment by giorgiosironi** [comment]
Me and David are running the script for the last 3 groups (Review Commons, eLife, and ScreenIT) and haven't had `null` date problems so far. If everything goes well we can commit these files tomorrow morning and close the ticket.

**Comment by giorgiosironi** [comment]
David will commit 2 of the remaining 3 groups. eLife is the last one, but the script failed:
```
...
Processed evaluation 5035 (hypothesis:nt6dQlhDEeyj83fDKkjZXQ)
Processed evaluation 5036 (hypothesis:IKYc7FhEEeyTwNPYVIqTzQ)
Processed evaluation 5037 (hypothesis:ISnFYFhEEeyML-do2ozcKA)
Processed evaluation 5038 (hypothesis:IZ7volhEEeysjZP9CIM41g)
Tried to build a Date from an invalid string: "T"
```
