### ISSUE TITLE
NCRC More information link returns 404

### ISSUE THREAD

**Issue by davidcmoulton** [sciety/sciety#1350]
To reproduce:
1. Go to https://sciety.org/articles/activity/10.1101/2021.11.17.21263608
2. Click on "More"
3. Click on "Read original source"
4. Note the resulting destination https://ncrc.jhsph.edu/research/reduced-incidence-of-long-covid-symptoms-related-to-administration-of-covid-19-vaccines-both-before-covid-19-diagnosis-and-up-to-12-weeks-after/ returns a 404.

To help diagnose, a snap shot of the NCRC Google sheet as at 5 Jan 2022 is available at https://docs.google.com/spreadsheets/d/1KyKFYMKiajjeHaPb86RK3-jE1Hdil2j_T-48Sfmuy_4/edit#gid=0

## Summary
Per comments below, the article that is returning 404 on https://ncrc.jhsph.edu does not appear when searched for by title on that site, nor does an author search on that site return an article with a similar but different title.

## Question
What should this evaluation link to in light of this?

**Comment by de-code** [comment]
As a reference something that is working:

https://sciety.org/articles/activity/10.1101/2021.11.04.467308#ncrc:31f1797b-2835-4e00-81cd-3978ae770359
https://ncrc.jhsph.edu/research/sars-cov-2-infection-in-free-ranging-white-tailed-deer-(odocoileus-virginianus)/

**Comment by de-code** [comment]
Searching by the author doesn't seem to show a matching paper: https://ncrc.jhsph.edu/?s=Simon

![image](https://user-images.githubusercontent.com/1016473/148199844-8a5ffb66-076b-41a1-aa49-e2fbbcef0397.png)

**Comment by hdrury1** [comment]
I've emailed Brooke so awaiting response. Suggest we can close this ticket now.
