### ISSUE TITLE
Add author response to Biophysics Colab's evaluation of a Research Square paper

### ISSUE THREAD

**Issue by BlueReZZ** [sciety/sciety#1370]
This article: https://www.researchsquare.com/article/rs-955726/v1

The annotation is here: https://hypothes.is/a/8h6HBnJMEeyIDzNrTJzkOA

The Sciety page is:
https://sciety.org/articles/activity/10.21203/rs.3.rs-955726/v1

Annotation ID `8h6HBnJMEeyIDzNrTJzkOA`

This link may open it in context on Research Square if you have the hypothesis plugin: https://www.researchsquare.com/article/rs-955726/v1#annotations:8h6HBnJMEeyIDzNrTJzkOA

**Comment by erkannt** [comment]
The Research Square evaluations appear to not have been publish via the hypothesis group instead of the user.

https://hypothes.is/groups/e277wiod/biophysics-colab
https://hypothes.is/users/biophysics_sciencecolab?q=
