### ISSUE TITLE
Spike: Lazy out of process lists read model

### ISSUE THREAD

**Issue by erkannt** [sciety/sciety#1450]

**Comment by giorgiosironi** [comment]
Running:
```
while curl -m 1 localhost:8080/ping; do date; done
```
breaks with the 1 second timeout when loading http://localhost:8080/groups/elife/lists once.

**Comment by davidcmoulton** [comment]
Link to Grafana query with lists service read model logs: https://sciety.grafana.net/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22grafanacloud-sciety-logs%22,%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp_kubernetes_io_instance%3D%5C%22sciety--prod%5C%22%7D%5Cn%7C%20json%5Cn%7C%20message%3D%5C%22Response%20time%5C%22%22,%22hide%22:true%7D,%7B%22refId%22:%22B%22,%22expr%22:%22%7Bapp_kubernetes_io_instance%3D%5C%22sciety--prod%5C%22,%20app_kubernetes_io_component%3D%5C%22lists-read-model%5C%22%7D%5Cn%7C%20json%22%7D%5D

**Comment by erkannt** [comment]
page load min and max on localhost

Using in-app readmodel
```
ab -c 10 -n 10 http://localhost:8080/groups/elife/lists | grep Waiting | tr -s ' ' | cut -f 2,6 -d ' '
976 7740
ab -c 10 -n 10 http://localhost:8080/groups/elife/lists | grep Waiting | tr -s ' ' | cut -f 2,6 -d ' '
968 7637
ab -c 10 -n 10 http://localhost:8080/groups/elife/lists | grep Waiting | tr -s ' ' | cut -f 2,6 -d ' '
1192 8413

```

Using lists-readmodel-service

```
ab -c 10 -n 10 http://localhost:8080/groups/elife/lists | grep Waiting | tr -s ' ' | cut -f 2,6 -d ' '
1948 12507
ab -c 10 -n 10 http://localhost:8080/groups/elife/lists | grep Waiting | tr -s ' ' | cut -f 2,6 -d ' '
1458 11421
ab -c 10 -n 10 http://localhost:8080/groups/elife/lists | grep Waiting | tr -s ' ' | cut -f 2,6 -d ' '
1475 11740
```

Both min and max times increase.

**Comment by erkannt** [comment]
Max concurrency on Daniel's machine monitored using ping while loop

`while curl -m 1 localhost:8080/ping; do date; sleep 0.5;done`

in-app readmodel: 2
external readmodel: 3

**Comment by erkannt** [comment]
After using external lists readmodel in two places on `/groups/elife/lists`

ab -c 10 -n 10 http://localhost:8080/groups/elife/lists

```
min   max
2518 21331
2466 20849
2424 20747

```
