### ISSUE TITLE
Add articles to Neuroscience list until we run out of time today

### ISSUE THREAD

**Issue by davidcmoulton** [sciety/sciety#1479]
We ran background policy over all events (52638), and noted it completed in 514 seconds (under 10 minutes).

**Comment by davidcmoulton** [comment]
We couldn't resolve whether or not the article with the DOI `10.1101/2021.05.04.442589` belongs in the eLife Neuroscience list as biorxiv.org was down (502) when we checked it in the browser at `https://www.biorxiv.org/lookup/doi/10.1101/2021.05.04.442589`.

`curl https://api.biorxiv.org/details/biorxiv/10.1101/2021.05.04.442589 | jq .` returned an empty collection.

**Comment by giorgiosironi** [comment]
The only problematic article was sorted by bioRxiv after we raised it, and it didn't affect this list (https://api.biorxiv.org/details/biorxiv/10.1101/2021.05.04.442589).
