### ISSUE TITLE
Create and populate the eLife `Biochemistry and Chemical Biology` list

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#1481]

**Comment by davidcmoulton** [comment]
Ran over all events. Failed to get subject area for three DOIs:

- 10.1101/2020.09.03.20184051
- 10.1101/2020.04.15.20065656
- 10.1101/2020.08.25.20181628

**Comment by davidcmoulton** [comment]
Tried adding this event into the backstop data, but atm the list count on the group card is incorrect with this data, so not changing that backstop test to use this event until the list count is also correct. The event code below is for reference so we don't have to invent it all over again!

```
0a485144-5015-402a-b41e-4cf4d82b1eee,ListCreated,2022-03-10 11:40:00,"{""listId"": ""2c369dbd-0174-45c2-aa88-b94184f7305a"", ""name"": ""Bogus list"", ""description"": ""Bogus description"", ""ownerId"": ""74fd66e9-3b90-4b5a-a4ab-5be83db4c5de""}"```
