### ISSUE TITLE
Tech spike for Prereview

### ISSUE THREAD

**Issue by davidcmoulton** [sciety/sciety#1502]
Context in https://miro.com/app/board/uXjVOKAkDZc=/

## Ingestion:
- [x] query Zenodo API sandbox for details and get back DOI (similar to https://github.com/PREreview/prereview-display-prototype)? YES: `doi`
- [x] query Zenodo API sandbox for details and get back Zenodo ID (similar to https://github.com/PREreview/prereview-display-prototype) YES: `id`
- [x] Do we need to paginate? YES
- [x] Can we restrict to only recently updated records? YES
- [x] Can we get an article DOI? YES
- [x] Can we get the evaluation's authors (optional but useful)? YES, at least from the Zenodo API

## Datacite:
- [ ] Can we get everything we need from the querying DataCite with the DOI, or do we need to fallback to Zenodo API (sandbox) to fill in any gaps?
  - [x] full text YES
  - [x] URL YES
  - [ ] alternative Zenodo identifier; unclear, but can wait as Prereview is not ready to assign a value here
  - [x] communities field **NO**
  - [x] rapid reviews (determined by keyword 'rapid-review' (check exact value)

## Zenodo API:
- [x] If starting with a Zenodo ID rather than a DOI, can we get everything we need from Zenodo (sandbox)? YES
  - [x] full text YES
  - [x] URL YES
  - [x] alternative Zenodo identifier YES
  - [x] communities field YES
  - [x] rapid reviews (determined by keyword 'rapid-review' (check exact value) YES

`fulltext`:
- DataCite returns text, Zenodo id query returns HTML

`URL`:
- can be built with `doi.org` or `zenodo.org/records`, depending on the identifier; also appears in various forms in API responses

## Versioning (if present)
- [x] are we using Version DOIs on Sciety for Prereview? Yes, we are not using Concept DOIs.
- [x] Does Prereview allow updating evaluations? This could be done for cleaning up HTML.
- [x] If so, is the updated evaluation posted as a new Version DOI? Would result in Sciety listing two evaluations until we retire both old and new version, and record again Concept DOIs as new EvaluationLocators.
- [x] If the metadata is changed to include community/keyword/... does that generate a new Version DOI? According to [Zenodo](https://help.zenodo.org/#versioning), no new version

Zenodo API docs:
- https://developers.zenodo.org/

**Comment by davidcmoulton** [comment]
To get a list of articles in the Zenodo sandbox:
```curl -v https://sandbox.zenodo.org/api/records/?communities=prereview-test-community```

**Comment by davidcmoulton** [comment]
Paginate is handled like this:
```
"links": {
    "next": "https://sandbox.zenodo.org/api/records/?sort=mostrecent&communities=prereview-test-community&page=2&size=10",
    "self": "https://sandbox.zenodo.org/api/records/?sort=mostrecent&communities=prereview-test-community&page=1&size=10"
  }
```

**Comment by davidcmoulton** [comment]
The default sort order is descending by date, obtainable from:
```
curl -v https://sandbox.zenodo.org/api/records/?communities=prereview-test-community | jq .hits.hits[].updated

"2022-03-22T10:00:54.663765+00:00"
"2022-03-22T09:59:25.992878+00:00"
"2022-03-10T11:10:11.857586+00:00"
"2022-03-10T10:19:15.050330+00:00"
"2022-03-10T10:19:13.047520+00:00"
"2022-03-10T10:14:26.278691+00:00"
"2022-03-09T16:38:55.725098+00:00"
"2022-03-09T16:13:27.224159+00:00"
"2022-03-09T15:50:10.474410+00:00"
"2022-03-09T14:07:37.571713+00:00"
```
This appears to be sorting well, but it's not clear whether it's sorting by `created`, `metadata.publication_date` or `updated`.

**Comment by giorgiosironi** [comment]
`metadata` contains a possible way to link the evaluation to the article it `reviews`:
```
          "related_identifiers": [
            {
              "identifier": "10.1101/2021.01.20.427507",
              "relation": "reviews",
              "scheme": "doi"
            },
```

**Comment by giorgiosironi** [comment]
`metadata` also contains:
```
          "related_identifiers": [
            // ...
            {
              "identifier": "10.5072/zenodo.1039218",
              "relation": "isVersionOf",
              "scheme": "doi"
            }
          ],
```
This provides a possible evaluation DOI, rather than an evaluation version DOI. We don't really support versioning on evaluation, so it might be desirable to use this DOI as the identifier rather than the one of the record. Triggers questions about what can we fetch from the version-less identifier.

**Comment by giorgiosironi** [comment]
`metadata` also might contain a reference to authors, but we'll have to verify outside of the sandbox with production data:
```
         "creators": [
            {
              "name": "Lightpink Hamster"
            }
          ],
```

**Comment by giorgiosironi** [comment]
To get an individual record from the Zenodo API using the Zenodo id:
```
curl -v https://zenodo.org/api/records/6342480
```

**Comment by davidcmoulton** [comment]
Example of alternative Zenodo identifier from the Zenodo API

```
       "alternate_identifiers": [
            {
              "identifier": "https://prereview.org/reviews/9bad8e71-c575-4ce6-be6a-a0cd9f0143e6",
              "scheme": "url"
            }
          ],
 ```

**Comment by davidcmoulton** [comment]
`metadata` contains the `communities` field (from the Zenodo API): 
```
         "communities": [
            {
              "id": "prereview-test-community"
            }
          ],
 ```

**Comment by davidcmoulton** [comment]
`metadata` contains the `keywords` array, which enables identification of a rapid review:

```
          "keywords": [
            "rapid-review"
          ],
```

**Comment by davidcmoulton** [comment]
`keywords` in Zenodo's API map to `tags` in a Datacite response.

```
  "tags": [
    "climate",
    "EUCP"
  ],
```

**Comment by davidcmoulton** [comment]
To query Datacite:

```
curl -v https://data.crosscite.org/10.5281%2Fzenodo.6354460 -H "Accept: application/vnd.codemeta.ld+json"
```

We obtained this by following redirects from doi.org with the accept header.
