### ISSUE TITLE
Add Biophysics Colab to docmaps

### ISSUE THREAD

**Issue by erkannt** [sciety/sciety#1521]

**Comment by giorgiosironi** [comment]
How to see bioRxiv calls to the docmaps API:
https://sciety.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-sciety-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp_kubernetes_io_instance%3D%5C%22ingress-nginx%5C%22%7D%5Cn%7C%20json%5Cn%7C%20__error__%20%3D%20%5C%22%5C%22%5Cn%7C%20ingress_name%3D%5C%22sciety--prod--frontend%5C%22%5Cn%7C%20request%20%3D~%20%5C%22GET%20%2Fdocmaps%2F.*%5C%22%5Cn%7C%20http_user_agent%3D%5C%22browser%5C%22%22%7D%5D,%22range%22:%7B%22from%22:%22now-30d%22,%22to%22:%22now%22%7D%7D
