### ISSUE TITLE
Investigate and mitigate Crossref 404 errors

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#1591]

**Comment by LinaKind** [comment]
[Explore-data-2022-05-20 10 40 28.csv](https://github.com/sciety/sciety/files/8738311/Explore-data-2022-05-20.10.40.28.csv)

**Comment by LinaKind** [comment]
[Explore-logs-2022-05-20 10 48 46.txt](https://github.com/sciety/sciety/files/8738375/Explore-logs-2022-05-20.10.48.46.txt)

**Comment by erkannt** [comment]
[404-dois-18-19-20th-of-may.txt](https://github.com/sciety/sciety/files/8738445/404-dois-18-19-20th-of-may.txt)

**Comment by giorgiosironi** [comment]
[doi-dot-org-status.txt](https://github.com/sciety/sciety/files/8738651/doi-dot-org-status.txt)

**Comment by giorgiosironi** [comment]
```
$ cat check-doi-dot-org.sh 
curl -s -o /dev/null -w "$1 %{http_code}\n" "https://doi.org/$1"
```

**Comment by giorgiosironi** [comment]
Tidied up version:
[404-dois-18-19-20th-of-may.txt](https://github.com/sciety/sciety/files/8738713/404-dois-18-19-20th-of-may.txt)

**Comment by LinaKind** [comment]
[crossref-works-checks.txt](https://github.com/sciety/sciety/files/8738759/crossref-works-checks.txt)

**Comment by LinaKind** [comment]
[biorxiv-status.txt](https://github.com/sciety/sciety/files/8740445/biorxiv-status.txt)
[medrxiv-status.txt](https://github.com/sciety/sciety/files/8740448/medrxiv-status.txt)
