### ISSUE TITLE
Investigate DOIs failing in crossref

### ISSUE THREAD

**Issue by davidcmoulton** [sciety/sciety#1602]
Discovered following failing DOIs via associated script:

10.1101/116376
10.1101/2020.12.28.424600
10.1101/2021.08.27.457974
10.1101/2021.11.10.467957
10.1101/2022.01.26.477692
10.1101/2022.01.31.478459
10.1101/2022.03.15.22272434
10.1101/2022.03.16.22271100
10.1101/2022.05.07.491022
10.1101/2022.05.09.491179
10.1101/2022.05.10.22274889
10.1101/2022.05.10.490700
10.1101/2022.05.10.491266
10.1101/2022.05.16.492112
10.1101/2022.05.24.22275411
10.1101/2022.05.24.22275498
10.1101/2022.05.25.22275562
10.1101/28.8.8.8148
10.1101/856533
10.1101/856536
10.1101/856547
10.1101/856553
10.1101/856556
10.1101/856558
10.1101/856566
10.1101/856570
10.1101/856571
10.1101/856572
10.1101/856579
10.1101/856582
10.1101/861592
10.1101/861594
10.1101/861603
10.1101/861611
10.1101/861615
10.1101/861620
10.1101/861622
10.1101/861627
10.1101/861628
10.1101/861630
10.1101/864115
10.1101/864119
10.1101/864120
10.1101/864122
10.1101/864142
10.1101/864147
10.1101/864151
10.1101/864156
10.1101/864157
10.1101/864158
10.1101/864160
10.1101/864163
10.1101/864164
10.1101/865970
10.1101/865975
10.1101/865985
10.1101/865991
10.1101/865993
10.1101/865997
10.1101/866015
10.1101/866016
10.1101/866018
10.1101/872183
10.1101/872187
10.1101/872201
10.1101/872204

**Comment by giorgiosironi** [comment]
Ran script on the sample provided in the description:
[doi-status-check.csv](https://github.com/sciety/sciety/files/8804195/doi-status-check.csv)
The biggest section is DOIs that do not exist anywhere.

**Comment by davidcmoulton** [comment]
Illustration of Bing requesting a bunch of dodgy 'dois':

https://sciety.grafana.net/explore?orgId=1&left=%7B%22datasource%22:%22grafanacloud-sciety-logs%22,%22queries%22:%5B%7B%22refId%22:%22C%22,%22expr%22:%22%7Bapp_kubernetes_io_instance%3D%5C%22ingress-nginx%5C%22%7D%5Cn%7C%20json%20%7C%20ingress_name%3D%5C%22sciety--prod--frontend%5C%22%20%7C%20http_user_agent%3D%5C%22Mozilla%2F5.0%20(compatible;%20bingbot%2F2.0;%20%2Bhttp:%2F%2Fwww.bing.com%2Fbingbot.htm)%5C%22%20%7C%20status%3D%5C%22404%5C%22%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D
