### ISSUE TITLE
Vimeo only plays when one accepts statistics cookies

### ISSUE THREAD

**Issue by erkannt** [sciety/sciety#1688]

**Comment by giorgiosironi** [comment]
Created:
https://support.cookiebot.com/hc/en-us/requests/105481
(credentials are in 1Password for `Cookiebot Support`)

**Comment by erkannt** [comment]
[Sciety - Video embedding and cookie consent.pdf](https://github.com/sciety/sciety/files/9314793/Sciety.-.Video.embedding.and.cookie.consent.pdf)
![Sciety - Video embedding and cookie consent](https://user-images.githubusercontent.com/19282025/184313911-2638797f-a5c7-4107-baaa-9d2fffa4f63d.jpg)
