### ISSUE TITLE
Spike: introduce a policy that reacts to UserSavedArticle events on startup

### ISSUE THREAD

**Issue by LinaKind** [sciety/sciety#1719]

**Comment by LinaKind** [comment]
After seeing too many events, as an example, narrowed down to one specimen user, `1122522190791028737`, user list url `http://localhost:8080/users/maria_eichel/lists/saved-articles`.

**Comment by giorgiosironi** [comment]
We discovered how to add a background policy to run at startup. We see limited value in the inside-out approach, and we are closing in favor of future outside-in spikes that are narrow in scope and go deep from UI to Domain Events/database/Commands.
