### ISSUE TITLE
Investigate `/evaluations` failures for EPP product

### ISSUE THREAD

**Issue by davidcmoulton** [sciety/sciety#1830]

**Comment by davidcmoulton** [comment]
Hypothesis 429 responses suspected to be during EPP load testing https://sciety.grafana.net/d/YZi1h58Gz/application-metrics?orgId=1&viewPanel=20&from=1665675016194&to=1665676803644&var-interval=1m

**Comment by giorgiosironi** [comment]
There seem to be no hard stop on requests made to Hypothes.is when rate limiting happens: we are able to serve 200 responses in the ~5 minutes after the rate limiting errors are logged.
