### ISSUE TITLE
Add Life Science Editors Foundation Group

### ISSUE THREAD

**Issue by themarkness** [sciety/sciety#2077]
# Joining form info

**Group name** 
Life Science Editors Foundation

**Hypothesis username**
https://hypothes.is/users/lifescienceeditorsfoundation

**Group URL slug** 
life-science-editors-foundation

**Logo**
<img width="268" alt="logo_lsef" src="https://user-images.githubusercontent.com/1681436/219688627-f160acea-4d73-49fe-ba0e-7f4b61974d3e.png">

**Brief description** 
The Life Science Editors Foundation aims to increase representation and eliminate inequity in the scientific community.

**Subject area**
Biology, Biomedicine

# Page markdown

## Who we are
The scientific community, particularly at leadership levels, suffers from a lack of diversity. This disparity arises, in part, from unfair and systemic barriers to progress. Scientists who have been excluded from the community have fewer role models and smaller networks, which makes it more challenging to climb the career ladder. They often carry a greater burden inside and outside work. We want to change the scientific culture to make it more inclusive, equitable, and diverse. To achieve this goal, we offer [JEDI awards](https://lifescienceeditors.org/apply/) and we review preprints authored by scientists from underrepresented groups to highlight and support their contributions.

[Visit our site](https://www.lifescienceeditors.org)
[Donate](https://secure.givelively.org/donate/life-science-editors-foundation/accelerate-equity-in-science)
[Linked In]https://www.linkedin.com/company/life-science-editors-foundation)
[Twitter](https://twitter.com/LSEFoundation)

## Our evaluation model

The Life Science Editors Foundation comprises volunteers with expertise in publishing, career development and research. Our assessment includes: the name of the reviewer, potential conflicts of interest and, in our view, the background of the study, the main question, the advance and the significance.

## PReF

The Preprint Review Features [(PReF)](https://osf.io/8zj9w/) describes key elements of each group’s evaluation activities.

<dl class="group-page-pref">
    <dt>Review requested by</dt>
    <dd>Authors, Non-authors</dd>
    <dt>Reviewer selected by</dt>
    <dd>Author, Self-nominated, Editor, service or community</dd>
    <dt>Public interaction</dt>
    <dd>Included</dd>
    <dt>Inclusion of author response</dt>
    <dd>Included</dd>
    <dt>Decision</dt>
    <dd>None</dd>
    <dt>Review coverage</dt>
    <dd>Complete paper, specific aspects</dd>
    <dt>Reviewer identity known to</dt>
    <dd>Public</dd>
    <dt>Competing interests</dt>
    <dd>Checked</dd>
</dl>

## Our team

- Angela Andersen
- Sabbi LallHelen Pickersgill
- Giovanna Guerrero-Medina
- Mandë Holford
- Alana Welm
- Magdalena Zernicka-Goetz
- Marie Bao
- Kathryn Claiborn
- Stacie Dodgson
- Carol Featherstone
- Caroline Hendry
- Shawna Hiley
- Rosy Hosking
- Susan Jones
- Milka KosticC
- onnie Lee
- Christina Lilliehook
- Robert Mahen
- Emilie Marcus
- Brandi Mattson
- Kristen Mueller
- Rebecca Parker
- April Pawluk
- John Pham
- Josephine Rodriguez
- Aruni Senaratne
- Diana Stafforini
- Li-Kuo Su
- Matt Velinder
- Usha Vivegananthan
- Diana Walsh
- Ellen Wilson
- Katrina Woolcock

## Content license

Content is licensed under the [Creative Commons CC BY 4.0](https://creativecommons.org/licenses/by/4.0/) unless otherwise specified.

**Comment by erkannt** [comment]
```sh
curl -v -H "Authorization: Bearer secret" -X POST http://localhost:8080/api/add-group -H "Content-type: application/json" -d '{"groupId": "f2c9eafa-6e24-4549-819c-09179e642b08", "avatarPath": "https://raw.githubusercontent.com/sciety/group-static-files/main/example-group.png", "descriptionPath": "life-science-editors--1480d2dd-463f-4834-8e81-d89c8ae2b86f.md", "homepage": "", "name": "Life Science Editors Foundation", "shortDescription": " The Life Science Editors Foundation aims to increase representation and eliminate inequity in the scientific community.", "slug": "life-science-editors-foundation"}'
```

**Comment by LinaKind** [comment]
curl -v -H "Authorization: Bearer secret" -X POST http://localhost:8080/api/add-group -H "Content-type: application/json" -d '{"groupId": "f2c9eafa-6e24-4549-819c-09179e642b08", "avatarPath": "https://raw.githubusercontent.com/sciety/group-static-files/main/life-science-editors-foundation.png", "descriptionPath": "life-science-editors--1480d2dd-463f-4834-8e81-d89c8ae2b86f.md", "homepage": "", "name": "Life Science Editors Foundation", "shortDescription": " The Life Science Editors Foundation aims to increase representation and eliminate inequity in the scientific community.", "slug": "life-science-editors-foundation"}'
