### ISSUE TITLE
Reflect changes to Rapid Reviews Infectious Diseases group

### ISSUE THREAD

**Issue by themarkness** [sciety/sciety#2169]
Rapid Reviews Covid-19 group has evolved to become Rapid Reviews Infectious Diseases.

As such we will need to reflect these changes in Sciety.

Our domain model does not currently support renaming groups, so we need to consider how to approach this. The group have said that they do not link to Sciety from their own pages and are happy for any URLs to be updated

Current URL slug  https://sciety.org/groups/rapid-reviews-covid-19/
**Updated URL slug** https://sciety.org/groups/rapid-reviews-infectious-diseases/

**Brief Description:**
RR\ID (Rapid Reviews\Infectious Diseases) is an open-access overlay journal that accelerates peer review of important infectious disease-related research preprints. 

**Who we are summary:**
RR\ID (Rapid Reviews\Infectious Diseases) is an open-access overlay journal that accelerates peer review of important infectious disease-related research preprints. We are an evolution of[ Rapid Reviews: COVID-19 (RR\C19)](https://rrid.mitpress.mit.edu/rrc19), which won the[ 2022 PROSE Award for Innovation in Journal Publishing](https://rapidreviewscovid19.mitpress.mit.edu/pub/bwdope09) for introducing a new peer review model facilitating rapid publishing of COVID-19-related research preprints. RR\ID expands beyond COVID-19 to advance our understanding of infectious diseases, leaning on a similar “curate, review, publish” model. RR\ID aims to prevent the dissemination of false/misleading scientific information and accelerate the validation and diffusion of robust findings. RR\ID aims to increase the application of science for the common good, responding to infectious disease challenges throughout the world.

**Logo**
![RR-ID_Social](https://user-images.githubusercontent.com/1681436/227901627-3c484004-5f14-4ed1-9937-1d3c10b5c10d.png)

**Comment by giorgiosironi** [comment]
New homepage seems to be https://rrid.mitpress.mit.edu/guidelines, that is where the existing one redirects.
