### ISSUE TITLE
Expand search to cover Research Square and Scielo Preprints

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#2192]

**Comment by giorgiosironi** [comment]
Test case for Research Square:
http://localhost:8080/search?category=articles&query=A+cell+therapy+approach+to+prevent+muscle+atrophy+and+paralysis+in+an+aggressive+mouse+model+of+ALS

**Comment by davidcmoulton** [comment]
http://localhost:8080/search?category=articles&query=Authorship+concentration+in+health+sciences+journals+from+Latin+America+and+the+Caribbean+&evaluatedOnly=true
