### ISSUE TITLE
Introduce a related articles section in the article page, relying on the third party call

### ISSUE THREAD

**Issue by LinaKind** [sciety/sciety#2273]
https://api.semanticscholar.org/api-docs/recommendations#tag/Paper-Recommendations/operation/get_papers_for_paper

**Comment by LinaKind** [comment]
```
curl "https://api.semanticscholar.org/recommendations/v1/papers/forpaper/DOI:10.1101/2022.07.28.501567?fields=externalIds" | jq
```

**Comment by davidcmoulton** [comment]
Item 73 of the `recommendedPapers` array, lacks a `DOI` property on its `externalIds` in https://api.semanticscholar.org/recommendations/v1/papers/forpaper/DOI:10.1101/2022.06.02.490114?fields=externalIds,authors,title
