### ISSUE TITLE
Add curation statements for the eLife articles tagged on Hypothes.is with "summary" and user "public_reviews"

### ISSUE THREAD

**Issue by kevinrutherford** [sciety/sciety#2371]

**Comment by kevinrutherford** [comment]
TO get a JSON payload listing all eLife summaries:

```
curl "https://api.hypothes.is/api/search?user=public_reviews;tag=Summary"
```

**Comment by erkannt** [comment]
To get a uri and hypothesis id:

`curl "https://api.hypothes.is/api/search?user=public_reviews;tag=Summary" | jq '.rows | .[] | {id: .id, uri: .uri}' | sed -e 's/uri.*content\//articleId":"/'`

**Comment by LinaKind** [comment]
/Users/linakinduryte/sciety/elife-author-responses-from-hypothesis-page-one.txt

**Comment by LinaKind** [comment]
[elife-author-responses-from-hypothesis-page-one.txt](https://github.com/sciety/sciety/files/11746508/elife-author-responses-from-hypothesis-page-one.txt)

**Comment by davidcmoulton** [comment]
[elife-curation-statement-evaluation-locators-page-one.txt](https://github.com/sciety/sciety/files/11747380/elife-curation-statement-evaluation-locators-page-one.txt)

**Comment by giorgiosironi** [comment]
Reference for API calls:
https://h.readthedocs.io/en/latest/api-reference/v1/#tag/annotations/paths/~1search/get
