### ISSUE TITLE
Support a PsyArxiv article for eLife EPP

### ISSUE THREAD

**Issue by kevinrutherford** [sciety/sciety#2404]
Relevant article: https://staging.sciety.org/articles/activity/10.31234/osf.io/mgn32

**Comment by LinaKind** [comment]
Incorrectly recorded evaluation:
```
01635d82-4e36-4f61-9310-60b794be0e26,EvaluationRecorded,2023-06-26 18:23:58.355,"{""authors"": [], ""groupId"": ""b5f31635-d32b-4df9-92a5-0325a1524343"", ""articleId"": ""doi:10.31219/osf.io/preprints/metaarxiv/smxe5"", ""publishedAt"": ""2022-10-25T10:20:10.925Z"", ""evaluationLocator"": ""hypothesis:m2NDkFROEe2TwA-8gdhglQ""}"
```

**Comment by giorgiosironi** [comment]
The new run didn't go over 54% CPU:
https://sciety.grafana.net/d/a164a7f0339f99e89cea5cb47e9be617/kubernetes-compute-resources-workload?orgId=1&refresh=30s&var-datasource=default&var-cluster=cloud&var-namespace=default&var-type=deployment&var-workload=sciety--staging--frontend&var-lokids=All&from=now-6h&to=now

Running again the same job on staging, to observe idempotence and the baseline load after we have already caught up with the backfilled 5000+ evaluations.
