### ISSUE TITLE
Implement a false door for user to be notified on the changes to a followed list

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#2485]

**Comment by davidcmoulton** [comment]
follow.it seems to only supports feeds set up manually in the UI, so doesn't match our use case, where users may be creating lists on a whim.

**Comment by LinaKind** [comment]
<img width="564" alt="image" src="https://github.com/sciety/sciety/assets/67826881/32f5956d-571e-4f71-bd4e-581cdf61c1ac">
