### ISSUE TITLE
We want to send newsletters from Civi and avoid them going to spam

### ISSUE THREAD

**Issue by LinaKind** [sciety/sciety#2502]

**Comment by LinaKind** [comment]
This issue still present itself when using the Civi forms. The agency who have designed the form has provided the following information:
All you need to do is log in to your DNS provider account and add the below:
You need to add:
mail._domainkey.[sciety.org](http://sciety.org/)	IN	TXT “v=DKIM1; h=sha256; k=rsa; p=MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAzueGZSRlbkJHrZ5gJXog5exqBeFgyQge7Mt+/ikIDf4+M54BiCVZriB4vTqMkJjttSrSZbYzUSaXF777uyEK+Inf6eAmh7EomSBTGtBOHfeT3BCoZgWyp5V+g6nc8qrPzIKj5cTif7Zbsef4rkhTd1fElC14+seFaEAPXtHqSsmMaMyk41ATcj2KCaeJPGk0wJYTgRIXpOode9”
	 “oQjtR0UMYwMfIFTRbhdDoE37BHy1BaG1HCU02XpkjHwN56Ys7aNo8tHOyLv6gj25V51PX08RYtS2xT6DvVdq00EYFHBOeMTk3tPhGcr0FZVrde1FjCnX+hQYZRw8MbXPQfCUG38wIDAQAB”
And:
[sciety.org](http://sciety.org/) TXT “v=spf1 include:_[spf.google.com](http://spf.google.com/) ip4:89.16.178.40 ~all”
If there may also be other servers sending from this domain you should be able to alter SPF to include them.

**Comment by giorgiosironi** [comment]
We tested these two DNS records for syntax with these tools:
https://www.mimecast.com/products/dmarc-analyzer/dkim-check/
https://www.mimecast.com/products/dmarc-analyzer/spf-record-check/
