### ISSUE TITLE
Remove incorrect reviews from article evaluated by Review Commons

### ISSUE THREAD

**Issue by LinaKind** [sciety/sciety#2511]
https://sciety.org/articles/activity/10.1101/055574 removing four evaluations from this preprint.

**Comment by LinaKind** [comment]
```
curl -v -H "Authorization: Bearer secret" -X POST http://localhost:8080/api/record-evaluation-removal -H "Content-type: application/json" -d '{"evaluationLocator": "hypothesis:63FcnN1kEe2uAlt4T5JsWQ"}'
```

**Comment by giorgiosironi** [comment]
Investigated [missing evaluations that have been removed by third parties on Hypothes.is, and now result in 404](https://sciety.grafana.net/explore?panes=%7B%22je1%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22sum%20by%20%28payload_error_url%29%20%28count_over_time%28%5Cn%5Cn%7Bapp_kubernetes_io_name%3D%5C%22sciety%5C%22,app_kubernetes_io_instance%3D%5C%22sciety--prod%5C%22%7D%5Cn%7C%20json%5Cn%7C%20level%20%3D%20%5C%22warn%5C%22%20%7C%20message%3D%60Third%20party%20data%20not%20found%60%20%7C%20payload_error_url%3D~%60https:%2F%2Fapi.hypothes.is%2Fapi%2Fannotations%2F.%2A%60%5Cn%5Cn%5B30d%5D%29%29%22,%22queryType%22:%22instant%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22,%22hide%22:false%7D%5D,%22range%22:%7B%22from%22:%22now-2d%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1#).

Total count is 379 for the last 30 days.
[Explore-data-2023-08-07 14 59 52.csv](https://github.com/sciety/sciety/files/12280664/Explore-data-2023-08-07.14.59.52.csv)
