### ISSUE TITLE
Don't cache error responses from Crossref

### ISSUE THREAD

**Issue by davidcmoulton** [sciety/sciety#2514]
For 200 responses from Crossref:

- Don't cache the empty string
- Don't cache "unexpected HTTP status: status=503\n(org.crossref.common.exceptions.IORuntimeException occured 7/27/23 6:21 PM)"

**Comment by davidcmoulton** [comment]
https://axios-cache-interceptor.js.org/config/request-specifics#cache-cachepredicate

**Comment by davidcmoulton** [comment]
https://sciety.grafana.net/explore?orgId=1&panes=%7B%22ObO%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22sum%20by%20%28message,%20payload_error_status%29%20%28count_over_time%28%5Cn%7Bapp_kubernetes_io_name%3D%5C%22sciety%5C%22,app_kubernetes_io_instance%3D%5C%22sciety--prod%5C%22%7D%5Cn%7C%20json%20%7C%20__error__%3D%5C%22%5C%22%5Cn%7C%20level%20%3D%20%5C%22error%5C%22%20%7C%20payload_error_message%3D%60Empty%20response%20from%20Crossref%60%5Cn%5B7d%5D%29%29%22,%22hide%22:true,%22queryType%22:%22instant%22,%22refId%22:%22A%22%7D,%7B%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22%7Bapp_kubernetes_io_name%3D%5C%22sciety%5C%22,app_kubernetes_io_instance%3D%5C%22sciety--prod%5C%22%7D%5Cn%7C%20json%20%7C%20__error__%3D%5C%22%5C%22%5Cn%7C%20level%20%3D%20%5C%22error%5C%22%20%7C%20message%3D%60Unable%20to%20parse%20document%60%20%7C%20payload_error_message%3D%60Empty%20response%20from%20Crossref%60%22,%22hide%22:false,%22queryType%22:%22range%22,%22refId%22:%22B%22%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1

**Comment by LinaKind** [comment]
Proof that we see cache misses on an article that was affected by this crossref issue:

<img width="1201" alt="image" src="https://github.com/sciety/sciety/assets/67826881/028ac092-152c-44b1-8627-ea6b58e109a3">
