### ISSUE TITLE
Not seeing articles published by Biorxiv after August 7th, on EuropePMC search

### ISSUE THREAD

**Issue by LinaKind** [sciety/sciety#2577]

**Comment by LinaKind** [comment]
Search does not return articles more recent than 8th of August:
https://europepmc.org/search?query=PUBLISHER%3A%22bioRxiv%22&page=1&sortBy=FIRST_PDATE_D%2Bdesc

**Comment by giorgiosironi** [comment]
Pending response from EuropePMC's Google Group:
https://groups.google.com/a/ebi.ac.uk/g/epmc-webservices/c/b9XFRE0P8hg

**Comment by giorgiosironi** [comment]
Have received a direct email mentioning a configuration issue that has been resolved.
The search on EuropePMC for Biorxiv articles looks better for recently published content, but:
https://europepmc.org/search?query=PUBLISHER%3A%22bioRxiv%22&page=31&sortBy=FIRST_PDATE_D%2Bdesc
still has very few articles published between 2023-08-08 and 2023-08-21.
https://staging.sciety.org/search?category=articles&query=10.1101%2F2023.08.08.549832 is still missing.
