### ISSUE TITLE
Allow a user to create annotation at the same time as they add an article to their list

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#2699]

**Comment by davidcmoulton** [comment]
In passing, we noticed this visual overlap of the speech bubble projection over the author name:

<img width="1190" alt="Screenshot 2023-10-02 at 11 30 52" src="https://github.com/sciety/sciety/assets/2893480/8bf1aa3c-2538-437a-a0d9-67650d0d69f2">
