### ISSUE TITLE
Reflect evaluation author changes in the docmaps

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#2758]
https://sciety.org/docmaps/v1/articles/10.1101/2023.09.01.555894.docmap.json

An evaluation for this article has been updated with the correct authors in the database, the change is not currently being reflected in the Docmap.

- `participants` should contain 3 authors
- `updated` should be `2023-10-18T...`

**Comment by LinaKind** [comment]
[Link ](https://sciety.grafana.net/explore?panes=%7B%22W8g%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp_kubernetes_io_name%3D%5C%22sciety%5C%22,app_kubernetes_io_instance%3D%5C%22sciety--prod%5C%22%7D%5Cn%7C%20json%20%7C%20__error__%3D%5C%22%5C%22%5Cn%7C%20message%20%3D%20%5C%22Received%20HTTP%20request%5C%22%5Cn%7C%20payload_url%20%3D~%20%5C%22%2Fdocmaps%2Fv1%2Findex.%2A%5C%22%20%7C%20payload_url%21%3D%60%2Fdocmaps%2Fv1%2Findex%3FupdatedAfter%3D2020-08-12%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D%7D&schemaVersion=1&orgId=1)to grafana log for docmap index requests.
