### ISSUE TITLE
Update the authors on Biorxiv for a very old evaluation from PREreview, because we suspect the docmap index is dodgy

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#2771]
https://sciety.org/docmaps/v1/articles/10.1101/833392.docmap.json
```
doi:10.5281/zenodo.3678326
```

**Comment by LinaKind** [comment]
Check biorXiv if the evalation now displays an author:

https://www.biorxiv.org/content/10.1101/833392v3
