### ISSUE TITLE
Display an evaluation for the Access Microbiology group

### ISSUE THREAD

**Issue by LinaKind** [sciety/sciety#2782]

**Comment by giorgiosironi** [comment]
We recorded one evaluation for this group on production, using `doi` as an existing evaluation locator service:
https://sciety.org/articles/activity/10.1099/acmi.0.000530.v1
If we get this wrong, we can erase this evaluation and start again.

**Comment by giorgiosironi** [comment]
XML for version 1 of the article that the evaluation relates to: https://www.microbiologyresearch.org/docserver/fulltext/acmi/10.1099/acmi.0.000530.v1/acmi.0.000530.v1.xml
