### ISSUE TITLE
Investigate use of a non-DOI as an article-page identifier

### ISSUE THREAD

**Issue by kevinrutherford** [sciety/sciety#2793]
**Objective:** do whatever hackery and hardcoding is necessary to show the full lifecycle / history / journey / activity of the Access Microbiology article whose first version has DOI 10.1099/acmi.0.000569.v1, but using a non-DOI in the URL to its article page.

**Approach:** Simulate a non-DOI article lifecycle ID by permitting the route `/articles/activity/10.1099-acmi.0.000569.v1`. (This was selected because it is easy to generate: visit the "real" article page and simply change the `/` in the DOI part of the URL to be `-` instead.

Todo:

- [x] allow `ArticleId` to accept any string, not just valid DOIs
- [x] Shim `fetchArticle` to return hardcoded details for that article lifecycle ID
- [ ] Shim the fetching of article versions with hardcoded data for the versions of this article
- [x] Shim the fetching of evaluations so that this article lifecycle ID maps to the evaluations for `10.1099/acmi.0.000569.v1`.
- [ ] Link each article version in the page to the corresponding DOI on Access Microbiology
- [ ] (other stuff we haven't discovered yet...)

**Comment by erkannt** [comment]
![image](https://github.com/sciety/sciety/assets/19282025/00d3e601-ad8f-46a2-9846-e29982ac8fed)
