### ISSUE TITLE
Improve observability of Crossref article fetching

### ISSUE THREAD

**Issue by LinaKind** [sciety/sciety#2802]

**Comment by giorgiosironi** [comment]
A few examples of articles legitimately missing authors on the preprint server, or in the machine-readable Crossref record:
https://www.biorxiv.org/content/10.1101/501551v1
https://www.medrxiv.org/content/10.1101/2023.09.15.23295616v1
https://www.medrxiv.org/content/10.1101/2020.06.29.20142430v1
