### ISSUE TITLE
Research spike: enable Access Microbiology in the EuropePMC search filter

### ISSUE THREAD

**Issue by davidcmoulton** [sciety/sciety#2890]
Working in here: https://github.com/sciety/sciety/tree/spike/enable-access-microbiology-in-search

**Comment by davidcmoulton** [comment]
Working with article https://www.microbiologyresearch.org/content/journal/acmi/10.1099/acmi.0.000626.v2

**Comment by giorgiosironi** [comment]
Crossref provides front matter for v3 (the journal article), but it does not contain formatting on the title whereas it does contain formatting in the abstract. We assume that both a paper card and a paper activity page should show front matter from the most recent paper expression, which is v3 here (regardless of the fact that it is the journal article expression and not the most recent preprint expression).
