### ISSUE TITLE
For a specific Access Microbiology paper, searching for its title should link to the canonical UUID-based paper activity page

### ISSUE THREAD

**Issue by davidcmoulton** [sciety/sciety#2891]
Using this search results page: http://localhost:8080/search?query=The+genome+of+a+steinernematid-associated+Pseudomonas+piscis+bacterium+encodes+the+biosynthesis+of+insect+toxins

**Comment by giorgiosironi** [comment]
Closed in favor of dedicating time to the content of the card.
