### ISSUE TITLE
Spike: given an expression DOI, use Crossref to find all expression DOIs for that paper

### ISSUE THREAD

**Issue by davidcmoulton** [sciety/sciety#2895]
Using the DOI [10.1099/acmi.0.000667.v3](http://localhost:8080/articles/activity/10.1099/acmi.0.000667.v3) for example.

**Comment by giorgiosironi** [comment]
How to find v2 starting from v1, which has no `relation` to it:
https://api.crossref.org/works?filter=relation.object:10.1099/acmi.0.000694.v1,type:posted-content
