### ISSUE TITLE
Allow previously preprinted journal articles to be included in the article activity feed

### ISSUE THREAD

**Issue by LinaKind** [sciety/sciety#2956]
http://localhost:8080/articles/activity/10.1099/acmi.0.000569.v1 should also include expression that points to a published journal article https://www.microbiologyresearch.org/content/journal/acmi/10.1099/acmi.0.000569.v3

**Comment by davidcmoulton** [comment]
[b4dd827](https://github.com/sciety/sciety/commit/b4dd8276c3d2ebdee9d4c4a2305e5371fc081177) allows journal articles to show up on the paper activity page. It's buggy as e.g. it allows the journal article http://localhost:8080/articles/activity/10.1099/jgv.0.001944 to show up and say it's on Access Microbiology when it's not, it an article from the Journal of General Virology.

**Comment by davidcmoulton** [comment]
Investigations reveal that both the Access Microbiology journal and other microbiology journals use the same domain `microbiologyresearch.org`. We display "published on Access Microbiology", on checking that the domain is `microbiologyresearch.org`.

**Comment by giorgiosironi** [comment]
We will be trying to restrict the search Crossref query to consider 4 types of relation rather than not filtering at all:
https://api.crossref.org/works?filter=relation.object:10.1101/2023.07.27.550898,type:posted-content,type:journal-article,relation.type:has-version,relation.type:is-version-of,relation.type:has-preprint,relation.type:is-preprint-of

**Comment by giorgiosironi** [comment]
We suspect 503 responses from Crossref are getting into our cache:
```
app-1  | {
app-1  |   "timestamp": "2024-01-18T10:38:42.019Z",
app-1  |   "level": "debug",
app-1  |   "message": "Response time",
app-1  |   "payload": {
app-1  |     "url": "https://api.crossref.org/works/10.21203/rs.3.rs-1828415/v3/transform",
app-1  |     "durationInMs": 3,
app-1  |     "responseStatus": 200,
app-1  |     "requestId": "bf85aef0-b5ed-11ee-8550-fbff1f28a786"
app-1  |   }
app-1  | }
app-1  | {
app-1  |   "timestamp": "2024-01-18T10:38:42.019Z",
app-1  |   "level": "warn",
app-1  |   "message": "Unable to find authors",
app-1  |   "payload": {
app-1  |     "expressionDoi": "10.21203/rs.3.rs-1828415/v3",
app-1  |     "response": "unexpected DoiDBrecord.get issue: null\n(org.crossref.common.exceptions.IORuntimeException occured 1/18/24 5:35 AM)",
app-1  |     "requestId": "bf85aef0-b5ed-11ee-8550-fbff1f28a786"
app-1  |   }
app-1  | }
app-1  | {
app-1  |   "timestamp": "2024-01-18T10:38:42.019Z",
app-1  |   "level": "warn",
app-1  |   "message": "Unable to find server",
app-1  |   "payload": {
app-1  |     "expressionDoi": "10.21203/rs.3.rs-1828415/v3",
app-1  |     "response": "unexpected DoiDBrecord.get issue: null\n(org.crossref.common.exceptions.IORuntimeException occured 1/18/24 5:35 AM)",
app-1  |     "requestId": "bf85aef0-b5ed-11ee-8550-fbff1f28a786"
app-1  |   }
app-1  | }
app-1  | {
app-1  |   "timestamp": "2024-01-18T10:38:42.020Z",
app-1  |   "level": "info",
app-1  |   "message": "Sent HTTP response",
app-1  |   "payload": {
app-1  |     "status": 503,
app-1  |     "durationInMs": 5,
app-1  |     "requestId": "bf85aef0-b5ed-11ee-8550-fbff1f28a786"
app-1  |   }
app-1  | }
```

**Comment by davidcmoulton** [comment]
For testing: 
https://elifesciences.org/articles/90184 relating to http://localhost:8080/articles/activity/10.7554/eLife.90184.4

**Comment by LinaKind** [comment]
[Link to Grafana query that filters out xml and json responses](https://sciety.grafana.net/explore?schemaVersion=1&panes=%7B%22xlg%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22%7Bapp_kubernetes_io_name%3D%5C%22sciety%5C%22,app_kubernetes_io_instance%3D%5C%22sciety--prod%5C%22%7D%5Cn%7C%20json%20%7C%20__error__%3D%5C%22%5C%22%5Cn%7C%20level%20%3D%20%5C%22warn%5C%22%5Cn%7C%20message%20%3D~%20%5C%22Response%20from%20Crossref%20.%2A,%20not%20caching%5C%22%20%7C%20payload_responseBody_message_type%3D%60work-list%60%22,%22hide%22:true,%22queryType%22:%22range%22,%22refId%22:%22B%22%7D,%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp_kubernetes_io_name%3D%5C%22sciety%5C%22,app_kubernetes_io_instance%3D%5C%22sciety--prod%5C%22%7D%20%21%3D%20%60%5C%22payload%5C%22:%7B%5C%22responseBody%5C%22:%5C%22%3C%3Fxml%60%5Cn%7C%20json%20%7C%20__error__%3D%5C%22%5C%22%5Cn%7C%20level%20%3D%20%5C%22debug%5C%22%5Cn%7C%20message%20%3D%20%5C%22Response%20from%20Crossref%20is%20valid,%20caching%5C%22%5Cn%7C%20payload_responseBody_message_type%21%3D%5C%22work-list%5C%22%5Cn%7C%20payload_responseBody_message_type%21%3D%5C%22posted-content%5C%22%5Cn%7C%20payload_responseBody_message_type%21%3D%5C%22journal-article%5C%22%5Cn%7C%20payload_responseBody%20%21~%20%60.%2Axml.%2A%60%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%221705570329789%22,%22to%22:%221705578218979%22%7D%7D%7D&orgId=1)

One of the examples that is returned using the above query:
```
{"timestamp":"2024-01-18T11:18:43.445Z","level":"debug","message":"Response from Crossref is valid, caching","payload":{"responseBody":"unexpected DoiDBrecord.get issue: null\n(org.crossref.common.exceptions.IORuntimeException occured 1/18/24 11:18 AM)","url":"https://api.crossref.org/works/10.1101/2020.04.27.20082362/transform","requestId":"56c0f270-b5f3-11ee-86f7-313eef9145c2"}}
```
