### ISSUE TITLE
Why do we see a Crossref record XML logged as Sciety Labs decoding failure?

### ISSUE THREAD

**Issue by LinaKind** [sciety/sciety#3018]

**Comment by LinaKind** [comment]
This is how the library generates keys to store cached responses:
https://axios-cache-interceptor.js.org/guide/request-id#custom-generator

**Comment by giorgiosironi** [comment]
This is the `defaultKeyGenerator`:
https://github.com/arthurfiorette/axios-cache-interceptor/blob/ad69e6d6e491cfa5fe2cb542bc90fd205fc823e3/src/util/key-generator.ts#L48
but it returns an object, not an integer.

**Comment by giorgiosironi** [comment]
The hashing of a request object to an integer seems to happen here:
https://github.com/arthurfiorette/axios-cache-interceptor/blob/ad69e6d6e491cfa5fe2cb542bc90fd205fc823e3/src/util/key-generator.ts#L44

**Comment by giorgiosironi** [comment]
The custom hashing library returns signed integers, which matches our finding of the keys we see in our Redis instance:
https://www.npmjs.com/package/object-code#getting-started

**Comment by giorgiosironi** [comment]
We found where the storage is invoked:
https://github.com/arthurfiorette/axios-cache-interceptor/blob/ad69e6d6e491cfa5fe2cb542bc90fd205fc823e3/src/interceptors/request.ts#L83C29-L83C36
and it uses `config.id`, which we know comes from the `generateKey` call which delegates to the hash library.
