### ISSUE TITLE
Get up to speed with Google Analytics -- HD

### ISSUE THREAD

**Issue by hdrury1** [sciety/sciety#302]

**Comment by hdrury1** [comment]
### Views

- Each new property is created with a default `All Website Data` view, which includes the raw, unfiltered data from the across the whole site
- We might consider creating different views to include, e.g. only visitors from a certain region, or only visitors using mobile
- Worth creating a `test` view to try out different filter configurations before finalising them in a new view
- Each new view only collects data from the time it was created

**Comment by hdrury1** [comment]
### Users and sessions

- Unique `cid` assigned to each user, stored in a browser cookie
- GA counts each `cid` as a new user -> if a stored `cid` is detected, a **returning user** is logged
- Returning users must use same browser/same device to be counted
- Can use `userID` feature to track users across browsers
- We can extend `session timeout` if we wish -> worth considering if one of our user goals is to read content on the site

### Content grouping and groups

- Content grouping -> [content groups] e.g. Articles -> [neuroscience, cell biology, computational biology]

### Scope

- `dementions` and `metrics` can be at hit level, session level, or user level
- You can only pair `dimentions` and `metrics` that have the same scope

### Conversions

- `macro` conversions = top level actions we want our users to perform
- `micro` conversions = actions users perform on the way to completing the macro conversion
- `micro` conversions help us learn about the user behaviour that leads to macro conversions, e.g. **A user clicking through to an article page may be a micro conversion, sharing the article via Twitter may be a macro conversion**

**Comment by BlueReZZ** [comment]
Worth noting that there's a new Google Analytics now. You use it by creating a new Google Analytics 4 property alongside existing properties

It uses machine learning to surface better metrics apparently so might be worth investing the time in now before we really get going

https://blog.google/products/marketingplatform/analytics/new_google_analytics/?

**Comment by hdrury1** [comment]
> Worth noting that there's a new Google Analytics now. You use it by creating a new Google Analytics 4 property alongside existing properties
> 
> It uses machine learning to surface better metrics apparently so might be worth investing the time in now before we really get going
> 
> https://blog.google/products/marketingplatform/analytics/new_google_analytics/?

Thanks @BlueReZZ! I'll look into it this week and report back in the next Gold Card feedback session.

**Comment by hdrury1** [comment]
### Custom dimensions and metrics

- We could conceivably use **custom dimensions** to help tailor the data we collect to our use case, e.g. we might want to be able to analyse user engagement based on the type of content they are consuming (review, summary, recommendation etc.)

**Comment by hdrury1** [comment]
### Segments

- **Subsets** of data
- Adding a segment will pervade throughout the reports until it is removed
- Allows us to compare two or more segments of users side-by-side across multiple reports, e.g. New vs Returning users, Desktop vs Mobile users, Twitter traffic vs Direct
- Can compare **up to 4** segments at once

**Comment by hdrury1** [comment]
### Multi-funnel reports

- Move beyond last click attribution to take into account prior marketing activities that went before
- Not relevant for us, as we have not set up `ecommerce` analytics

### Cohort analysis

- `cohorts` are usually time-bound, while `segments` are sliced by particular user behaviour or technology
- GA groups cohorts by **acquisition date**
- We can compare multiple cohorts over longer or shorter periods of time
- As in other reports, we can further **segment** cohorts to only display users exhibiting certain behaviours

**Comment by hdrury1** [comment]
### Converters vs non-converters

![Screenshot 2020-11-12 at 09 38 56](https://user-images.githubusercontent.com/17023702/98922947-f78ae200-24ca-11eb-856c-47b2dc0f42da.png)

We see that converters have longer session durations and a lower bounce rate
