### ISSUE TITLE
Change name to Sciety

### ISSUE THREAD

**Issue by hdrury1** [sciety/sciety#306]
## User visible changes

- [x] URLs: `sciety.org`
  - [x] deleage to route53 zone
  - [x] setup for `external-dns`
  - [x] setup for Ingress HTTPS
  - [x] redirect from `www`
  - [x] Twitter application callback URL
  - [x] switch `APP_ORIGIN` (breaks `hive.review` login)
  - [x] redirect `hive.review`?
  - [x] ~remove `oldHostname` from Helm chart~ can't remove as it provides the redirect
  - [x] ~remove hardcoded `hive.review` from `libero/infrastructure`~
  - [x] remove `example.sciety.org`
- [x] Email receival (`team@hive.review`)
- [x] Hero title on home page
- [x] Page titles
- [x] Pages
  - [x] Feedback form
  - [x] About Page
  - [x] Homepage
- [x] Assets
  - [x] ~[Favicon](#312)~
  - [x] ~[Logo](#312)~
- [x] explain sciety-eLife relationship in footer
  - [x] Add the following text "Sciety is operated by a team based within eLife Sciences Publications Limited. It is steered by all of its communities, readers and authors."
- [x] Twitter
  - [x] [Twitter Developer Portal App](https://developer.twitter.com/en/portal/dashboard)
  - [x] Username

## Stakeholder/community visible changes

- [x] Github
  - [x] repo
  - [x] org
  - [x] project
- [x] Slack channels (to what?)
  - [x] does it break the Github Actions notifications?
  - [x] does it break the CloudWatch alarm notifications?
    - [x] error on prod 
    - [x] Broken build
    - [x] Prod deploy
- [x] README
- [x] Update Google Analytics
- [x] Update Google Tag Manager
- [x] Update Data Studio?

## Under the hood changes

- [x] Docker
  - [x] new organization/user?
  - [x] IMAGE env var for builds and smoketest
  - [x] remove legacy push to liberoadmin
- [x] Codebase
  - [x] Helm
    - [x] all Kubernetes resources name
    - [x] remove old helm releases
        - [x] Staging
        - [x] Prod 
  - [x] CSS classes
  - [x] User agent
- [x] AWS
  - [x] `libero/infrastructure`
     - [x] move to sciety org
     - [x] remove mention of hive/libero/prc
       - [ ] ~remove from db (scary)~
     - [ ] ~Kubernetes cluster?~
     - [ ] ~make tf code less generic~
  - [x] not on infrastructure as code (we've fixed them, but haven't renamed)
    - [x] CloudWatch queries
    - [x] [CloudWatch metric and its namespace](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#metricsV2:graph=~())
    - [x] [CloudWatch alarm](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#alarmsV2:!alarmStateFilter=OK)
    - [x] [SNS topic](https://console.aws.amazon.com/sns/v3/home?region=us-east-1#/topics)
    - [x] [Lambda for Slack notification](https://console.aws.amazon.com/lambda/home?region=us-east-1#/functions/notifySlackFromSnsTopicError?tab=configuration)

**Comment by davidcmoulton** [comment]
NS value for DNS Simple:
```
ns-249.awsdns-31.com.
ns-1452.awsdns-53.org.
ns-1739.awsdns-25.co.uk.
ns-593.awsdns-10.net.
```

**Comment by giorgiosironi** [comment]
https://developer.twitter.com/en/portal/projects/1297805502685093888/apps/18623712/settings has the new settings, but needs the `hive.review` callback URLs removed later.

**Comment by giorgiosironi** [comment]
This is the [Lambda](https://console.aws.amazon.com/lambda/home?region=us-east-1#/functions/notifySlackFromSnsTopicError?tab=configuration) that notifies `#prc-general` of alerts; it has an environment variable for the channel name we could update.
