### ISSUE TITLE
Docmaps: Support inputs in actions, and deprecate inputs in steps

### ISSUE THREAD

**Issue by kevinrutherford** [sciety/sciety#3069]
The standard is evolving such that the `inputs` are moving from `steps` into `actions`. The SDK has been updated (https://github.com/Docmaps-Project/docmaps/pull/158) such that the `inputs` are supported in `actions` _and_ also still provided (but deprecated) in `steps` to support legacy clients that haven't yet migrated to the new standard.

This ticket will make an equivalent change to Sciety's docmaps.

**Comment by LinaKind** [comment]
Biorxiv and EuropePMC notified.
