### ISSUE TITLE
Avoid asymmetric matchers in jest where possible

### ISSUE THREAD

**Issue by kevinrutherford** [sciety/sciety#3072]

**Comment by erkannt** [comment]
Remaining usages of objectContaining are in `my-feed` (too messy, ran away) and `identify-feed-items` (matchers don't narrow a discriminated union, so can't trivially access all keys on the left side of the matcher).

```
$ grep -rl 'objectContaining' test
test/jest.setup.ts
test/html-pages/sciety-feed-page/construct-feed-item/identify-feed-items.test.ts
test/html-pages/my-feed-page/my-feed/followed-groups-activities.test.ts
```
