### ISSUE TITLE
Ensure medRxiv articles are not included in a PCI feed

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#311]
Problem: https://staging.sciety.org/articles/10.1101/2020.06.03.20119925 reviewed by a PCI is on Medrxiv, so the Biorxiv API doesn't provide version information (and it states incorrectly that it was published on Biorxiv). There's some post mortem material in this, because I notice by accident rather than via logs/metrics/observability

- [x] use JSDOM rather than regex
- [x] check that the article is on bioRxiv 
- [x] remove invalid dates
- [x] log an error when no article versions are found
- [x] update data

**Comment by thewilkybarkid** [comment]
No error message logged as we don't check that the `collection` from bioRxiv contains an entry, it's an empty list.

**Comment by thewilkybarkid** [comment]
https://staging.sciety.org/articles/10.1101/2020.06.03.20119925 still says 'We couldn't get version information from bioRxiv. Please try refreshing this page.' as it's not a bioRxiv article but we don't check that before displaying it. Not doing anything with it as it's not linked from anywhere, you can only access it with URL hacking.
