### ISSUE TITLE
Apply new colour & add logo

### ISSUE THREAD

**Issue by davidcmoulton** [sciety/sciety#312]
- [x] add Sciety logo
- [x] add favicon
- [x] add improved favicon
  - [x] add SVG
  - [x] fix ICO transparency
  - [x] add 32x32 PNG
- [x] general links
  - [x] change link colour to `rgb(207, 69, 0)`
  - [x] change link hover colour to `rgb(181, 56, 24)`
- [x] buttons
  - [x] introduce ` button--secondary` for article feed toggle
    - [x] colour `rgb(33, 33, 33)`
    - [x] background colour `rgb(255, 255, 255)`
    - [x] border `rgb(33, 33, 33)`
    - [x] hover state: background colour: pick a light grey
    - [x] make width consistent
  - [x] change the primary button colour to `rgb(207, 69, 0)`
  - [x] create new default button style:
    - [x] colour: `rgb(33, 33, 33)`
    - [x] background colour:  `rgb(255, 255, 255)`
    - [x] border: 1px solid `rgb(33, 33, 33)`
    - [x] border radius of 5px
    - [x] hover state:
      - [x] colour: `rgb(255, 255, 255)`
      - [x] background color `rgb(207, 69, 0)`
      - [x] border colour `rgb(207, 69, 0)`
  - [x] apply default button style to "Give us Feedback" button
  - [x] apply default button style to the "Unfollow" button
  - [x] make the colour of the search button icon `rgb(33, 33, 33)`
  - [x] make the background colour of the search button icon `rgb(255, 255, 255)`
  - [x] on hover, make the colour of the search button icon `rgb(255, 255, 255)` Can be achieved by putting the SVG inline, removing the fill from the SVG and setting the fill colour in our CSS.
  - [x] on hover, make the background color of the search button icon rgb(207, 69, 0)
- [x] footer
  - [x] add coloured backgrounds to the footer so the above text, 3 elements and copyright notice are delineated and the footer is suitably separate from the page content (e.g. see https://coko.foundation/)
- [x] editorial community boxes on home page
  - [x] change name colour to `rgb(33, 33, 33)`
  - [x] change hover state background colour to `rgb(247, 247, 247)`
  - [x] on hovering over any of it, including the button, ensure the colour of the name remains `rgb(181, 56, 24)`
- [x] home page feed
  - [x] remove primary colour from links
  - [x] on hover change to  `rgb(207, 69, 0)`
  - [x] new home page screenshot
- [x] refactor:
  - [x] remove Semantic UI from site header
  - [x] remove CSS custom properties for:
    - [x]  colours and instead set colours in style rules directly using sass
    - [x] `--MAX-SITE-WIDTH-REM` as sass variable instead
    - [x] use units everywhere (e.g. px-to-rem)
    - [x] colours that aren't in settings
  - [x] remove and .gitignore `.DS_Store` files
- [x] fix TODO re: flex on body
- [x] unset base `font-size` on `html`

**Comment by hdrury1** [comment]
![scietyFeedMockup](https://user-images.githubusercontent.com/17023702/98536006-f82f3880-227e-11eb-967f-6e4bc20b7b72.png)

Here's the feed image. Can we see what it looks like with a drop shadow applied?

**Comment by hdrury1** [comment]
![scietyFeedMockup](https://user-images.githubusercontent.com/17023702/99239543-1bb03100-27f3-11eb-8e97-63032f247ddc.png)
