### ISSUE TITLE
What can we do with Hypothesis tags?

### ISSUE THREAD

**Issue by hdrury1** [sciety/sciety#313]
eLife have begun tagging their hypothesis comments to distinguish between types of event and different authors. What can we do with this additional information?

- [x] ~Can we delineate between reviews, author responses and summaries within the article feed?~
  - ~option1: new event, new ingestions...~
  - ~option2: hardcode some events, deal with them in projections~
  - ~option3: edit hardcoded html~
  - [x] ~option4: hardcode metadata passed into renderer~
  - ~option5: develop scripts to produce different output that takes types into account~
  - ~option6: curl some stuff~
  - [x] ~option7: clone elife review script and dump types with it~
- [x] ~Can we delineate between different reviewers in the article feed? (e.g. 'Reviewed by Reviewer 1 for eLife')~
  - [x] ~we can ingest with clones script~
  - [x] ~we can change review feed item header~
- [x] curl to see how types show up
- [x] are there standards we can adopt for types

**Comment by davidcmoulton** [comment]
```bash
curl https://api.hypothes.is/api/annotations/hRt05CpdEeuQM1PK_kyF8A -s | jq .tags
```
returns:
```json
[
  "scietyType:ReviewSummary"
]
```

**Comment by davidcmoulton** [comment]
Starting from http://localhost:8080/articles/10.1101/2020.05.20.105023:

```bash
curl https://api.hypothes.is/api/annotations/SNNhnCpWEeu3kAt7ZWD_9g -s | jq .tags
```
returns
```json
[
  "InRevision",
  "scietyType:PeerReview"
]
```

**Comment by davidcmoulton** [comment]
Starting from http://localhost:8080/articles/10.1101/2020.07.22.216135:

```bash
curl https://api.hypothes.is/api/annotations/apzzNB0IEeurCB_njCeppA -s | jq .tags
```
returns:
```json
[
  "Author Response"
]
```

**Comment by giorgiosironi** [comment]
Starting from http://localhost:8080/articles/10.1101/2020.05.05.079749:
```bash
$ curl -s https://api.hypothes.is/api/annotations/wQl6oiWhEeulOksee8Kbcg | jq .tags
```
returns:
```json
[
  "scietyType:PeerReview",
  "scietyAuthor:Daniele Marinazzo"
]
```
(sent by @hdrury1)

**Comment by BlueReZZ** [comment]
A good resource that we should follow is Stencila's scholarly publishing extensions of schema.org at https://schema.stenci.la
They have now defined a `Review`  https://schema.stenci.la/review but we felt that adding microdata or JSON-LD to hypothesis just for us was too much effort. One to watch if we have a more structured way of obtaining content in future.

`Review` is available on schema.org too but it was not specific enough to provide a vocabulary for the types of review that we have `PeerReview` and `ReviewSummary`, and there was no concept of an `AuthorResponse`

Dublin Core does have a `type` element and it recommends using a fixed vocabulary as we have done. It also suggests using its own vocabulary but as with the schema.org choices they are not specific enough to differentiate our needs https://www.dublincore.org/specifications/dublin-core/dcmi-terms/#http%3a%2f%2fpurl.org%2fdc%2felements%2f1.1%2ftype

`creator` is used and defined well in both Dublin Core and schema.org

The conclusion was to use similar naming and not the full structure or reference to schema.org or Dublin Core for these tags as per https://github.com/sciety/sciety/issues/313#issuecomment-732257037 above
