### ISSUE TITLE
Investigate SciScore reports

### ISSUE THREAD

**Issue by BlueReZZ** [sciety/sciety#315]
SciScore Reports are the results of automated screening on preprints, currently run daily on any COVID related preprints on bioRxiv and medRxiv. Their reports are all published on their Twitter feed: https://twitter.com/SciscoreReports

The people at SciScore would like to see what their reports would look like on the site, in context, and also would like to know if they need to supply us with any additional information other then their hypothesis details

Their hypothesis user is `sciscore@hypothes.is`
## Attempt 1
@BlueReZZ had a quick go at adding a new community for them with this list of reviews:
```csv
2020-11-09T09:45:53.992661+00:00,10.1101/2020.11.06.372227,hypothesis:AdeASiJmEeul2fs9gQqCFg
```
It found the right API call, received a response but didn't display the text on the article page, here's the API call: https://api.hypothes.is/api/annotations/AdeASiJmEeul2fs9gQqCFg

This was taken from: https://www.biorxiv.org/content/10.1101/2020.11.06.372227v1#annotations:AdeASiJmEeul2fs9gQqCFg

## Examples sent to us by SciScore
These examples are notable because they include more comprehensive results
https://via.hypothes.is/https://www.biorxiv.org/content/10.1101/2020.11.06.372037v1#annotations:giY60CJlEeuLp9sCgQLM0Q
https://via.hypothes.is/https://www.biorxiv.org/content/10.1101/2020.10.31.362848v1#annotations:RoKzMByfEeusRXcsUx3i_Q
https://via.hypothes.is/https://www.biorxiv.org/content/10.1101/2020.11.07.367649v1#annotations:4RzaRCJlEeuMWE_fHpMWUA
https://via.hypothes.is/https://www.biorxiv.org/content/10.1101/2020.11.04.364315v1#annotations:yqnl0iBcEeum8sfloRXWfg
https://via.hypothes.is/https://www.biorxiv.org/content/10.1101/2020.10.31.363309v1#annotations:qmyrSBygEeu9GPe-MMMevQ

### To Do

- [x] Can we add Sciscore content?
- [ ] Is there anything we need to do our end to make the reports readable?
- [x] Is there anything SciScore needs to do their end? [yes](https://github.com/sciety/sciety/issues/315#issuecomment-731109160)
- [ ] Produce a demo article page for Paul and Hannah to show during the SciScore working group call (25/11)
  - [x] ~feature flag~ a hardcoded article to include sciscore feed item - http://localhost:8080/articles/10.1101/2020.10.31.362848
- [x] Style existing html
  - [x] table
    - [x] horizontal spacing
    - [x] vertical spacing
    - [x] add a top/bottom border to the table
  - [x] ~remove style attributes~ (done by sanitizer)
  - ~style `<hr>` elements to hide them~
- [ ] Use a hard-coded editorial community on the page, linking to their site instead
  - [x] Add community 
  - [x] ~Add EditorialCommunituJoinedEvent~
  - [ ] Add EditorialCommunityReviewedArticleEvent
- [x] Make visible only on staging

**Comment by BlueReZZ** [comment]
From my brief experiment (swapping out one of the annotation IDs with one in an existing community's list) the output seems reasonable with a couple of issues that might be addressed by planned work on Markdown rendering:
- The first table renders as muliple `<td>` instead of multiple `<tr>` as it does on Hypothesis, which is the intention
- The tables need styling (borders, width considerations etc)
- Use of bold and italics is a bit inconsistent but that might look better once the tables are styled

![image](https://user-images.githubusercontent.com/578113/99371358-b6be0f00-28b6-11eb-875c-fe258532aee6.png)

**Comment by thewilkybarkid** [comment]
- Contains broken HTML: `<tr">` and extra closing `</p>`
- Contains inline table styles
