### ISSUE TITLE
Cookie consent slightly broken

### ISSUE THREAD

**Issue by erkannt** [sciety/sciety#316]
- have to scroll to reach button on FF and Brave on real Android devices (Giorgio can repro, David can't)
- no black background on old mobile Safari

## ToDO

- [ ] timeboxed investigation

**Comment by giorgiosironi** [comment]
On real Android device, multiple browsers:
![2020-11-10 10 18 42](https://user-images.githubusercontent.com/160299/98661343-3dff0600-233e-11eb-975b-4f5863407478.png =400x)
The page can be dragged around to get to the `Got it!` button.
