### ISSUE TITLE
Markdown is processed incorrectly

### ISSUE THREAD

**Issue by thewilkybarkid** [sciety/sciety#317]
The current processing of Markdown can result in broken HTML:

```markdown
***Summary:** This study tackles a difficult problem of understanding the basis for hippocampal theta rhythms through reduction of a highly detailed model, seeking to validate a reduced model that would be more amenable to analysis. The reviewers appreciated the attention to this challenging problem and the substantial work that went into it, but had several fundamental concerns about the methodology, interpretation, and reporting.*
```

results in

```html
<p><strong><em>Summary:</strong> This study tackles a difficult problem of understanding the basis for hippocampal theta rhythms through reduction of a highly detailed model, seeking to validate a reduced model that would be more amenable to analysis. The reviewers appreciated the attention to this challenging problem and the substantial work that went into it, but had several fundamental concerns about the methodology, interpretation, and reporting.</em></p>
```

rather than the expected

```html
<p><em><strong>Summary:</strong> This study tackles a difficult problem of understanding the basis for hippocampal theta rhythms through reduction of a highly detailed model, seeking to validate a reduced model that would be more amenable to analysis. The reviewers appreciated the attention to this challenging problem and the substantial work that went into it, but had several fundamental concerns about the methodology, interpretation, and reporting.</em></p>
```

## Current workflow
- eLife writes Hypothesis comment in markdown
- we fetch markdown using Hypothesis API
- we use [`showdown`](https://github.com/showdownjs/showdown) to convert markdown to HTML (showdown looks like it might be unmaintained)

## Options
- we find a maintained library that performs correct conversion of markdown to HTML
- ask eLife to change their coding to side step the bug (specifying block quotes would improve HTML semantics, too). That this won't work for other communities where we don't have the same influence.
- we run a tidy over the converted HTML to guard against external content breaking the site
- strip some HTML elements 
- ~replace `***` with `> **`~ not always a block quote, so can't do this safely
- find out from Hypothesis which Markdown processor they're using (& see if we can use the same):
  - to render in page
  - to preview in their editor
- do Hypothesis provide HTML version of the markdown content that we could use directly?

## Proposal
- [x] we will then need to intentionally style:
  - [x] `<blockquote>`
    - [x] hardcode the Markdown of `10.1101/2020.07.28.225557` first review content
    - [x] style it
    - [x] eLife uses blockquotes for at least this author response
    - [x] remove hardcoding
    - [x] ~sample: Andy may provide an author response by editing the currently broken article http://localhost:8080/articles/10.1101/2020.07.28.225557~
    - [x] ~sample: the Review Commons https://www.biorxiv.org/content/10.1101/2020.07.08.193938v1# which is automatically imported from EJP~
  - [x] ~move on to headings?~
  - [x] contents of `<blockquote>`
- [x] ask eLife to mark up block quotes as block quotes in markdown 
- [x] replace `showdown`
  - [x] ~try Remarkable 1.7; doesn't work due to not matching types~
  - [x] ~try Remarkable 2.0; doesn't work due to missing types~
  - [x] ~try ignoring missing types?~
  - [x] try adding definition locally?
  - [x] ~try other libraries?~
  - [x] ~contribute types upstream; takes a while, rabbit hole~
  - [x] replace in `editorial-community-page`
  - [x] replace in `about-page`
  - ~update unit tests and implement todo tests~
- [x] try running tidy over the output - gains fix in short term & provides a fall back for the future
  - [x] ~[DomPurify](https://github.com/cure53/DOMPurify)~
    * actively maintained
    * definitely fixes our eLife review testcase (demo here: https://cure53.de/purify)
    * aimed at in-browser use, requires `JSDOM` if run on backend
    * provides a `.removed` which might be useful for reporting to user
    * possibly quite opinionated
  - [x] [sanitize-html](https://github.com/apostrophecms/sanitize-html)
    * actively maintained (bugs also fixed quickly)
    * whitelist based approach
    * also allows for replacing of tags, which might be useful for tidying up incoming review e.g. headers
    * a few open bugs
    - [x] ~sanitize article titles? [Sample with italics](http://localhost:8080/articles/10.1101/2020.11.09.375865)~
    - [x] sanitize article abstracts? [Sample sample with italics](http://localhost:8080/articles/10.1101/2020.11.09.375865) [Sample with italics, section, heading and list](http://localhost:8080/articles/10.1101/2020.08.07.241547)
    - [x] ~sanitize editorial community descriptions~
  - [x] ~[insane](https://github.com/bevacqua/insane)~
    * not actively maintained for several years
- ~tests for the selected Markdown library run within `make test` even if they are integration tests for a third party; how to move them out of `make test`?~ Not doing as unclear about the value
- [x] http://localhost:8080/articles/10.1101/2020.07.20.211466 has `<ol>` and `<p>` that have no margin to separate them when the latter follows the former
- [x] pull `article-feed` into its own SASS partial
  - [x] media queries
  - [x] remove interpolation 
  - [x] remove custom properties
  - [x] validate ordering of rules
  - [x] increase padding on feed item title to avoid clashes
- [x] refactor
  - [x] convert all components to return HtmlFragment rather than string
    - [x] `article-page`
    - [x] `article-search-page`
    - [x] `editorial-community-page`
    - [x] `home-page`
    - [x] `shared-components`
    - [x] `user-page`

**Comment by giorgiosironi** [comment]
Investigated https://github.com/gagern/node-libtidy but it's a rabbit hole for C++ compilation.

**Comment by erkannt** [comment]
## Linkify and remarkable

- according to [remarkable changelog](https://github.com/jonschlinkert/remarkable/blob/master/CHANGELOG.md#200--2019-08-07) the  2.0 release was mostly concerned with compilation and bundle sizes
- looking at [this diff](https://github.com/jonschlinkert/remarkable/commit/d88735387a61c264fe82d12f9008367b793f17f9) we can probably get linkify running in 1.7 by simply enabling it in the constructor

## Nested em and strong in marked

[Comment on issue](https://github.com/markedjs/marked/issues/1036#issuecomment-361694578) mentions how old-school markdown renderers like Marked are susceptible to this issue due to their heritage being `markdown.pl` while Commonmark ones don't have this issue.

**Comment by thewilkybarkid** [comment]
Looked into the Remarkable 2.0 problems, and it's definitely that the types are outdated. There's been a closed (and broken) PR (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/41111), and there is another one that is open, but is inactive and also broken (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/48846).

**Comment by thewilkybarkid** [comment]
About Remarkable and Markdown-it: https://github.com/jonschlinkert/remarkable/issues/363

**Comment by will-byrne** [comment]
Markdown Library Choice 
Markdown-it:
  Rejected because of lack of gfm support and differences of opinion of maintainers or Remarkable.
Marked
  Did not pass tests for current use case.
Showdown:
  Rejected because of failing to parse `***content** more content*` and gfm numbered list styles `1)`.
