### ISSUE TITLE
Redirect users to Sciety homepage after successfully resetting password etc on Auth0.

### ISSUE THREAD

**Issue by LinaKind** [sciety/sciety#3182]

**Comment by davidcmoulton** [comment]
Successfully introducing the redirect causes a "Back to Sciety" button to display on said Success page. The button links to the URI provided in the `initiate_login_uri` client property in the `tenant.yml` file, but the button text appears to be managed by the [Management API](https://auth0.com/docs/customize/login-pages/universal-login/customize-text-elements#configure-prompts-and-screens). It's not completely clear whether this is something we want to do in this file. Leaving further investigation as out of scope.
