### ISSUE TITLE
Fix alert dashboard name and scope to reflect its intention

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#319]
- [x] ~http://localhost:8080/articles/10.1101/2020.07.28.225557v1 alerts us due to the 404 error on the request to Crossref~
- [x] ~while trying out http://localhost:8080/articles/10.1101/2020.07.28.225557 a 504 from Crossref is surfaced as a 404 of the article page, which is likely incorrect~
- [ ] the alert in `#sciety-general` covers only `prod` but the [dashboard](https://console.aws.amazon.com/cloudwatch/home?region=us-east-1#dashboards:name=PRCMetrics) shows `staging` errors too
  - [ ] also called `PRCMetrics`

**Comment by thewilkybarkid** [comment]
Thought: can we separate out recoverable errors (e.g. the component's hidden rather than failing the page entirely)?
