### ISSUE TITLE
To avoid /articles/:doi/meta surfacing 404s, redirect to article pages

### ISSUE THREAD

**Issue by davidcmoulton** [sciety/sciety#3218]

**Comment by giorgiosironi** [comment]
We verified [404s were turned into 307s](https://sciety.grafana.net/explore?schemaVersion=1&panes=%7B%22i51%22%3A%7B%22datasource%22%3A%22grafanacloud-logs%22%2C%22queries%22%3A%5B%7B%22datasource%22%3A%7B%22type%22%3A%22loki%22%2C%22uid%22%3A%22grafanacloud-logs%22%7D%2C%22editorMode%22%3A%22code%22%2C%22expr%22%3A%22%7Bapp_kubernetes_io_name%3D%5C%22sciety%5C%22%2Capp_kubernetes_io_instance%3D%5C%22sciety--prod%5C%22%7D%5Cn%7C+json+%7C+__error__%3D%5C%22%5C%22%5Cn%7C+message%3D%60Sent+HTTP+response%60%5Cn%7C+payload_url%3D%7E%5C%22.*meta.*%5C%22%22%2C%22hide%22%3Afalse%2C%22queryType%22%3A%22range%22%2C%22refId%22%3A%22B%22%7D%5D%2C%22range%22%3A%7B%22from%22%3A%22now-7d%22%2C%22to%22%3A%22now%22%7D%7D%7D&orgId=1).
