### ISSUE TITLE
Spike: is it possible to reconstitute the current set of evaluations by ingesting the current real world

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#3234]

**Comment by giorgiosironi** [comment]
We ran this for all 7 PCI groups:
```
make ingest-evaluations INGEST_ONLY=pci INGEST_DAYS=6000 INGEST_DEBUG=true
```
resulted in ~327 evaluations being correctly recorded.

**Comment by giorgiosironi** [comment]
To look into a local database:
```
$ make dev-sql
docker compose --file docker-compose.yml --file docker-compose.dev.yml exec -e PGUSER=user -e PGPASSWORD=secret -e PGDATABASE=sciety db psql
psql (12.3)
Type "help" for help.

sciety=# SELECT COUNT(*) FROM events;
 count 
-------
   327
sciety=# SELECT COUNT(*) FROM events WHERE payload->>'groupId'='32025f28-0506-480e-84a0-b47ef1e92ec5';

 count 
-------
   114
(1 row)
```

**Comment by giorgiosironi** [comment]
To count unique evaluations for a group on a copy of the production database:
```
grep -r 32025f28-0506-480e-84a0-b47ef1e92ec5 data/exploratory-test-from-prod.csv | grep -o '""evaluationLocator"": ""doi:.*' | so
rt | uniq | wc -l
```

**Comment by davidcmoulton** [comment]
The Arcadia group has 2642 evaluations specified on their group card in prod. Local, fresh ingestion yielded 2083.

**Comment by giorgiosironi** [comment]
The preLights group has 1175 evaluations specified on their group card in prod. Local, fresh ingestion yielded 1542.
We had to edit `hours=120000` in the ingestion code to look further into the past than the hardcoded 120 hours.

**Comment by giorgiosironi** [comment]
The prereview group has 415 evaluations specified on their group card in prod. Local, fresh ingestion yielded 405.

**Comment by giorgiosironi** [comment]
It is known NCRC does not have an ingestion set up currently, as a dormant group; we would need to bring that back.

**Comment by giorgiosironi** [comment]
To compare, the current Hypothesis group we ingest from for eLife:
```
$ curl -s "https://api.hypothes.is/api/search?group=q5X6RWJ6&limit=200&sort=created&order=asc" | jq .total
26477
```
which is about ~500 less than the group card in prod.

The number of unique evaluation locators recorded in prod is:
```
$ grep -r b560187e-f2fb-4ff9-a861-a204f3fc0fb0 data/exploratory-test-from-prod.csv | grep -o '""evaluationLocator"": ""hypothesis:.*' | wc -l
28865
```
which suggests we erased/removed almost ~2000 of them over time?

**Comment by giorgiosironi** [comment]
More on eLife suggests the Hypothes.is group is the source of truth and will cover our use case:

> https://hypothes.is/users/Public_Reviews is the user and https://hypothes.is/groups/q5X6RWJ6/elife is the group. Using the group rather than the user makes sense. We post reviews/responses using Kotahi, which ensures they end up on hypothes.is in the group specified (as well as bioRxiv, medRxiv, EPP, and hopefully Sciety!) Paul, let us know if any of that is mistaken!
  [< 1 minute ago](https://elifesciences.slack.com/archives/C011EQLKP51/p1715332612269079?thread_ts=1715331251.208209&cid=C011EQLKP51)

> Thanks, that fits our understanding, and it [goes back to 2019](https://api.hypothes.is/api/search?group=q5X6RWJ6&limit=10&sort=created&order=asc) so it doesn't miss any historical content.

**Comment by giorgiosironi** [comment]
The Rapid Reviews Infectious Diseases group has 995 evaluations specified on their group card in prod. Local, fresh ingestion yielded only 114 even after unhardcoding `daysAgo(1)`. Suggests some bug in pagination or filtering as this ingestion has to filter out the other `peer-review` items from MIT Press on the same DOI prefix.
