### ISSUE TITLE
HTML in article titles is being stripped (italics, subscript, superscripts)

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#324]
## New Issue?

- [x] italics in title currently not displayed
  - [x] homepage feed
  - [x] ~search results~  Current API call returns plain text (no inline formatting, `<sup>` etc.)
  - [x] EC feed
  - [x] article page
- ~type for e.g. StringWithNoHtmlTags?~
- ~handle mathml~
- [x] turn `title` element into valid html
  - [x] filter out non-html tags
  - [x] tests
  - [x] `SanitiseHtmlFragment`
  - [x] ~Make title a `Maybe` type (`titles` can be 0-20)~
  - [ ] ~Look at inline whitespace~ ask Crossref
- [x] Consider refactor of `fetch-crossref-article` to break it into smaller pieces.
  - [x] Add TODOS for refactoring and error scenarios clarification
  - [x] ~separate from-XML transformation from errors/logging~
  - [x] ~`Result.err` should return 2 kinds of errors, but their names shouldn't be HTTP-related?~
  - [x] ~removing fallbacks for properties?~
  - [x] ~introducing `Maybe` for properties?~

Sample: https://staging.sciety.org/articles/10.1101/2020.01.31.929299

**Comment by davidcmoulton** [comment]
EuropePMC return plain text titles, so titles on the search results page doesn't have superscripts, italics etc.

**Comment by davidcmoulton** [comment]
Crossref returns XML with line breaks before and after inline. We cannot know whether the whitespace this introduces is significant or not, so there will always be a space before and after each inline element, which may or may not be intended.

Examples:
``` bash
curl -H "Accept: application/vnd.crossref.unixref+xml" https://api.crossref.org/works/10.7554/eLife.60513/transform
```

``` bash
curl -H "Accept: application/vnd.crossref.unixref+xml" https://api.crossref.org/works/10.7554/eLife.59502/transform
```

``` bash
curl -H "Accept: application/vnd.crossref.unixref+xml" https://api.crossref.org/works/10.1101/2020.11.02.365478/transform
```

**Comment by thewilkybarkid** [comment]
Whitespace handling in the CrossRef API is discussed in https://github.com/CrossRef/rest-api-doc/issues/112, but I'm not sure what to make of it. It suggests that it's up to the publisher to provide correct whitespace, but since we see the same line breaks in bioRxiv and eLife content that would be quite a coincidence. Can't also see any documentation about how to handle whitespace in `<title>` and `<abstract>` elements etc.

**Comment by thewilkybarkid** [comment]
The JSON format has correct whitespace in the abstract, but doesn't have any inline markup in the title (mentioned in https://github.com/sciety/sciety/issues/310#issuecomment-730278074):

```sh
curl https://api.crossref.org/works/10.1101/2020.11.02.365478 | jq .
```

**Comment by giorgiosironi** [comment]
Only open point now for @BlueReZZ to communicate with Crossref about whitespace issues.

**Comment by BlueReZZ** [comment]
I've replied to the CrossRef ticket, will close this but add any responses that are relevant for completeness.
