### ISSUE TITLE
Introduce visual testing and refactor page layout

### ISSUE THREAD

**Issue by erkannt** [sciety/sciety#326]
- [x] visual testing
  - [x] investigate backstop and percy
  - [x] install backstopjs
  - [x] make target
    - [x] ~using local browser/backstop~
    - [x] ~in docker?~
    - [x] in backstopjs container?
      - [x] `npm install` should be a dependency
      - [x] avoid downloading redundant Chromium
  - [x] specify scenarios for staging vs. prod
    - [x] homepage (only one with cookie banner)
    - [x] terms page
    - [x] hide cookie banner as a default
    - [x] homepage
    - [x] one article page that includes reviews
      - [x] avoid noise of up-down-feature diff
    - [x] one article page that includes expanded reviews 
    - [x] one editorial community page
      - ~don't visual test this page at all~
      - ~ignore and trust the human~
      - ~pass in a parameter to the page that removes things~
      - ~hardcode a dummy page~
      - [x] test: remove stuff from the page
      - ~test: select a single DOM element on the page~
      - ~compare staging to a previous revision of staging that is stored in the bitmaps in the Git repo~
      - ~compare localhost to a previous revision of localhost (or somewhere else) with a fixed state~
      - ~compare staging to a previous revision of staging that is deployed in some kind of additional environment~
      - ~compare fixed-staging to a previous revision of fixed-staging that is deployed in some kind of additional environment~
    - [x] about page
    - [x] privacy page
    - [x] article-search page
    - [x] user page
    - [x] include cookie to avoid cookie banner animation causing false positives 
  - [x] specify viewports
  - [x] de-noise the console output
  - [x] ~avoid false negative of 404s~ No access to response object
  - [x] ~check inconsistency between reaching a state via clicks vs. hardcoding a cookie~ comfortable with two approaches, nothing to do
- [x] refactor
  - [x] ~make layout coupling explicit in code~ Giving pages flexibility to use the appropriate `display` and to return any number of elements.
  - [x] use `sciety-grid--simple` on:
    - [x] terms
    - [x] privacy
    - [x] ~user~ using its own grid to keep 7 columns for `.user-page-contents`
    - [x] search results
    - [x] error pages in `article-page`
  - [x] consider error pages
    - [x] can we remove duplication of `sciety-grid--*` in error pages markup inside `render-page`s?
    - [x] remove unused `content` field in `RenderPageError`
    - [x] extract `page-handler` functions in their own module?
    - [x] is the name `description` the best?
    - [x] ~revamp error messages~ (out of scope)
  - [x] address profile page vertical space
  - [x] do all pages have a vertical space issues that could be solved by `grid-auto-rows`?
  - [x] ~remove semantic-ui completely?~ (out of scope)

note: apply-standard-page-layout is only responsible for vertical positioning of the main content and the styles of the header and footer.

**Comment by giorgiosironi** [comment]
Current time on my laptop with 2 viewports and this list of scenarios:
```
real    0m46.564s
```
