### ISSUE TITLE
Update text (and <title>) on the homepage to help visitors understand Sciety

### ISSUE THREAD

**Issue by LinaKind** [sciety/sciety#3268]

**Comment by LinaKind** [comment]
https://groups.google.com/a/elifesciences.org/g/team/c/4UPQt_BiF0s

**Comment by LinaKind** [comment]
Link to the experiment on vistaly:
https://app.vistaly.com/w/NM9JzslmvPaQt08_RKTKA/rm?drawer-id=YyQ0MoeoTfY6e3iv77wiQ&drawer-tab=overview&gc=one&tn-id=GRXbmJcu673YEtyliPa5c&view=experiments

**Comment by themarkness** [comment]
Link to the survey in Hotjar https://insights.hotjar.com/sites/443270/surveys/responses/1024072?sort_by=-index
