### ISSUE TITLE
Searching for Sciety.org in Google gives 'no information available' message

### ISSUE THREAD

**Issue by hdrury1** [sciety/sciety#338]
Update `robots.txt`

- [x] open up for all
  - [x] make sure only `prod`
- [x] stop __search__ being indexed
- [x] site-verification
  - [x] @BlueReZZ  to grant Google search console access to the team
- [x] capture DNS TXT record into infrastructure as code
  - [x] add `aws_route53_record`
  - [x] remove hardcoding of domain
  - [x] remove hardcoding of hosted zone
  - [x] document where the magic value came from
  - [x] remove `PeterHooper` and other obsolete users
- [x] page-title ('titleofpage | Sciety' except for homepage)
  - [x] articles ('the-whole-title | Sciety')(go with consistency, see what it looks like, maybe experiments later)
  - [x] ECs ('name-of-community | Sciety')
  - [x] homepage ('Sciety: where research is evaluated and curated by the communities you trust. ') 
  - [x] users ('twitter-display-name | Sciety')
  - [x] search('Search | Sciety')
  - [x] about('About | Sciety')
  - [x] terms and privacy ('the-h1-content | Sciety')
  - [x] consider error pages
  - [x] make the title mandatory
  - [x] escape/remove inline HTML
  - [x] consider deduplicating the `Page` type
  - ~check TODOs for `unsafelyUnwrap`~ postponing for `fp-ts` exploration
  - ~reduce number of Twitter API calls (increased in https://github.com/sciety/sciety/commit/64cc0c3e913c100dee8aff598eb4d939a84ca0af)~ #327
  - ~remove duplication of the stripping tags in the article-page title usage~
  - [x] use pipe in page-handler
  - [x] remove duplication of `| Sciety` suffix
- ~metadata~
- ~retrigger google spider~
- ~build sitemap~

**Comment by giorgiosironi** [comment]
https://www.google.com/webmasters/tools/robots-testing-tool may help (requires a verified property)

**Comment by thewilkybarkid** [comment]
We already have a `TXT` `google-site-verification` entry, may have been setup for GMail. Think users will need to be granted access /cc @BlueReZZ

**Comment by BlueReZZ** [comment]
> We already have a `TXT` `google-site-verification` entry, may have been setup for GMail. Think users will need to be granted access (we can overwrite it, but unsure if that'll have side effects) /cc @BlueReZZ

It looks like the verification code is related to me and the domain, as the same one worked for verifying the domain in the "webmaster central" and G Suite verification paths.

Therefore I have legitimate access to it in the search console. I also found a way to add users so added @thewilkybarkid and we can see what happens tomorrow.

**Comment by BlueReZZ** [comment]
Tried a live check using the google bot on the homepage but it's not seeing the updated `robots.txt` There is an issue with the requesting of reindexing currently so maybe the page isn't working as expected. I learned more here: https://support.google.com/webmasters/answer/9012289#live_indexable
