### ISSUE TITLE
ALERT on 2020-12-01: community page failing due to the high number of Twitter users to be shown

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#340]
Ranging from 17:00 to 23:00 UTC.

## Problem 1

Impact: one person loaded an editorial community page, with many Twitter followers. The first time they refreshed due to slowness. The second time it failed with a 404, an incorrect error message.

- [x] 4 `Request to Twitter API for user details failed`
  - [x] fix the error message not to be a 404
    - [x] stop catching any error
    - [x] limit scope of follower list failure somehow
  - [x] show fallback if user details unavailable
    - [x] add tests
    - [x] remove knowledge of `render-follower` from `render-followers`
      - [x] remove knowledge of the `follow-details` type from `render-followers`
      - [x] look at the adapter using a `catch`
  - ~UI: reduce the size of the community followers list permanently?~
  - ~UI: reduce the size of the community followers list until a new design is proposed?~
  - [x] Content Grouping should consider `/users` pages on Google Analytics
  - ~find out if these link to the user pages are used?~ 
  - [x] Log timing for requests to Twitter
  - ~something about caching/bulk requests?~
  - [x] Look into Axios, does it request using HTTP 1.x and / or 2?
  - [x] make logger serialise errors properly
  - [x] show an error page instead of internal server error on `/users/userid`
    - [x] use `HtmlFragment` in the types of `user-page/render-page`

## Problem 2

Impact: possibly 3 different people had login problems when coming back from Twitter. See #341.

## Problem 3

Impact: an article reviewed by PREreview reported incorrect publishing information (`Published on bioRxiv`, no versions available). An article which URL was probably hand-written had the same problem. See #342.

## Investigate regardless of the impact

- [x] UUID of different requests look almost the same: `c05a1050-3409-11eb-ab1e-0b1626cdc678`,` c2b872b0-3409-11eb-ab1e-0b1626cdc678`, `6eb06d00-340c-11eb-ab1e-0b1626cdc678` (`cls-rtracer` library uses V1)
- [x] credentials being dumped in the log for Twitter request errors: redact all `Authorization` properties of any object in the logger
- [x] check for Crossref and database and similar: redact all `Crossref-Plus-API-Token` properties of any object in the logger

**Comment by giorgiosironi** [comment]
`4 Request to Twitter API for user details failed` appear to be 503 errors all happened within the same second.

2 came from a request to `/editorial-communities/10360d97-bf52-4aef-b2fa-2f60d319edd7`, the PREreview community page, which has many Twitter followers displayed. Our page response code was 404 as any error gets mapped to an "editorial community not found" message.

**Comment by giorgiosironi** [comment]
3 `Unhandled Error` cases are `Failed to find request token in session`, similar to #330. They happened at different times of the day.

Sample full stack trace:
```
Error: Failed to find request token in session
at SessionStore.get (/app/node_modules/passport-oauth1/lib/requesttoken/session.js:13:44)
at Strategy.OAuthStrategy.authenticate (/app/node_modules/passport-oauth1/lib/strategy.js:214:33)
at Strategy.authenticate (/app/node_modules/passport-twitter/lib/strategy.js:87:40)
at attempt (/app/node_modules/passport/lib/middleware/authenticate.js:366:16)
at authenticate (/app/node_modules/passport/lib/middleware/authenticate.js:367:7)
at /app/node_modules/koa-passport/lib/framework/koa.js:194:7
at new Promise (<anonymous>)
at /app/node_modules/koa-passport/lib/framework/koa.js:193:12
at /app/node_modules/koa-passport/lib/framework/koa.js:143:7
at new Promise (<anonymous>)
```

Investigating the most recent case, we found `/twitter/callback?oauth_token=MgMAIQAAAAABHCzgAAABdiCAHHE&oauth_verifier=A8Ivz7OQevpSFdVT9yg8eTuEn7lSzPGp` with `requestId` `c5ed8a60-3427-11eb-ab1e-0b1626cdc678`.

**Comment by giorgiosironi** [comment]
2 `No article versions found` happened at different times of the day, `requestId`:
- `6eb06d00-340c-11eb-ab1e-0b1626cdc678`
- `b66fd360-33f8-11eb-ab1e-0b1626cdc678`

They happened on article pages, during the request to the bioRxiv API to get the list of versions. They are both medRxiv articles.

DOIs involved:
- `10.1101/2020.02.22.20025460`
- `10.1101/2020.05.18.20099960`

**Comment by will-byrne** [comment]
[Url for changing the content grouping for pages:](
https://analytics.google.com/analytics/web/?authuser=1#/a167311475w233457116p219087825/admin/content-groupings/m-content-contentGroupingTable.rowShow=10&m-content-contentGroupingTable.rowStart=0&m-content-contentGroupingTable.sortColumnId=dateModified&m-content-contentGroupingTable.sortDescending=true)
