### ISSUE TITLE
Tackle deprecated sass behaviour

### ISSUE THREAD

**Issue by LinaKind** [sciety/sciety#3404]

**Comment by LinaKind** [comment]
Deprecation Warning: Sass's behavior for declarations that appear after nested
rules will be changing to match the behavior specified by CSS in an upcoming
version. To keep the existing behavior, move the declaration above the nested
rule. To opt into the new behavior, wrap the declaration in `& {}`

https://sass-lang.com/documentation/breaking-changes/mixed-decls/

**Comment by erkannt** [comment]
Postponed as it requires further investigation to make a decision and nothing currently broken.
