### ISSUE TITLE
ALERT on 2020-12-01: problems coming back from Twitter

### ISSUE THREAD

**Issue by kevinrutherford** [sciety/sciety#341]
Impact: possibly 3 different people had login problems when coming back from Twitter.

- [x] 3 `Unhandled Error` (user experience: internal server errror)
  - [x] reproduce (use twitter callback url from staging on localhost triggers the same type of error)
  - [x] user friendly error page for `internal server error`
    - [x] add Middleware preceding `passport`
    - [x] add error page for errors in `/static`
    - [x] extract Middleware for `/static` too in the same file?
    - ~refactor into fp-ts~
    - [x] extract new Middlewares in other files?
  - ~answer questions around user logins~ (see #343)
  - ~determine what caused the errors to occur in the wild~
    - ~check if the same callback URL has been called multiple times (back button scenario?) only by time correlation and/or GET parameters on `/twitter/callback`~
- refactoring
  - [x] convert the Maybe in `applyStandardPageLayout` to an `Option`?

**Comment by giorgiosironi** [comment]
Reopened after further alerts of what we believe are `/twitter/callback` requests triggered by the back button in the browser.
