### ISSUE TITLE
Run ingestion for the all available ACMI evaluations on localhost

### ISSUE THREAD

**Issue by davidcmoulton** [sciety/sciety#3425]

**Comment by LinaKind** [comment]
Pagination with offsets:
`&rows=1000&offset=1000` to get the second thousand results.
Documentation: https://api.crossref.org/swagger-ui/index.html#/Works/get_works 

Rights total: 1000 without the offset
Rights total: 651 with the offset
Running the ingestion for both sets matches the total number of expected evaluations:
https://api.crossref.org/works?filter=prefix:10.1099,type:peer-review,relation.type:is-review-of&sort=published&order=asc&rows=1000
