### ISSUE TITLE
Investigate the risk of recording all evaluations under the 10.1099 doi prefix

### ISSUE THREAD

**Issue by LinaKind** [sciety/sciety#3440]

**Comment by LinaKind** [comment]
As of today we record 1661 evaluations:
https://api.crossref.org/works?filter=prefix:10.1099,type:peer-review,relation.type:is-review-of

The relation filter is for robustness, but does not exclude anything:
https://api.crossref.org/works?filter=prefix:10.1099,type:peer-review

The publisher has 72718 items on crossref, initial sample shows `journal-article`:
https://api.crossref.org/works?filter=prefix:10.1099

**Comment by giorgiosironi** [comment]
Running the below commands confirms that all ingested evaluations have `Microbiology Society` as publisher:

```
$ curl -v "https://api.crossref.org/works?filter=prefix:10.1099,type:peer-review,relation.type:is-review-of&sort=published&order=asc&rows=1000" > acmi-page-1.txt
$ curl -v "https://api.crossref.org/works?filter=prefix:10.1099,type:peer-review,relation.type:is-review-of&sort=published&order=asc&rows=1000&offset=1000" > acmi-page-2.txt
$ cat acmi-page-* | jq . | grep publisher | sort | uniq -c
   1661         "publisher": "Microbiology Society",
```

**Comment by LinaKind** [comment]
Filtering by doi partial suffix shows all items have strong relationship with acmi.

```
$ cat acmi-page-* | jq . | grep DOI | grep 10.1099/acmi | wc -l
1661
```

**Comment by giorgiosironi** [comment]
Querying by `publisher-name` `Microbiology Society` produced 72718 items, which is the same as filtering by DOI prefix:
https://api.crossref.org/works?filter=prefix:10.1099&query.publisher-name=Microbiology%20Society

**Comment by LinaKind** [comment]
Facets can give us the total number of items matching each `type`:

```
curl "https://api.crossref.org/works?filter=prefix:10.1099&facet=type-name:*" | jq .message.facets

{
  "type-name": {
    "value-count": 5,
    "values": {
      "Journal Article": 69192,
      "Peer Review": 1661,
      "Report": 1004,
      "Posted Content": 856,
      "Journal": 5
    }
  }
}
```

**Comment by giorgiosironi** [comment]
This investigation shows that there are 1004 `report` type items available on Crossref under the `10.1099` prefix. We believe they correspond to machine-generated reports rather than peer review.
```
$ curl -v "https://api.crossref.org/works?filter=prefix:10.1099,type:report&sort=published&order=asc&rows=1000" > acmi-reports-page-1.txt
$ curl -v "https://api.crossref.org/works?filter=prefix:10.1099,type:report&sort=published&order=asc&rows=1000&offset=1000" > acmi-reports-page-2.txt
$ cat acmi-reports-page-* | jq . | grep DOI | head
        "DOI": "10.1099/acmi.0.000459.v1.2",
        "DOI": "10.1099/acmi.0.000459.v1.1",
        "DOI": "10.1099/acmi.0.000460.v1.1",
        "DOI": "10.1099/acmi.0.000460.v1.2",
        "DOI": "10.1099/acmi.0.000463.v1.1",
        "DOI": "10.1099/acmi.0.000463.v1.2",
        "DOI": "10.1099/acmi.0.000462.v1.1",
        "DOI": "10.1099/acmi.0.000462.v1.2",
        "DOI": "10.1099/acmi.0.000464.v1.2",
        "DOI": "10.1099/acmi.0.000464.v1.1",
```

**Comment by LinaKind** [comment]
All `posted-content` items (typically preprints) are part of acmi. 
```
$ curl -v "https://api.crossref.org/works?filter=prefix:10.1099,type:posted-content&sort=published&order=asc&rows=1000" > acmi-posted-content-page-1.txt

$ cat acmi-posted-content-page-* | jq '.message.items[].DOI' | grep acmi | wc -l
856
```

**Comment by giorgiosironi** [comment]
According to Crossref `journal` records, this publisher has 5 journals.
```
curl "https://api.crossref.org/works?filter=prefix:10.1099,type:jou
rnal" | jq '.message.items[].title'
[
  "Journal of General Virology"
]
[
  "Microbiology"
]
[
  "International Journal of Systematics and Evolutionary Microbiology"
]
[
  "Journal of Medical Microbiology"
]
[
  "JMM Case Reports"
]
```
However, 2 more publications are listed on the website:
- `Access Microbiology, an open research platform` (not to be confused with `Microbiology`)
- `Microbial Genomics`

**Comment by giorgiosironi** [comment]
We are testing hypothetical scenarios against the current product, to find out:
- whether they could trigger undesirable consequences
- if we can identify the relevant places to intervene in the code if that happens.

We have investigated this hypothetical scenario:
> the Microbiology Society adds another journal with public peer reviews which appear on Crossref, and they don't want it on Sciety. What do we do?
We inspected our ACMI ingestion and it will start to record these peer reviews, assuming they are under the same DOI prefix. 

Therefore, we will need to:
- introduce an ingestion filter that targets DOIs of the form `10.1099/acmi.*`
- erase the incorrectly recorded evaluations

**Comment by davidcmoulton** [comment]
Another hypothetical scenario:
> Mark asks us to include machine-generated reports as well as peer reviews. What do we do?

Therefore, we will need to:
- change or add [Crossref URL](https://api.crossref.org/works?filter=prefix:10.1099,type:report,relation.type:is-related-material&sort=published&order=asc&rows=1000) and codecs in the ingestion
- the DOIs use the same prefix so we will ensure the evaluation fetcher for the digest fails cleanly, and provides only a link to the [original URL](https://doi.org/10.1099/acmi.0.000459.v1.2) in the paper activity page
- we won't be able to guarantee any machine readable digest

**Comment by LinaKind** [comment]
We are testing hypothetical scenarios against the current product, to find out:
- whether they could trigger undesirable consequences
- if we can identify the relevant places to intervene in the code if that happens.

We have investigated this hypothetical scenario:
> the Microbiology Society adds another journal with public peer reviews which appear on Crossref, and they want it on Sciety. What do we do?
We inspected our ACMI ingestion and it will start to record these peer reviews, assuming they are under the same DOI prefix. 

Therefore, we will need to:
- introduce ingestion filters that targets DOIs of the form `10.1099/acmi.*` and whatever we need for the new journal
- erase the incorrectly recorded evaluations

**Comment by davidcmoulton** [comment]
Another hypothetical scenario:
> the society changes their domain name (or path), where they host the XML for machine readable digests

We will need to:
- if the domain / path is changed for all hosted machine readable digests, then we will need to update the hardcoded URL root to the new value
- if the hosting is split between original and new locations, more investigation will be needed
