### ISSUE TITLE
Send a payload to a test COAR inbox

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#3462]
Using evaluations from this sample paper to create a test payload:
https://sciety.org/articles/activity/10.1101/2024.04.03.24305276

**Comment by giorgiosironi** [comment]
Keeping the `object` `type` as `sorg:WebPage` which seems more accurate than [what the documentation suggests](https://notify.coar-repositories.org/specification/patterns/announce-ingest/):
```
A type which should include the value AboutPage from schema.org.
```

**Comment by LinaKind** [comment]
Current response using the script:
```
HTTP/2 422 
< date: Fri, 16 Aug 2024 10:37:09 GMT
< server: Fly/f8a8cc0dd (2024-08-15)
< content-length: 134
< content-type: application/json
< via: 2 fly.io
< fly-request-id: 01J5DC6FJGHTKWJHWN615TS0S6-waw
< 
* Connection #0 to host coar-notify-inbox.fly.dev left intact
{"detail":[{"type":"missing","loc":["body"],"msg":"Field required","input":null,"url":"https://errors.pydantic.dev/2.0.3/v/missing"}]}% 
```

We know the test inbox is not ready to be used reliably.
