### ISSUE TITLE
Article with no title or abstract cached

### ISSUE THREAD

**Issue by kevinrutherford** [sciety/sciety#347]
The article https://sciety.org/articles/10.1101/2020.01.22.915330 was visited on prod; the title / abstract were fetched, but an error occurred while parsing the title / abstract. This does not result in an error, so the broken article was cached until the server next restarted.

- [x] Errors parsing the Crossref response result in the article not being deleted from the cache
- [ ] Showing `Unknown title` with no other explanation is not particularly user-friendly
- [ ] Might be good to have an endpoint that clears the cache without having to do a release
- [ ] Displaying `Unknown title` etc should be a concern of the rendering component, not the fetcher

**Comment by kevinrutherford** [comment]
On the cached article page on prod, the bioRxiv versions were present, but the title, authors and abstract were missing.

![Screenshot from 2020-12-11 12-52-12](https://user-images.githubusercontent.com/23290/101905848-fde6a980-3baf-11eb-837f-23791bb42618.png)

**Comment by giorgiosironi** [comment]
Closing in favor of https://github.com/sciety/sciety/issues/359
