### ISSUE TITLE
Timebox an investigation into the cause(s) of the createUserAccountCodec failures

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#3485]

**Comment by giorgiosironi** [comment]
Exporting last [30 days of logs filtered by `createUserAccountFormCodec failed`](https://sciety.grafana.net/explore?schemaVersion=1&panes=%7B%22ewi%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22sum%20by%20%28message,%20payload_codec,%20payload_error_status%29%20%28count_over_time%28%5Cn%7Bapp_kubernetes_io_name%3D%5C%22sciety%5C%22,app_kubernetes_io_instance%3D%5C%22sciety--prod%5C%22%7D%5Cn%7C%20json%20%7C%20__error__%3D%5C%22%5C%22%5Cn%7C%20level%20%3D%20%5C%22error%5C%22%5Cn%5B7d%5D%29%29%22,%22hide%22:true,%22queryType%22:%22instant%22,%22refId%22:%22A%22%7D,%7B%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22%7Bapp_kubernetes_io_name%3D%5C%22sciety%5C%22,app_kubernetes_io_instance%3D%5C%22sciety--prod%5C%22%7D%5Cn%7C%20json%20%7C%20__error__%3D%5C%22%5C%22%5Cn%7C%20level%20%3D%20%5C%22error%5C%22%20%7C%20message%3D%60createUserAccountFormCodec%20failed%60%22,%22hide%22:false,%22queryType%22:%22range%22,%22refId%22:%22B%22%7D,%7B%22refId%22:%22C%22,%22expr%22:%22%7Bapp_kubernetes_io_name%3D%5C%22sciety%5C%22,app_kubernetes_io_instance%3D%5C%22sciety--prod%5C%22%7D%5Cn%7C%20json%20%7C%20__error__%3D%5C%22%5C%22%5Cn%7C%20payload_requestId%3D%5C%220a1c5b40-afc6-11ee-be14-afeff25334d0%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22,%22hide%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-30d%22,%22to%22:%22now%22%7D%7D%7D&orgId=1).

```
$ cat ~/Downloads/Explore-logs-2024-08-27\ 11_03_06.json | jq -r '.[].line' | jq -r '.payload.error[]' | sort | uniq -c | sort -rn
     17 Expecting UserHandle at handle but instead got: ""
      6 Expecting SanitisedUserInput at fullName but instead got: ""
      3 Expecting UserHandle at handle but instead got: "Nágila Batista Coelho "
      2 Expecting UserHandle at handle but instead got: "reji003."
      2 Expecting UserHandle at handle but instead got: "Moh"
      2 Expecting UserHandle at handle but instead got: "epibio.njala/abu"
      2 Expecting UserHandle at handle but instead got: "anil.org"
      1 Expecting UserHandle at handle but instead got: "yanxi-li"
      1 Expecting UserHandle at handle but instead got: "Tagay25@gmail.com"
      1 Expecting UserHandle at handle but instead got: "Tagay25@1234"
      1 Expecting UserHandle at handle but instead got: "Tagay25@"
      1 Expecting UserHandle at handle but instead got: "sciety.org/nagila/"
      1 Expecting UserHandle at handle but instead got: "Sarah Michelle"
      1 Expecting UserHandle at handle but instead got: "Rejina003@2002"
      1 Expecting UserHandle at handle but instead got: "Reji003@2002"
      1 Expecting UserHandle at handle but instead got: "rakhitha "
      1 Expecting UserHandle at handle but instead got: "nagila Batista Coelho "
      1 Expecting UserHandle at handle but instead got: "nagilabatistacoelho "
      1 Expecting UserHandle at handle but instead got: "nagila Batista "
      1 Expecting UserHandle at handle but instead got: "Nágila "
      1 Expecting UserHandle at handle but instead got: "nagila "
      1 Expecting UserHandle at handle but instead got: "mph.njala.edu.sl"
      1 Expecting UserHandle at handle but instead got: "mansi.30"
      1 Expecting UserHandle at handle but instead got: "epibio.njala.edu.sl"
```
User handles only allow the characters `a-zA-Z0-9_` and a length from 4 to 15 characters. All of these are input validation failures and were values provided by site visitors (or not provided).

Various cases, in order of occurrence:
- empty handle
- empty full name
- spaces in the handle
- `/`, `@`, `.`, `-` in the handle (forbidden characters)
- handle too long

**Comment by LinaKind** [comment]
Possible proposals:

- enhance the sign up experience with JS, providing realtime feedback on what is allowed to key in
- relax characters allowed into the handle
- relax length requirements
- remove trailing/leading spaces
- generate a default handle, allow user not to provide a handle immediately
