### ISSUE TITLE
GA has recorded no goal conversions for Follow or Log in events

### ISSUE THREAD

**Issue by hdrury1** [sciety/sciety#353]
According to conversion tracking in GA, no one (with GA enabled) has clicked Follow or Log In since we implemented the event triggers last week. This seems implausible- are things behaving as they should?

- [x] rename variables, tags & triggers to reflect behaviour in GTM
- [x] use new environment-sensitive snippet in prod
- [x] check if goals are updated by events
- [x] investigate lack of goal conversions leading up to December 17th

**Comment by davidcmoulton** [comment]
Running 
```sql
select * from events where type = 'UserFollowedEditorialCommunity' and date > '2020-12-13';
```
on the prod database on 18th December, when ignoring Sciety team members' activity, showed three users performing "Follow" activity on the 13 and 14th December. These activities aren't showing up in GA.

Either they are using an ad-blocker, or blocking third party cookies, or not consenting to cookies, or there something is broken.

**Comment by erkannt** [comment]
- we see `UserFollowedCommunityEvents` in our DB that don't show up in GA (neither as events, nor as goal conversions)
- there are 6 `Follow` events (two sessions, ergo two goal conversions) in GA
  - we don't see corresponding events in our DB (which might be normal, correct behaviour)

## Options

- dive deeper into logs for the users we have that followed
  - users who don't complete the follow flow (should event in GA, no `UserFollowedCommunityEvent`)?
  - specific browser that doesn't work/autoblocks GA
- do same query for `Breadcrumbs`
  - no events show in GA, are there events in DB
- **wait for more data**
