### ISSUE TITLE
Deploy coar-notify-inbox kustomization to the prod environment

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#3560]

**Comment by LinaKind** [comment]
Available at: https://inbox-sciety-prod.elifesciences.org/

**Comment by giorgiosironi** [comment]
To limit access, the [`nginx.ingress.kubernetes.io/whitelist-source-range` annotation for Ingresses](https://github.com/kubernetes/ingress-nginx/blob/main/docs/user-guide/nginx-configuration/annotations.md#configuration-snippet) might be too strong.

[`nginx.ingress.kubernetes.io/configuration-snippet`](https://github.com/elifesciences/elife-flux-cluster/blob/9533493342cff400fa301465c3ec43783dc86b24/deployments/reviewer/redirects/prod/redirect-ejp.yaml#L5) could give us flexibility such as stopping POST requests only.

**Comment by davidcmoulton** [comment]
Possible solution using the [nginx access module](https://nginx.org/en/docs/http/ngx_http_access_module.html), see also https://serverfault.com/questions/840342/allowing-post-requests-from-a-single-ip-address-only-on-nginx?
