### ISSUE TITLE
404 on 10.1101/2020.12.16.423020

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#357]
- [x] mitigate by removing from events temporarily
- [x] why Biorxiv has this article but Crossref doesn't? Delay of several days for all new Biorxiv articles indexing on Crossref
- [x] where do the links come from? eLife's feed
- [ ] contact Biorxiv to understand the duration of the delay and whether it has always been there
- [ ] mitigate medium term
  - [x] update the scripts to skip this article?
  - [ ] update the scripts to remove any article not on crossref?

**Comment by giorgiosironi** [comment]
Error page not present in Google Analytics.

Link comes from `eLife reviewed an article` on eLife's feed (homepage or [editorial community page](https://staging.sciety.org/editorial-communities/b560187e-f2fb-4ff9-a861-a204f3fc0fb0)) and the title cannot be shown there as it cannot be retrieved from Crossref.

**Comment by giorgiosironi** [comment]
Various papers up to https://www.biorxiv.org/collection/neuroscience?page=7 are not on Crossref, it seems there is a window of at least 5-6 days in which new Biorxiv papers have not been ~pushed~ exported to Crossref. The doi.org redirects for these papers don't work as weel.

**Comment by giorgiosironi** [comment]
As a very small sample of 1 article, we looked at an old article from January and according to:
```
curl -v -H "Accept: application/json" "https://api.crossref.org/works/10.1101/2020.01.31.929299/transform"
```
it seems to had a delay of just 1 day between posting date and Crossref `created` date for its version 1.

**Comment by BlueReZZ** [comment]
I've emailed Ted at bioRxiv to let him know - he was looking into it on 22nd Dec 2020 so may be waiting for a remediation to process if their people have been away over the New Year.

**Comment by BlueReZZ** [comment]
Ted got back to us
> Yes the general issue that we experienced was resolved by late on the 24th - many thanks again for getting in touch. And thanks, too, for pointing out this specific omission. We will address it ASAP.
