### ISSUE TITLE
Timebox investigation into codec failure: crossrefMultipleWorksResponseCodec, crossrefIndividualWorksResponseCodec

### ISSUE THREAD

**Issue by davidcmoulton** [sciety/sciety#3580]

**Comment by davidcmoulton** [comment]
[Grafana view](https://sciety.grafana.net/explore?schemaVersion=1&panes=%7B%22fxi%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22sum%20by%20%28message,%20payload_codec,%20payload_error_status%29%20%28count_over_time%28%5Cn%7Bapp_kubernetes_io_name%3D%5C%22sciety%5C%22,app_kubernetes_io_instance%3D%5C%22sciety--prod%5C%22%7D%5Cn%7C%20json%20%7C%20__error__%3D%5C%22%5C%22%5Cn%7C%20level%20%3D%20%5C%22error%5C%22%5Cn%5B7d%5D%29%29%22,%22hide%22:true,%22queryType%22:%22instant%22,%22refId%22:%22A%22%7D,%7B%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22,%22expr%22:%22%7Bapp_kubernetes_io_name%3D%5C%22sciety%5C%22,app_kubernetes_io_instance%3D%5C%22sciety--prod%5C%22%7D%5Cn%7C%20json%20%7C%20__error__%3D%5C%22%5C%22%5Cn%7C%20level%20%3D%20%5C%22error%5C%22%20%7C%20message%3D%60Codec%20failure%60%22,%22hide%22:false,%22queryType%22:%22range%22,%22refId%22:%22B%22%7D,%7B%22refId%22:%22C%22,%22expr%22:%22%7Bapp_kubernetes_io_name%3D%5C%22sciety%5C%22,app_kubernetes_io_instance%3D%5C%22sciety--prod%5C%22%7D%5Cn%7C%20json%20%7C%20__error__%3D%5C%22%5C%22%5Cn%7C%20payload_requestId%3D%5C%220a1c5b40-afc6-11ee-be14-afeff25334d0%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22,%22hide%22:true%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D%7D&orgId=1) of the latest errors of this kind.

**Comment by davidcmoulton** [comment]
An example of a response failing decoding via the `crossrefIndividualWorksResponseCodec`: https://api.crossref.org/works/10.20944/preprints202405.0088.v1

**Comment by giorgiosironi** [comment]
Found this failure to be related to a relation we don't allow:
```
$ curl -s "https://api.cross
ref.org/works/10.20944/preprints202405.0088.v1" | jq .message.relatio
n
{
  "is-preprint-of": [
    {
      "id-type": "short-doi",
      "id": "10.1111/avj.13360",
      "asserted-by": "subject"
    }
  ]
}
```

**Comment by davidcmoulton** [comment]
Same problem found for this one: https://api.crossref.org/works/10.20944/preprints202401.1982.v1

**Comment by giorgiosironi** [comment]
https://www.doi.org/doi-handbook/HTML/shortdoi.html explains that short DOIs have the form `10/abcde`; the values found here do not conform, and do not redirect to a different DOI when used on doi.org; therefore this is a metadata problem with Crossref's response.

**Comment by giorgiosironi** [comment]
https://github.com/sciety/sciety/blob/cd43dec481387ef702380a00755f25553ff87649/src/third-parties/fetch-publishing-history/fetch-all-paper-expressions-from-crossref/crossref-work.ts#L6 should probably allow values that do not have `id-type`:`doi` to prevent a whole article page failure, but ignore those values (which can be legitimate `short-doi` values).
