### ISSUE TITLE
Investigate correctness of the papers-evaluated-by-group read model to prevent possible bugs

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#3624]

**Comment by giorgiosironi** [comment]
479 preprints [listed on the ACMI website](https://www.microbiologyresearch.org/content/journal/acmi/preprints)

how many evaluations are on Crossref?  
total: 1895  

how many paper expressions are on Crossref?  
total: 967  

how many papers are on Crossref?
total: 478  
`curl 'https://api.crossref.org/works?filter=prefix:10.1099,type:posted-content&rows=1000'  | jq '.message.items[].DOI' | cut -d 'v' -f 1 | sort -u | wc -l  `

how many evaluations have we recorded on staging?  
total: 1895  
`grep -r EvaluationPublicationRecorded data/exploratory-test-from-staging.csv | grep 4d6a8908-22a9-45c8-bd56-3c7140647709 | wc -l`  

how many different "paper DOIs" do these evaluations show as part of their own DOIs?  
total: 424 (see [acmi-unique-doi-fragments-indicating-papers.txt](https://github.com/user-attachments/files/17619552/acmi-unique-doi-fragments-indicating-papers.txt))


discrepancy with 430 items on [staging](https://staging.sciety.org/api/groups/4d6a8908-22a9-45c8-bd56-3c7140647709/evaluated-papers)

**Comment by LinaKind** [comment]
List of doi fragments that we think are not evaluated, total 55.
[non-evaluated-dois.txt](https://github.com/user-attachments/files/17619791/non-evaluated-dois.txt)

**Comment by LinaKind** [comment]
how many Papers do the evaluations point to with their `relation`? 423

[evaluated-papers.txt](https://github.com/user-attachments/files/17620018/evaluated-papers.txt)

**Comment by giorgiosironi** [comment]
Investigation on the above 6 dois showed duplication in the [evaluated-papers-api-response.txt](https://github.com/user-attachments/files/17620497/evaluated-papers-api-response.txt):
```
$ grep 000913 evaluated-papers-api-response.txt  -A 2 -B 2
  "items": [
    {
      "representative": "10.1099/acmi.0.000913.v2",
      "lastEvaluatedAt": "2024-10-31T00:00:00.000Z"
    },
--
    },
    {
      "representative": "10.1099/acmi.0.000913.v1",
      "lastEvaluatedAt": "2024-10-02T00:00:00.000Z"
    },
```

**Comment by LinaKind** [comment]
This API https://staging.sciety.org/api/groups/4d6a8908-22a9-45c8-bd56-3c7140647709/evaluated-papers as of today returns 432 items. By extracting unique paper doi prefixes from the EvaluationPublicationRecorded events we also count 432 items.
