### ISSUE TITLE
Use  fast-xml-parser for title in the expression front matter

### ISSUE THREAD

**Issue by LinaKind** [sciety/sciety#3662]

**Comment by giorgiosironi** [comment]
A [Grafana investigation](https://sciety.grafana.net/explore?schemaVersion=1&panes=%7B%22al9%22:%7B%22datasource%22:%22grafanacloud-logs%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bapp_kubernetes_io_name%3D%5C%22sciety%5C%22,app_kubernetes_io_instance%3D%5C%22sciety--prod%5C%22%7D%5Cn%7C%20json%20%7C%20__error__%3D%5C%22%5C%22%5Cn%7C%20message%20%3D%20%5C%22build-expression-front-matter-from-crossref-work:%20Unable%20to%20find%20title%5C%22%22,%22queryType%22:%22range%22,%22datasource%22:%7B%22type%22:%22loki%22,%22uid%22:%22grafanacloud-logs%22%7D,%22editorMode%22:%22code%22%7D%5D,%22range%22:%7B%22from%22:%22now-7d%22,%22to%22:%22now%22%7D%7D%7D&orgId=1) leads to a first result of an unsupported paper, with two `<titles>` elements:
https://gist.github.com/giorgiosironi/1316faedfb15653b7411f82fc185559c
