### ISSUE TITLE
Fix evaluation records for one paper evaluated by Biophysics Colab

### ISSUE THREAD

**Issue by davidcmoulton** [sciety/sciety#3670]
https://sciety.org/articles/activity/10.1101/2023.08.12.553106

curl -v -H "Authorization: Bearer secret" -X POST http://localhost:8080/api/erase-evaluation -H "Content-type: application/json" -d '{"evaluationLocator": "hypothesis:LBUFQLDXEe-oyBPqVYar5Q"}'

**Comment by erkannt** [comment]
- References to the deleted hypothesis annotations have been removed the Sciety page.
- The curation statement annotation on hypothesis does not have a 'Summary' tag. Previous curation statements by the group have such a tag allowing our ingestion to automatically tag them as 'curation-statement.


(Locally we tried to change the evaluation type of one evaluation to be 'curation-statement' to make it show up as a curation statement. This has not resulted in the desired UI change. We will pick this up when we next work on Sciety.)
