### ISSUE TITLE
biorXiv, crossref, DOI delays, missing

### ISSUE THREAD

**Issue by erkannt** [sciety/sciety#368]
- [ ] ~contact crossref re: missing DOI in transform endpoint @BlueReZZ~

**Comment by BlueReZZ** [comment]
I was just about to hit send on this then realised that the DOI I was testing was different to the one in #357 and that one is still returning a 404.

The other issue was down to the way I was requesting the API, it seems there's no default content negotiation on the `/transform` so you need to specify JSON in the `Accept` header. This is not the same as the standard article endpoint.

I'll close this and continue to check https://doi.org/10.1101/2020.12.16.423020 which should redirect to https://www.biorxiv.org/content/10.1101/2020.12.16.423020v1 and give us a `200` response from:

`curl -v -H "Accept: application/json" "https://api.crossref.org/works/10.1101/2020.12.16.423020/transform"`
