### ISSUE TITLE
Explore funnel metrics

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#373]
Window from 2020-12-14 to 2021-01-12.

- [x] What percentage of visitors are logging in?
  - [x] How many are starting log in? 175
  - [x] How many complete log in? 49
- [x] What percentage of visitors are leaving breadcrumbs?
- [x] How many breadcrumb events? 59, all `UserFollowedEditorialCommunity`
- [x] How many users left at least one breadcrumb? 25
  - [x] What is the median number of breadcrumbs per user? 2
- ~[ ] Are people being put off leaving breadcrumbs because of the log in barrier?~
  - 126 users began login but did not complete (72%)

## Caveats

- [Google Analytics numbers show 21 `Follow` GA events](https://analytics.google.com/analytics/web/#/report/content-event-events/a167311475w233457116p219087825/_u.date00=20201214&_u.date01=20210112&explorer-segmentExplorer.segmentId=analytics.eventAction&explorer-table.plotKeys=%5B%5D&explorer-table.rowStart=0&explorer-table.rowCount=10/) despite a corresponding 59 Domain Events; this suggest our GA setup is not tracking as many users or events as it should, or the user has not clicked on the cookie consent/has an ad blocker/etc
  - [Google Analytics shows 10 distinct users creating `Follow` GA events](https://analytics.google.com/analytics/web/#/my-reports/Q0iul9oTTwSekdaWW8wB3Q/a167311475w233457116p219087825/_u.date00=20201214&_u.date01=20210112), same caveat on whether this is missing data
- Log in attempts and successes number is a total count, not distinct users
- Further automation required for some of these questions if we want to answer them regularly

**Comment by giorgiosironi** [comment]
https://docs.google.com/spreadsheets/d/1wrmL1osJFjWMndUTqzZ6RTafWfcf2WQLCNwW06ENTcA/edit?usp=sharing

**Comment by giorgiosironi** [comment]
Comparing data across this period:
- GA users: 202
- GA sessions: 290
- Distinct ip addresses (includes bots, non consenting users, adblocked users) :3231

**Comment by giorgiosironi** [comment]
Refining:
- [GA finds 34 page views on a test article](https://analytics.google.com/analytics/web/#/report/content-pages/a167311475w233457116p219087825/_u.date00=20201214&_u.date01=20210112&_r.drilldown=analytics.pagePath:~2Farticles~2F10.1101~2F2020.06.15.152868&explorer-table.plotKeys=%5B%5D)
- `Hits on test article for comparison with GA` log query finds out 187 distinct user agents in the same period, after a best effort attempt to exclude bots

**Comment by hdrury1** [comment]
- Can we make the numbers coming out of GA more accurate?
- Can we automate the process of pulling these numbers out of the logs/database?

**Comment by hdrury1** [comment]
![Vision and assumptions (3)](https://user-images.githubusercontent.com/17023702/104472776-35cc7c80-55b4-11eb-85db-0cf0c37861c8.jpg)
