### ISSUE TITLE
Is the %age of non-consenting sessions stable?

### ISSUE THREAD

**Issue by kevinrutherford** [sciety/sciety#383]
Objective: compare daily session counts from GA to similar extracted from the logs

Caveat: the error bars will be large, because the overall numbers are small.

- [x] track daily sessions
  - [x] going back to when we added IP address to the logs (2020-12-11)
  - [x] what is the GA definition of a "session"?
  - [x] how should we define a "session" in the logs?
    - [x] exclude bot user agents
    - [x] unique IP-User Agent pairing per day 
- [x] don't think about automation or tooling for now
  - [x] get the data out of Cloudwatch and do the rest by hand

**Comment by giorgiosironi** [comment]
> In order for Google Analytics to determine which traffic belongs to which user, a unique identifier associated with each user is sent with each hit. This identifier can be a single, first-party cookie named __ga_ that stores a Google Analytics client ID, or you can use the _User-ID_ feature in conjunction with the client ID to more accurately identify users across all the devices they use to access your site or app. 
>
> -- https://support.google.com/analytics/answer/2992042?hl=en

> A single user can open multiple sessions. Those sessions can occur on the same day, or over several days, weeks, or months. > As soon as one session ends, there is then an opportunity to start a new session. There are two methods by which a session ends:
> - Time-based expiration:
>   - After 30 minutes of inactivity
>   - At midnight
> - Campaign change:
>    - If a user arrives via one campaign, leaves, and then comes back via a different campaign.
>
> -- https://support.google.com/analytics/answer/2731565?hl=en#zippy=%2Cin-this-article

<img src="https://lh3.googleusercontent.com/jYib9rNgrLOavCGfEaMPqJNOIf6cN5aHqsZpXAKPP1IVOUM3iFImIIxMW_AnWHlI5xKJ=w1100" />

**Comment by giorgiosironi** [comment]
CSV extraction:
```
$ cat real-user-page-hits-on-prod-20210118-20210124-tabs | sed -e 's/ [^\t]*\t/\t/' | grep -v HeadlessChrome | cut -f 1,2,3 | sort | uniq -c | sort | wc -l
449
```

**Comment by will-byrne** [comment]
GA numbers

Day Index | Sessions
-- | --
18/01/2021 | 22
19/01/2021 | 15
20/01/2021 | 33
21/01/2021 | 10
22/01/2021 | 9
23/01/2021 | 5
24/01/2021 | 6
  | 100

**Comment by will-byrne** [comment]
Difference in detected sessions between GA(blue) and Logs(red, using query above)

<img width="893" alt="Screenshot 2021-01-25 at 11 55 14" src="https://user-images.githubusercontent.com/13573277/105702790-334b1a80-5f04-11eb-9981-30ede703a5d2.png">

**Comment by will-byrne** [comment]
list of unique user agents that need to be filtered to remove the rest of the bots
[user_agents.txt](https://github.com/sciety/sciety/files/5866378/user_agents.txt)

**Comment by davidcmoulton** [comment]
Based on `user_agents.txt`, additional user agents to screen out include:
```
PhantomJS
crawler
Crawler
Crawlson
HttpClient
Aviary
EventMachine
http-client
Go http package
GRequests
GuzzleHttp
Dataprovider.com
NetcraftSurveyAgent
TrendsmapResolver
ips-agent
ubermetrics
Python-urllib
ShortLinkTranslate
Twingly
Twitter
Typhoeus
WordPress.com
gocolly
fasthttp
http.rb/4.0.0
jetstack-cert-manager
ltx71
node-fetch
python-requests
```

Note there are a number of lines lacking a user agent, but including a request. Suggests the data extraction needs improvement.

**Comment by giorgiosironi** [comment]
Graphs from https://docs.google.com/spreadsheets/d/1ALO0uA9Fd0783mElYw_viBSUyNEaaknL08aAQBPn7cA/edit#gid=1180942363

![Screenshot_2021-01-25 visitors-overview](https://user-images.githubusercontent.com/160299/105722617-c47abb00-5f1d-11eb-80df-5f3bd752ba6c.png)

**Comment by giorgiosironi** [comment]
The bucket `s3://sciety-data-extractions` has the raw data.
