### ISSUE TITLE
Display versions of medrxiv articles on sciety article pages

### ISSUE THREAD

**Issue by davidcmoulton** [sciety/sciety#384]
Example of medrxiv article reviewed by eLife, with multiple versions: https://www.medrxiv.org/content/10.1101/2020.09.03.20184051v2.full

- [x] show version error with correct server
- [x] show versions for medrxiv
- [x] ~check that abstract for http://localhost:8080/articles/10.1101/2020.05.22.20110593 works (mathML?)~ https://elifesciences.slack.com/archives/C011EQLKP51/p1611741689024900

## Refactoring

- [x] create a type for `'biorxiv' | 'medrxiv'` somewhere
- [x] medrxiv unit tests for `get-biorxiv-article-version-events`
- [x] rename `GetBiorxivArticleVersionEvents` type and implementation
- [x] improve `getServer`, pipe?
- ~should we move the avatars for biorxiv and medrxiv to static files?~
- ~begin using domain terminology "articleId" instead of "doi" for variable names~
- [x] extract medRxiv equivalent of `RenderArticleVersionErrorFeedItem`
- [x] remove promises in `handle-article-version-errors`
- [x] find out why `FetchExternalArticle` didn't need the `server` field
- [x] make sure `HtmlFragment` is used in `render-page` rather than strings
- [x] remove `Result` from `render-page`

## Technical debt

- [x] make the lint fix the uniformity on `;` vs. `,` in type definitions
- [x] make the lint enforce `type` over `interface`
- [x] review recent fp-ts code
- [x] lint rules for fp-ts
- ~make `parse-crossref-article` use Options, e.g. `getElement`~ punt to working on Codecs
- [ ] Remove NPM `hightlight.js` version warning

**Comment by giorgiosironi** [comment]
Using http://localhost:8080/articles/10.1101/2021.01.23.427922 to temporarily test the error of missing versions on a biorxiv article.

**Comment by erkannt** [comment]
```
curl -v https://api.crossref.org/works/10.1101/2021.01.15.21249880/transform -H "Accept: application/vnd.crossref.unixref+xml"
```

**Comment by davidcmoulton** [comment]
My Firefox is blocking the hot-linked avatar images from Twitter in the article feed:

<img width="1248" alt="Screenshot 2021-01-27 at 16 25 34" src="https://user-images.githubusercontent.com/2893480/106021197-74862a80-60bc-11eb-966f-9b92e411d977.png">

(taken from https://staging.sciety.org/articles/10.1101/19003376 on 2021-01-27 at 16.25.34)

This doesn't seem to be a problem on the profile page, where avatars loaded in the same way are displayed. 

Looks like an example of opaque / arcane browser heuristics.
