### ISSUE TITLE
Hard code an NCRC review

### ISSUE THREAD

**Issue by BlueReZZ** [sciety/sciety#405]
- [x] Don't display the link back to the original source since there's no URL
- [x] Assume there will be a `UUID`
- [x] Assume that we have a usable date
- [x] Do not typeset the content (missing sup, sub, italic etc)
- [x] Introduce ~sections~ headings for each section of the content
- [x] Take an example row from https://docs.google.com/spreadsheets/d/1tDO5yci19_jRsUQY9uAkvga3OY9Jblky2yhknrN1Cww/edit#gid=0
- [x] Keep it only on `staging`
- [x] Populate editorial community page content from https://ncrc.jhsph.edu/what-we-do/
- [x] See more / See less buttons
- ~Review responses~
- [x] Feed on editorial community page
- ~Feed on home page~
- ~Add the NCRC community to the `data/editorial-community-joined.csv` file~ no longer used

## Refactor

- ~Make NCRC community page not look broken (list)~

## Tech debt

- [x] Make `templateListItem` take a `ReadonlyNonEmptyArray`.
- [x] Investigate why no error on http://localhost:8080/articles/10.1101/2021.01.29.21250653
- [x] Try to introduce `TaskEither` into `fetch-datacite-review`
- [x] Remove unused `publicationDate` from error return in `fetch-datacite-review`

**Comment by thewilkybarkid** [comment]
Hard-coding https://ncrc.jhsph.edu/research/robust-spike-antibody-responses-and-increased-reactogenicity-in-seropositive-individuals-after-a-single-dose-of-sars-cov-2-mrna-vaccine/ (review of https://doi.org/10.1101/2021.01.29.21250653)

**Comment by giorgiosironi** [comment]
Example at row 2780 of https://docs.google.com/spreadsheets/d/1tDO5yci19_jRsUQY9uAkvga3OY9Jblky2yhknrN1Cww/edit#gid=0 has a different version of the `final_take` column (perhaps outdated) with respect to https://ncrc.jhsph.edu/research/robust-spike-antibody-responses-and-increased-reactogenicity-in-seropositive-individuals-after-a-single-dose-of-sars-cov-2-mrna-vaccine/ which adds `available as a preprint and thus not yet peer reviewed`.
