### ISSUE TITLE
Add NCRC and its reviews

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#410]
- [x] keep it on `staging`
- [ ] check correct name of editorial community (`NCRC` or else) /cc @BlueReZZ 
- [x] add `ncrc-sheet@sciety.iam.gserviceaccount.com` to authorized users of NCRC Google Sheet /cc @BlueReZZ 
- [x] generate review URL via string transformation of the article title
- [x] fetch data for the currently hardcoded article 10.1101/2021.01.29.21250653
  - [x] call Google sheets
  - [x] generate HTML from spreadsheet columns
  - [x] `ReviewFeedItem` in `render-review-feed-item` has a `source` field that now must be optional
  - [x] change `get-events-from-data-files` to add an event with a `NcrcId` rather than the hardcoded DOI
  - [x] create `fetch-ncrc-review` to generate HTML from spreadsheet columns
  - [x] `fetch-review` needs to delegate to `fetch-ncrc-review`
  - [x] Add new `ReviewId` type to include NCRC uuid
  - [x] check `toReviewId`
  - [x] ensure NCRC review ids are correctly serialized and deserialized
  - [x] tackle `reviewId.toString()` usage
- [x] provide credentials for google sheets api calls
  - [x] manually create GCP service account for terraform
  - [x] add SA keys to infra repo secrets
  - [x] add GCP provider 
  - [x] generate key from terraform
  - [x] insert key as secret to cluster
  - [x] local usage
    - [x] .gitignore key file
    - [x] generate local file using `gcloud`
    - [x] mount local key file into docker containers
  - [x] setup google auth in application
  - [x] break up `fetch-ncrc-review` so that unit tests don't make real calls 
  - [x]  helm chart: populate file from secret
- [x] find out which row we should be loading
  - [x] investigate whether there is a `find` API (only find&replace could be found in `batchUpdate`)
  - [x] select first column (400+) cells and look for the UUID
- [x] add script to fetch data for all articles
- ~display something (e.g. a link, even to the homepage) to the user when we can't get content from NCRC; this includes some local usages when you run the application without key~ Needs UX guidance
- [x] log exceptions coming from google sheets
- ~duplicates?~ Awaiting feedback

Expect roughly 110 medrxiv and 14 biorxiv articles.

See https://github.com/sciety/sciety/issues/406 for various dependencies

## Out of scope

- refactoring/tech-debt removal regarding `ReviewId` types, split off into #452 

## Refactoring

- [x] clean up `fetch-datacite-review` from hardcoding
- [x] clean up inferredUrlFromReviewId
- [x] problem: `something.toString()` has returned `[object Object]` in the browser and this could be caught by linting
- [x] resolve `// eslint-disable-next-line no-underscore-dangle` comments
- [x] use `/var/run/secrets/sciety`  or similiar for our key to avoid collisions
- [x] dedupe call and value extraction from sheets

## Tech debt
- ~handle Hypothesis API errors (current behaviour is to throw, breaking the page)~
- ~test left side of `TaskEither` in `infrastructure/fetch-review.ts`~
- ~Replace classes with branded strings~
- [x] Fix
   > ts-jest[config] (WARN) The option `tsConfig` is deprecated and will be removed in ts-jest 27, use `tsconfig` instead
- ~why could we use `NcrcId` without exporting it~
- ~duplication of `FoundReview` type~

**Comment by thewilkybarkid** [comment]
Following https://denisluiz.medium.com/python-with-google-sheets-service-account-step-by-step-8f74c26ed28e for how to authorize without a user-dependant OAuth flow.

**Comment by giorgiosironi** [comment]
To allow a person to impersonate a service account for local usage:
https://cloud.google.com/iam/docs/impersonating-service-accounts

**Comment by giorgiosironi** [comment]
ReviewId to change:
```
NcrcId.fromString('0c88338d-a401-40f9-8bf8-ef0a43be4548'),
```

**Comment by giorgiosironi** [comment]
Possibly relevant: https://stackoverflow.com/questions/50921909/how-to-invoke-gcloud-with-service-account-impersonation

**Comment by giorgiosironi** [comment]
https://cloud.google.com/iam/docs/service-accounts states:

> You can create up to 10 service account keys per service account to facilitate key rotation.

**Comment by giorgiosironi** [comment]
The following articles have duplicated reviews:
```
      2 10.1101/2020.03.27.20043836
      2 10.1101/2020.03.31.20049023
      2 10.1101/2020.04.01.20047381
      2 10.1101/2020.04.06.20055632
```
