### ISSUE TITLE
Update link to PCI Ecology RSS feed

### ISSUE THREAD

**Issue by hdrury1** [sciety/sciety#480]
We've heard back from PCI who are going through a migration of all of their sites, hence the altered RSS URLs.

Their developer is pretty overwhelmed but they do have a new feed for PCI Ecology that they'd like us to test:

https://ecology.peercommunityin.org/rss/rss4elife

If it's bigger than changing the URL, reconsider.

**Comment by giorgiosironi** [comment]
Only 2 communities support the new URL; the other 4 work on the old one.
