### ISSUE TITLE
Introduce left hand side nav and drawer

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#489]
- Is always user-toggleable from the icon control.
- collapses automatically when the viewport is too narrow.

## Questions
**Question: how does the viewport width compete with the user interaction to determine whether the menu is shown?**

For example:

- Scenario A:
  1. I load the page in a wide viewport, the menu is shown as the media query has fired
  1. I click the toggle to hide the menu
  1. I click the toggle to show the menu, I have now indicated a desire for the menu
  1. I make the viewport narrower, should the media query take precedence and hide the menu, or should the user interaction take precedence and keep it visible even though things are close to getting squished?
 
- Scenario B:
  1. I load the page in a narrow viewport, the menu is hidden as the media query has not fired
  1. I click the toggle to show the menu
  1. I click the toggle to hide the menu, I have now indicated a desire for the menu going away
  1. I make the viewport wider, should the media query take precedence and show the menu, or should the user interaction take precedence and keep it hidden even though there's plenty of space to show it now?

Answer: ~**The user preference should take precedence over the viewport width.**~ Reopened. See below.

**Question: when on a page with content longer than the viewport height, the top menu with the toggle for the flyout menu scrolls off the top of the screen. Should the top nav bar stick to the top of the screen?**

Answer: **Yes.**

**Question: how does the existing footer play with this design, before the footer bits and pieces are incorporated into the flyout menu?**

- [ ] min width on content. Will force horizontal scroll. How to handle menu toggle? Can keep on screen?
- [ ] Should menu state persist across page loads?
- [ ] what should happen to the menu if someone opens page in a new tab/window?
- [ ] revisit question "How does the viewport width compete with the user interaction to determine whether the menu is shown"

## Current understanding of non-js behaviour
- [ ] Menu display is by media query
- [ ] Menu toggle displayed on narrow view & links to a separate page of navigation links
- [ ] Menu toggle hidden on wide view when menu is displayed

When js is available:
- [ ] change link on menu toggle to be the fragment identifier of the menu
- [ ] don't hide the menu toggle on wide view

- [ ] Fix mobile experience of search box placeholder text

**Comment by NickDuf** [comment]
Design reference files
- [Mobile design logged in/out](https://invis.io/QJ109JWXEVRU#/446498848_review-Mobile-Broken-Down-Profile)
- [Mobile search active/inactive](https://invis.io/QJ109JWXEVRU#/446498850_review-Mobile-Broken-Down-Search)
- [Mobile drawer and profile/](https://projects.invisionapp.com/d/main?origin=v7#/console/21112247/446498849/preview?scrollOffset=405)
- [Desktop](https://projects.invisionapp.com/d/main?origin=v7#/console/21112247/445379630/preview?scrollOffset=405)

**Comment by davidcmoulton** [comment]
This would be a good time to introduce "Skip to content" links. To see how they can work, load a Github page, and then press the tab key.

**Comment by thewilkybarkid** [comment]
Reading: [Responsive, Pure CSS Off-Canvas Hamburger Menu](https://medium.com/@heyoka/responsive-pure-css-off-canvas-hamburger-menu-aebc8d11d793)

**Comment by davidcmoulton** [comment]
@thewilkybarkid The problem with that is that using a checkbox feels a bit hacky, and  `:target` is unlikely to be robust enough to stand up to the possibility of using other page anchors, and toggling it can become annoying. I've got a prototype that ticks the boxes for source / tab order, visual order, layout and behaviour, only using js to toggle the menu by setting a data attribute. Will post a link.

**Comment by giorgiosironi** [comment]
For reference, what I see when I try to open a menu link in a new tab in Feedly:
![Screenshot_2021-03-16 Feedly – Goodbye information overload](https://user-images.githubusercontent.com/160299/111286929-a0dd1280-863a-11eb-85e9-6f5694343d8a.png)
