### ISSUE TITLE
Update integration with PREreview to use new API

### ISSUE THREAD

**Issue by erkannt** [sciety/sciety#514]
**Timebox: 2 hours**

> The new PREreview API and documentation can be found here: https://www.prereview.org/api/docs. I’ll let @Josh King and @Harum answer any follow-up questions as needed.

> Hey @Hannah Drury, just to follow up, you can pull all of the full-length reviews via a `GET /api/v2/full-reviews` , all the rapid-reviews at `GET /api/v2/rapid-reviews`, and all the preprints at `GET /api/v2/preprints`. All of these endpoints include query parameters `limit=<integer>` to limit the number of items in the response, `offset=<integer>` to start the list of items a certain number of items in to the list,  `asc=<boolean>` to set the sort order to ascending or descending, and `is_published=<boolean>` to limit the results to only those published or unpublished on the site. Reviews are sorted by date. Preprints also have `search=<string>` which does a case-insensitive full-text search of preprint title, author, abstract, and DOI/arxivID. For example, to get the first 10 published rapid reviews starting with review #5, you would `GET:
GET /api/v2/rapid-reviews?limit=10&offset=5&is_published=true`
Let me know if you run into any problems! We're still making tweaks and changes to the API, so any feedback is helpful!

**Comment by davidcmoulton** [comment]
Hannah says stick with full reviews for now, until we've had a conversation about rapid reviews.

**Comment by thewilkybarkid** [comment]
The functionality is there, we haven't committed the data updates due to the data issues mentioned in https://elifesciences.slack.com/archives/C011EQLKP51/p1617185815146100.
