### ISSUE TITLE
Remove feature flag from NCRC content

### ISSUE THREAD

**Issue by hdrury1** [sciety/sciety#525]
- ~Confirm duplicates have disappeared~ Decision to leave duplicates in.
- [x] Remove feature flag
- [x] Check live in Production

**Comment by giorgiosironi** [comment]
Duplicates have not disappeared:

- https://staging.sciety.org/articles/activity/10.1101/2020.03.27.20043836
- https://staging.sciety.org/articles/activity/10.1101/2020.03.31.20049023
- https://staging.sciety.org/articles/activity/10.1101/2020.04.01.20047381
- https://staging.sciety.org/articles/activity/10.1101/2020.04.06.20055632
