### ISSUE TITLE
Italic run on in teaser text

### ISSUE THREAD

**Issue by will-byrne** [sciety/sciety#526]
Third review of [this article](https://staging.sciety.org/articles/activity/10.1101/2020.12.07.414862) has italics that run on the rest of the feed. 

Lots of `<em>` and `</em>` in the rest of the markup, including round the footer.

**Comment by hdrury1** [comment]
Also https://staging.sciety.org/articles/activity/10.1101/2020.02.22.961052

**Comment by thewilkybarkid** [comment]
The cut-off point in the teaser is in an `<em>`, which is left unclosed.

(All the other `<em>`s are inserted by the browser to make it a valid DOM, they're not in the actual source.)
