### ISSUE TITLE
Update script for PCI fails

### ISSUE THREAD

**Issue by erkannt** [sciety/sciety#535]
## Issues

- rss `link` elements contain two dois, we currently select the first one, we need to select the second
- website has changed, `pci-recomOfSource` element no longer exists
- the date in the new feed doesn't obviously relate to the reviews or the article

## Refactoring
- [ ] Use more accurate XPaths
- [ ] fix `unable to start` log message (missing meaning)
- [ ] log and skip broken feed entries
- [ ] report back to pci-evol-biol that their feed is inconsistent

## Tech debt
- [ ] Look into using codec for this script

**Comment by hdrury1** [comment]
Full list of RSS feeds for PCI content

https://evolbiol.peercommunityin.org/rss/rss4elife

https://ecology.peercommunityin.org/rss/rss4elife

https://archaeo.peercommunityin.org/rss/rss4elife

https://genomics.peercommunityin.org/rss/rss4elife

https://paleo.peercommunityin.org/rss/rss4elife

https://zool.peercommunityin.org/rss/rss4elife

https://cneuro.peercommunityin.org/rss/rss4elife

https://forestwoodsci.peercommunityin.org/rss/rss4elife

https://mcb.peercommunityin.org/rss/rss4elife

https://animsci.peercommunityin.org/rss/rss4elife

https://networksci.peercommunityin.org/rss/rss4elife

**Comment by BlueReZZ** [comment]
I added the URLs which all return data now 👍🏻 but having run the scripts it found no new evaluations from any PCI community, although the feeds say there are. Presume the work in this ticket is now to figure out why that is - likely a structure change or similar.

**Comment by thewilkybarkid** [comment]
@kevinrutherford and I looked at updating the script to use the new RSS, but the `<date>` field doesn't match the recommendation date on the page.

**Comment by hdrury1** [comment]
PCI have responded: `<date>` refers to the publication of the recommendation (rather than the date it was written). They would like us to use this date in our activity feed. /cc @kevinrutherford and @thewilkybarkid

**Comment by erkannt** [comment]
Closing in favour of Gold Card
