### ISSUE TITLE
Search box on results page, link to it in nav

### ISSUE THREAD

**Issue by erkannt** [sciety/sciety#554]
Highlight the existence of search on each page, not only the homepage.

## Scope

- [ ] add search box to results page
  - [x] query persists in search box
    - [x] otherwise there is a placeholder text (see designs)`
  - [x] `X` in the search box
    - [x] style
    - [x] is visible when the query is present
    - [x] pressing it clears the entry
    - [x] should be keyboard usable
    - [x] with an appropriate label for screen readers
    - [x] roll out to search page
  - [x] hidden submit button for screen readers
  - [ ] states of box and clear button (e.g. focus)
- [x] change `<h1>` (see designs)
- [x] change `<title>`: `Sciety | Search results for [search phrase]`
- [x] the text is "10 of $N results for [search phrase]"
  - [x] placed under the search box (see designs)
- [x] left margins consistent across elements and viewports
- [x] search icon in navbar links to search page without a query
  - [x] don't show any results when there's no query (there is a new empty query search page)
  - [x] make background colour fill the screen (ignoring `margin-bottom` on `<main>`)
- ~Taiko test~

## Required Designs

- [x] search box on results/search page
- [x] navbar with icon

Match to designs: https://projects.invisionapp.com/d/main?origin=v7#/console/21112247/445867128/preview?scrollOffset=1134

## Questions
- [x] Should `sciety` be `Sciety`?
- ~For better accessibilty, `Sciety` should prefix rather than suffix the `<title>` value. Can we make that change site wide?~
- [x] Can we improve on the current placeholder text?
- [x] Where should the search icon go in the current old fashioned site nav?
- ~on wider viewports, should the left text edge of the text box line up with the left edge of the card text?~

## Refactoring
- [x] move media queries inside style rules (structure for sass not css) in file `_search-results-page.scss`
- ~is there shared CSS between the search and search-results pages~
- ~are there shared components between search and search-results pages~

**Comment by davidcmoulton** [comment]
As the `<title>` of the page is the first thing read by a screen reader when a page is loaded, good practice for the contents of the `<title>` element on a search results page would be: `Sciety | Search results for [search phrase]`

**Comment by hdrury1** [comment]
Suggested amendment to placeholder text: "Discover articles, groups, authors and more..."
