### ISSUE TITLE
Build menu navigation page

### ISSUE THREAD

**Issue by davidcmoulton** [sciety/sciety#580]
## Feature
- [x] Add new route to menu page
- [x] Content
  - [x] Add markup
  - [x] Add styles
    - [x] colours
    - [x] typography
    - [x] menu item icons
    - [x] feedback button
    - [x] layout
      - [x] align left `X` and match top bar with visual linked by Nick
      - [x] remove margin-bottom from `<main>`
      - [x] fix vertical alignment of top bar
      - [x] fix typography of top bar
      - [x] Max-width for menu items is 300px
    - [x] remove drop shadow on site nav
    - [x] hover state, only in this page
    - [x] focus state, across the site (apply `:focus` (normalise))
- [x] Hardcode menu page
  - [x] new `applyStandardPageLayout` 
  - [x] remove existing header
  - [x] new header
    - [x] close icon (does nothing)
    - [x] search icon
    - [x] login
  - [x] restyle/structure footer
- [x] Implement the close nav button (using referer)
- [x] Fix the tab order to reflect prototype
- [x] Remove titles from SVGs if present
- [x] Check with a screen reader
- [x] Stop legal link being 100% wide
- [x] Correct the height of the menu list in Chrome (set height of `menu-page-container` to 100vh)
- [x] Add padding to menu list items.

## Questions for Nick

- [x] The designs have no Sciety logo under certain circumstances -- is this intentional? Nick says "It is for now, until we figure out what's were doing with the top nav. There was talk of share buttons etc"
- [x] Designs have more padding on left of burger icon than on the right of the log in / out button, is this intentional?
       Yes. Is intentional
- [x] Focus state for links? Same as buttons?
      Yes. Roll out everywhere.
- [x] What should be the focus/clickable area on the menu links?
       Nick will provide a maxwidth for the clickable are
- [x] Does the design for the menu page change on a wide viewport?
      Nick will provide a design. Fonts probably stay the same. Positioning/Grid will probably change.
- [x] In the flyout menu, we will line-clamp menu entries to 2 lines plus ellipsis. Should that also apply here? Yes
- [x] hover state on dark background (new menu footer)? Fine as built.

## Refactoring

- [x] Extract the `visually-hidden` duplication
- [x] progressively enhance with `:focus-visible`
- [x] Extract to a mixin for link states
- [x] extract magic numbers
- [x] Rename / Remove `site-header` related classes

## Tech debt
- [x] Check cache control headers ~(logged in & also on menu page but logged out)~ limited to `Referer`
- [x] Remove `order/order` rule for `at-rules` inside blocks [aggregate rules](https://github.com/bjankord/stylelint-config-sass-guidelines/wiki/Lint-Rule-Comparison) [rules](https://github.com/hudochenkov/stylelint-order/blob/master/rules/order/README.md)
- [x] ~Consolidate states into the `_states` partial~
- [x] ~Consolidate duplication of component states, perhaps into component partials e.g. `button` containing `button.accent()` or `button.default()` or `button.icon()`~ nothing extractable found (yet)
- [x] simplify link style overrides now that we have `normalise`

## Prototype
https://davidcmoulton.github.io/ui-impementation-idea/public/
https://davidcmoulton.github.io/ui-impementation-idea/public/index-no-js.html

**Comment by NickDuf** [comment]
@davidcmoulton here are the answers to your questions including a [visual](https://invis.io/QJ109JWXEVRU#/447990504_drawer-Desktop-No-Js).

- **Does the design for the menu page change on a wide viewport?** - No, it's exactly the same. We align left, no grid inside the app bar.
- **What should be the focus/clickable area on the menu links?** - Max-width for menu items is 300px
