### ISSUE TITLE
Implement narrow no-js version, on all pages

### ISSUE THREAD

**Issue by davidcmoulton** [sciety/sciety#581]
### Narrow
- per design: https://projects.invisionapp.com/d/main?origin=v7#/console/21112247/447546543/preview?scrollOffset=1796.7166748046875
- per prototype: https://davidcmoulton.github.io/ui-impementation-idea/public/index-no-js.html

### Wide
- burger menu disappears
- existing top nav appears:
<img width="812" alt="Screenshot 2021-03-22 at 09 28 14" src="https://user-images.githubusercontent.com/2893480/111968352-f6109c80-8af0-11eb-95cd-36a8b2f76556.png">

...

## Features

- [x] hide the logo on narrow
- [x] hide the `Home`, `About` links on narrow
- [x] add the hamburger menu link to `/menu`
- [x] hide the hamburger on wide
- [x] accessibility as per prototype

## Questions

- [x] Why using a `::before` to set the menu button link text for screen readers rather than the HTML?
- [x] Should the menu item not be in a list?

**Comment by giorgiosironi** [comment]
Options:
- implement the no-js design for both narrow and wide, roll out for everyone
- implement the no-js design for narrow only, wide needs duplicate navigation markup plus some media query
- implement the no-js design for narrow only, but fill in with JavaScript somehow the original markup we have now
