### ISSUE TITLE
Can no longer follow communities, and corrective actions

### ISSUE THREAD

**Issue by erkannt** [sciety/sciety#595]
## Diagnosis

- [x] editorialCommunityId in `follow` event is blank

## Recover working state

- [x] rename hidden inputs back to `editorialcommunityid` on home page and user page.
- [x] delete the broken event from the staging database

## Command validation

- [x] ensure non-empty `GroupId` results in user friendly error page and doesn't get committed
  - [x] Follow
  - [x] Unfollow 
- [x] check other forms
  - [x] respond
  - [x] save article
- ~ensure existing article (respond, save article)~
- ~ensure valid `UserId`~

## Improvements

- [x] collapse three Follow/Unfollow toggles into the same thing
- [ ] Follow button work
  - [x] hidden fields should have names that come from the command handlers
  - [x] address coupling of field names in `context.session`
  - [x] rename fields to avoid `community` in it
  - [x] collapse taiko tests to match
  - [x] check fields before redirecting to log-in
  - [ ] ensure `GroupId` is a current one, before committing
  - [ ] address coupling of field names in `context.session` (don't save individual fields, use codec in both directions)
  - [ ] address duplication between the command handlers
  - [ ] improve the fast test coverage of the Follow/Unfollow command
- [ ] apply the same pattern to `/unfollow`
- [ ] apply the same pattern to `/respond`
- ~replace `catchErrors` middleware to avoid throws~
- [ ] user-friendly error message when `/respond` is broken
- [ ] user isn't told when the `save-article` command fails (to write the event)

## Resilience

- [ ] useable error message on reading bad event from database
- ~startup app, ignoring bad events?~
- [x] Add Taiko test for user following / unfollowing a community
- [x] Add Taiko test for respond helpful

## Punted

- [ ] use Premium Twitter API to get a sandbox so that Taiko doesn't run into added security steps when logging in

**Comment by giorgiosironi** [comment]
We tried duplicating the `prod-sql` Makefile target to connect to staging, but we cannot connect to it. The credentials that the `psql` pod sees are identical to the ones the running staging application is using, but we get timeouts or password errors.
The `staging` database is running correctly as the existing staging app is still running too, and all indicates these credentials are correct.
