### ISSUE TITLE
Add a preLights hardcoded evaluation with a guid rather than a Doi

### ISSUE THREAD

**Issue by hdrury1** [sciety/sciety#614]
Ticket to help preLights build custom RSS feed: https://github.com/sciety/sciety/issues/470

**Comment by giorgiosironi** [comment]
The production deployment for the preLights RSS feed is scheduled for today.

**Comment by hdrury1** [comment]
> Morning Hannah (and all),

I hope everyone is well. You beat me to it Hannah - the deployment completed overnight, you can access the live URL at:

https://prelights.biologists.com/feed/sciety/?key={key-as-previously-provided}

If we could ask that you aim to use the filter arguments on the URL to avoid overloading the feed generator, as discussed during the build phase.

If there are any questions please do not hesitate to contact me.

All the best,

Julian

**Comment by giorgiosironi** [comment]
> The following optional parameters are:
>    hours - an integer which defines the number of hours the feed covers, counting back from the current time, based upon the post's last update datetime.  We recommend all calls use this parameter, a typical value would be hours=24
>    doi - this can be used to return a feed that relates to a specific preLights post or preList only, it is assumed this will be used if you've received notification of the DOI via some other method, for example from a call to crossref.
