### ISSUE TITLE
Change dates on search results

### ISSUE THREAD

**Issue by thewilkybarkid** [sciety/sciety#626]
- [x] Replace date posted with latest version date
  - [x] template renders the new date, with fallback 
    - [x] unit test
  - [x] introduce `latestVersionDate` in the view model
  - [x] fetch the date from biorxiv API
- [x] Add the latest activity date from the latest evaluation (and hide if there are none)
  - [x] template optionally renders the new date
    - [x] unit test
  - [x] get the date from a/the projection
    - [x] use real data
    - [x] "handle" wrapping li elements
    - [x] unit test

![Screenshot from 2021-03-30 16-05-45](https://user-images.githubusercontent.com/1784740/113840306-75a49980-9788-11eb-9c7c-a5514ac020c9.png)

## Refactoring

- [x] make `getLatestActivityDate` a named function
- [x] improve `toLowercase` type
- [x] improve handling of `li` tags in meta list
  - [x] same line problem
  - [x] `<span>` are sometimes in functions and sometimes not
  - [x] no ternary inside templates
- ~compare reviews from port to projection~
- [x] look for alternative to the `map` in `populateArticleViewModel`

## Tech debt

- ~replace `FindReviewsForArticleDoi` with client-defined type~
- ~group authors missing on article meta pages (https://staging.sciety.org/articles/meta/10.1101/2021.04.06.438687)~ Extracted to #631.
- [ ] Improve author semantics: convert `div` to a `ul`
  - [ ] an error on the codec doesn't cause the whole page to break
  - [ ] extend the codec with `authorList`
    - [ ] include organisational authors

**Comment by giorgiosironi** [comment]
We got to this codec for the author list (as opposed to an author string):
```
const author = t.union([
  t.type({
    fullName: t.string,
  }),
  t.type({
    collectiveName: t.string,
  }),
]);

const resultDetails = t.type({
  doi: DoiFromString,
  title: t.string,
  authorString: t.string,
  authorList: t.type({
    author: t.array(author),
  }),
  firstPublicationDate: DateFromISOString,
  bookOrReportDetails: t.type({
    publisher: europePmcPublisher,
  }),
});
```
However, we are not committing this, as if there are other unknown cases for `author` they would currently break the whole search page for that query.
