### ISSUE TITLE
Change group page feed to be a list of articles

### ISSUE THREAD

**Issue by kevinrutherford** [sciety/sciety#637]
Copy the article card design from the search results page.

## Questions
Relates to https://staging.sciety.org/groups/4eebcec9-a4bb-44e1-bde3-2ae11e65daaa

- [x] In what order should the items appear?
      Most recent activity by that group. Which might not match the `latest activity` if other groups are active. And that is ok for now.
- [x] does someone else reviewing an article change its ordering by last activity date in the list? (e.g. https://staging.sciety.org/articles/activity/10.1101/2019.12.20.884056)
      No. See answer above.
- ~how should the 'side-bar' (followers & feed) be styled re background colour vs cards / white backgrounds?~
       No styling work until we have designs by Nick.
- [x] is "Feed" heading still appropriate? Replace with "Recent activity" see https://github.com/sciety/sciety/issues/637#issuecomment-817840606) Use "Recent activity" for now.
- ~wrapping of meta information?~ wait for designs
- ~minium width?~
- ~layout on narrow screen~
- [x] what to show when there's no articles?
      Use text from previous feed.
- [x] what should happen if we can't fetch bits of information (from Crossref and/or bioRxiv)?
  - if we can't get version info: don't show a _latest version_
  - if we can't get Title and Authors from Crossref:
    - show error message if all articles failed
    - show an error box for each article that failed / show a single error box if any article failed (choose simplest implementation)
    - error box shows up in the point in the list where those articles would have been
- [x] how many articles should be shown?
       up to 10
- [x] when a lookup fails, what should happen?

## Acceptance criteria

- Cards in the group page should behave/look/feel the same as the card in the search results
- The author list should be expressed as **Surname N, Surname O.** across these two, but ignore the disparity with the article meta page

## Implementation
- [x] Render happy path for new feed
  - [x] move `<li>` out of article card
  - [x] deal with empty array of authors
  - [x] change element in `<div class="group-activity-list__item_container">` from `div` to `article`
  - [x] wrap title in `<h3>`
  - [x] decouple from search markup/CSS
  - [x] authors as a list for semantics
  - [x] always have top border on first item
- [x] remove hard-coding
  - [x] sketch interfaces to help plan
  - [x] fetch version info with hard-coded server property
  - [x] fetch server 
  - [x] fetch title
  - [x] fetch author
  - [x] use real latest activity date
  - [x] use real evaluation count
  - [x] list of articles itself
- [x] Change `Feed` title to `Recent Activity` after roll out to all groups
- [x] set `line-height` 20px equivalent on authors list (https://projects.invisionapp.com/d/main/#/console/21112247/445867128/inspect) & let the list items inherit that
- [x] `line-height` of meta information should be 20px equivalent
- [x] check in screen reader - provide supplementary text as necessary
- [x] Check in IE
- [x] TODO test on not existing group implies we should return a `O.none` for that case
- [x] projection currently returns always `O.some` because `RM.lookup` on activities can't fail (can it?)

## Refactoring
- [x] convert `span` to a `div` for `<span class="group-activity-list__item__meta">`
- [x] ~type of author array (sanitised)~
- [x] tests of `fetch-article-details` have multiple currying
- [x] final `map` in `fetch-article-details`
- [x] separate rendering of empty list
- [x] use same renderer for article cards in group page and search results page
  - [x] make `searchEuropePmc` return a list of authors
  - [x] extract renderer and view model to shared components
  - [x] Fix `#group-activity-list-authors` breaking encapsulation
  - [x] Remove `render-search-result.ts`
  - [x] find a better way to distinguish between result types
  - [x] test `render-article-activity.ts`
  - [x] ~add regression test for authors trailing `.`~ model as Sass mixin, test by Backstop
  - [x] tidy class names for group search result card (no longer needs to be generic)
  - [x] investigate / extract new card mixin
  - [x] investigate usage and location of view models
- [x] align search results with group page (eg authors as a list)
- [x] review styles and consolidate usage (was copied over from `.search-results-list`, `.search-results-list__item` et al.)

## Tech debt

- [x] inline `full-tab-card` mixin wherever it is used, as we are unclear on coupling of designs
- [x] check for unescaped strings that should be escaped
- ~the app is left running after Backstop failed~; don't fix to allow investigation
- ~server doesn't always restart when making changes~; cannot reproduce on Linux

## Out of scope/lower user value

- Show articles for which we can retrieve data from Crossref
- Don't display anything (no card in the list) for any articles that fail because of missing data from Crossref
- The number of cards might be lower (e.g. 9 rather than 10) if an article is not displayed for the previous reason

**Comment by BlueReZZ** [comment]
I can quickly answer one of those - `Feed` is no longer appropriate, and to avoid having to impose a taxonomy then `Recent activity` seems most appropriate until we have the ability to add more context.

**Comment by davidcmoulton** [comment]
```
/*
* Option A:
*   1. compute DOIs for the group (in a sorted list)
*   2. compute all group activities
*   3. Join results of 1 and 2 (map and a lookup)
*
* Option B:
*   1. filter for current group activities only
*   2. reduce events to compute activities for all articles ("compute all group activities")
*       branch 1: add activity if the article isn't in the state
*       branch 2: substitute activity with a new one, changing date and count (+1)
*   3. sort by latest activity date by current group
*   4. map to remove date
*
* Consensus: aim for something like option A, refactor to something like option B. Aim: don't iterate over events > once
*
* */
```

**Comment by giorgiosironi** [comment]
IE check looks good:
![Screenshot_2021-04-20 Dashboard](https://user-images.githubusercontent.com/160299/115394124-5bcc7300-a1da-11eb-88b7-db0411f47ed0.png)
