### ISSUE TITLE
The homepage for logged in users displays articles recently evaluated by groups I follow

### ISSUE THREAD

**Issue by hdrury1** [sciety/sciety#643]
Acceptance criteria:

- [x] The feed shows a list of up to 20 articles (ie. rather than events) that have recently been evaluated by groups I follow
  - [x] Ordered by descending date of latest activity (even if that latest activity is not by a group that I follow)
- [x] The list of articles is presented in the same card format as the group page
- [x] The errors of the group page article cards should not be changed in this ticket
- [x] The title of the list is not 'Feed' but 'Recent activity by groups you follow'
- [x] If the list of articles is empty, display the current messages
- [x] Rename things from `ArticleActivityCard` to `ArticleCard`

## Questions

- [x] in the case of an error in fetching details of one article, what should happen? 
  Do not display that article card. Show 19 articles rather than 20.
- [x] in the case of errors on fetching details of multiple articles?
  No difference from a single article case.
- [x] in the case of errors on fetching details of all articles?
  Display `We're having trouble accessing this content right now. Please try again later.`.
- ~what is the acceptable page generation time?~

Architecture and Mikado steps: https://miro.com/app/board/o9J_ksK0wlg=/?moveToWidget=3074457357915554952&cot=14

**Comment by kevinrutherford** [comment]
![Screenshot from 2021-04-22 14-30-34](https://user-images.githubusercontent.com/23290/115722926-5ce6d700-a377-11eb-8156-256bc955923a.png)
