### ISSUE TITLE
find-prereview-reviews failed, their API seems to be down

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#655]
- [x] @hdrury to contact PREreview
- [x] temporarily stop fetching reviews from PREreview
- [x] ...
- [x] fetch reviews from PREreview again

**Comment by hdrury1** [comment]
> it's not down, but it's possible that azure's being kind of sluggish. @Hannah Drury do you know specifically which API queries you're doing so I can do some troubleshooting?

**Comment by giorgiosironi** [comment]
This is the request we are making:
```
$ curl -v -H "Accept: application/json" https://www.prereview.org/api/v2/preprints
```
After about a minute, this eventually returns:
```
< HTTP/1.1 500 Internal Server Error
< Content-Length: 109
< Content-Type: application/json; charset=utf-8
< Vary: Origin
< X-Request-Id: 400d05cb-9161-417c-8799-1b964c97bac0
< Date: Wed, 21 Apr 2021 08:21:13 GMT
< 
{
  "statusCode": 500,
  "error": "Internal Server Error",
  "message": "An internal server error occurred"
}
```
We suspect we have to use pagination?

**Comment by hdrury1** [comment]
Response from PREreview:

> thanks for the additional context @Hannah Drury! Yes, you could definitely use pagination (we use limit and offset query parameters for that, for instance to fetch 10 preprints starting from the 20th preprint you'd add ?limit=10&offset=20 to your query). However there's definitely a new performance issue with the query that didn't exist previously, which I'm trying to track down. So I also wouldn't characterize what you're seeing as expected behavior and we hope to have a fix soon.
