### ISSUE TITLE
Move the groups list to a new page

### ISSUE THREAD

**Issue by kevinrutherford** [sciety/sciety#698]
## Acceptance criteria:

- [x] the list of groups is no longer on the home page (logged in and logged out)
  - [x] leave the current groups space empty
  - [x] don't expand the remaining column
- [x] there is a new link `Groups` in the menu
  - [x] takes the browser to a new page `/groups`
  - [x] has a new SVG icon
- [x] `/groups` has the title `Groups`
- [x] `/groups` shows the list of groups
  - [x] sorted as currently
  - [x] having exactly the same content in each card
  - [x] the cards are laid out in an auto flowing grid
- [x] handle errors as currently
- [x] OG Title is: 'Sciety Groups'
- [x] OG Descriptions is: ???

## Questions

- [x] what should the OpenGraph Title and Description be?

**Comment by hdrury1** [comment]
Description: `Content creators helping you decide which preprints to read and trust.`
