### ISSUE TITLE
Pages taking ages to load

### ISSUE THREAD

**Issue by kevinrutherford** [sciety/sciety#700]
## Mitigation

- [x] remove ScreenIT temporarily
  - [x] remove the ScreenIT data
  - [x] stop ingesting ScreenIT evaluations
  - [x] put the ScreenIT group page behind a feature flag
- [x] Fix performance problems with fp-ts maps
  - [x] group page / recent activity
  - [x] home page / your feed
  - ~document performance curve using tests~

## Add performance regression tests to components using Evaluated events
- [x] group-page recent-activity __FAILS__
- [x] article-page feed __PASSES__
- [x] logged-in-home-page your-feed __FAILS__
- [x] search-results __PASSES__
- [x] user-page saved-articles-list -- looking at the code, this probably passes

## Analysis

For the `group-page / recent-activity` case, the problem lies within the call to `RA.reduce` .

In particular, `RM.` calls to lookup and upsert in the ReadonlyMap show a performance improvement when substituted with a plain object (`Record<string, ...>`).

**Comment by giorgiosironi** [comment]
Noticed: https://github.com/gcanti/fp-ts/issues/1492
