### ISSUE TITLE
Add RR:C19 as a Sciety group

### ISSUE THREAD

**Issue by hdrury1** [sciety/sciety#741]
- [x] ingest all their content
- [x] enable in prod
- [x] clean up ReviewIds

**Comment by erkannt** [comment]
These are the rapid reviews we currently can't display on sciety.org as they are not biorxiv or medrxiv articles.
[5142a5bc-6b18-42b1-9a8d-7342d7d17e94.csv](https://github.com/sciety/sciety/files/6637550/5142a5bc-6b18-42b1-9a8d-7342d7d17e94.csv)

**Comment by BlueReZZ** [comment]
> @BlueReZZ These are the rapid reviews we currently can't display on sciety.org as they are not biorxiv or medrxiv articles.
> [5142a5bc-6b18-42b1-9a8d-7342d7d17e94.csv](https://github.com/sciety/sciety/files/6637550/5142a5bc-6b18-42b1-9a8d-7342d7d17e94.csv)

That's really useful thanks. Adds to the data to generate a pull to support a broader set of preprint servers, even at a lower level of integration (i.e. no version history)

**Comment by will-byrne** [comment]
This is a suspected data issue where the second `is-review-of` should probably be a `is-supplement-to` or an article DOI: 
```json
"URL": "http://dx.doi.org/10.1162/2e3983f5.8257bfb2",
    "relation": {
        "is-review-of": [
            {
                "id-type": "doi",
                "id": "10.1101/2020.05.13.20101253",
                "asserted-by": "subject"
            },
            {
                "id-type": "doi",
                "id": "10.1162/2e3983f5.dfd95570",
                "asserted-by": "subject"
            }
        ]
    }
```
