### ISSUE TITLE
I can view all articles returned from my search query, even if there are more than 20

### ISSUE THREAD

**Issue by hdrury1** [sciety/sciety#751]
Acceptance criteria:

- [x] When the `All Articles` category is selected, and there are more than 20 results:
  - [x] I can navigate to the next page of results
- [x] `Next` is centred below the list of results
- [x] `Next` is styled as a default button
- [x] `Next` is displayed and clickable on every page where the number of results remaining to show is greater than or equal to the page size

**Comment by giorgiosironi** [comment]
For reference: second page of `covid` search:
http://localhost:8080/search?category=articles&query=covid&cursor=AoJwgLSPkfcCKDQzMDA4Nzk4
