### ISSUE TITLE
Ask visitors to staging a question with Intercom

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#763]
<img src="https://intercom.intercom-attachments-7.com/i/o/160504834/dcccf591e5117cd984237b2b/bnfbP3k8XHCvrSEc4TrC4CufTDSEAvk8EhwERNunMZbVXkN2tIrzXjJg3vZoASjl1Iun9SecRkVr3-tgvT-4021lbVwMD8BHaL54Dua6Vdyy0No7nuxVvMLS43phRMRRXGbIPt3V" />

- [x] set up first question or interaction for `visitors` (no `leads` or `users` filters). At the moment there is a default configuration but this will be changed by the outreach team.
- [x] Fountain to integrate widget via ~[`<script>` tag](https://app.intercom.com/a/apps/j1i1ayq1/home?step=set_up_messenger_visitors), `Basic JavaScript` option~ GTM option https://www.intercom.com/help/en/articles/2631808-install-intercom-with-google-tag-manager
  - [x] appears only on staging.sciety.org
  - [x] dev team: only loaded if the visitor consents to cookies; at the moment after Cookiebot approval, Intercom only loads on a following page load rather than in the current page
- [x] outreach team: [graphical customization](https://app.intercom.com/a/apps/j1i1ayq1/home?step=set_up_messenger_visitors)
  - [x] chatbot identity
  - [x] title and text of chat (not `eLife Sciences Publications ltd`)
  - [x] logo
  - [x] background color
  - [x] action color
  - [x] background texture, if any
  - [x] out of scope: [customizing the launcher button](https://www.intercom.com/help/en/articles/2894-customize-the-intercom-messenger-technical)
- [x] dev team: performance concerns
  - ~[loading can be delayed](https://www.intercom.com/help/en/articles/5053693-can-i-delay-loading-intercom-on-my-site-to-reduce-the-js-load) after an arbitrary time via `setTimeout`~
  - ~real time presence [relies on heartbeats](https://www.intercom.com/help/en/articles/254-real-time-user-presence-the-technical-explanation), hence it can affect bandwidth usage. The size of the effect is unknown~
- [x] Paul: privacy concerns
  - [x] sanity check [first party cookies list](https://www.intercom.com/help/en/articles/2361922-intercom-messenger-cookies)
  - [x] Intercom suggests to [update the privacy policy](https://www.intercom.com/help/en/articles/194-updating-your-privacy-policy)
  - [x] the documentation assures us of [GDPR compliance](https://www.intercom.com/help/en/articles/1385437-how-intercom-complies-with-gdpr) for data portability and retention
- [x] Hannah and dev team: accessibility, documentation (by memory says it's accessible to screen readers, to be verified) 
- [x] Enable in prod
- ~Slack integration~

## JavaScript code

```
<script>
  window.intercomSettings = {
    app_id: "j1i1ayq1"
  };
</script>

<script>
// We pre-filled your app ID in the widget URL: 'https://widget.intercom.io/widget/j1i1ayq1'
(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',w.intercomSettings);}else{var d=document;var i=function(){i.c(arguments);};i.q=[];i.c=function(args){i.q.push(args);};w.Intercom=i;var l=function(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://widget.intercom.io/widget/j1i1ayq1';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);};if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})();
</script>
```

**Comment by hdrury1** [comment]
Reaching out to Intercom directly to clarify what personal data is collected and used.
