### ISSUE TITLE
preLights now only loads with JS enabled, retrieving excerpts therefore is broken

### ISSUE THREAD

**Issue by erkannt** [sciety/sciety#827]
Our fetcher relies on getting HTML from a preLight page. They seem to have done something so that you can no longer load their pages without JS.

- [x] ask them what is going on, this probably also breaks other stuff

- [x] follow up about DOI warnings

**Comment by hdrury1** [comment]
Heard back from preLights

> I've raised an issue with the firewall team in relation to this, this has been enabled as part of some investigations that are being completed for a login issue we've been experiencing. It has now been disabled and JavaScript is not being required - please let us know if this resolves the issue you were experiencing.

**Comment by giorgiosironi** [comment]
Today we ran the script and added:
```
2021-06-18T08:04:34.000Z,10.1101/2021.04.30.442087,prelights:https://prelights.biologists.com/?post_type=highlight&p=29610
```
but there are 3 warnings about DOIs we can't parse that may require a change on the other side:
```
WARNING: Cannot parse url to DOI: https://www.biorxiv.org/content/10.1101/2020.01.24.917146v1.full
WARNING: Cannot parse url to DOI: https://www.biorxiv.org/content/10.1101/779769v1.full
WARNING: Cannot parse url to DOI: https://www.biorxiv.org/content/10.1101/364786v4.full
```
@hdrury1 can you follow up with the other side to understand what should the URL format be?

**Comment by hdrury1** [comment]
> Hi Hannah,

I hope you are well. Apologies, we don't quite understand the nature of the issue - the URLs you've quoted look to be BioRxiv URLs as opposed to DOIs or URLs to our feed. Are you able to send us the three queries you are performing (the URLs on our feed you are calling) which are resulting in the 'cannot parse error'?  It might be easier to have a quick call next week to discuss?

All the best,

Julian

**Comment by giorgiosironi** [comment]
Note: bioRxiv pages have a `<meta name="DC.Identifier" content="10.1101/2020.01.24.917146" />` tag that can be used to go from a URL we load to the DOI for that preprint.
