### ISSUE TITLE
Consistent `Failed to retrieve article versions` errors from biorxiv/medrxiv API

### ISSUE THREAD

**Issue by giorgiosironi** [sciety/sciety#842]
- [x] collect some recent examples

**Comment by erkannt** [comment]
Recent examples:
- https://staging.sciety.org/articles/activity/10.1101/2021.06.10.21258608
- https://staging.sciety.org/articles/activity/10.1101/2021.02.10.21251247

API url used:
- https://api.biorxiv.org/details/medrxiv/10.1101/2021.06.10.21258608
- https://api.biorxiv.org/details/medrxiv/10.1101/2021.02.10.21251247

All DOI with version errors in the past 30 days:

<google-sheets-html-origin><style type="text/css"></style>

10.1101/839589
--
10.1101/2021.04.20.440659
10.1101/2021.03.13.435275
10.1101/2021.05.01.442271
10.1101/2020.09.16.300343
10.1101/861849
10.1101/2021.06.10.21258608
10.1101/2021.06.13.21258845
10.1101/2021.06.12.21258810
10.1101/2021.02.10.21251247
10.1101/2021.06.02.446343
10.1101/2020.07.26.221168
10.1101/2020.05.13.094805
10.1101/2020.10.24.353680
10.1101/2020.06.11.145615
10.1101/2020.10.13.336479
10.1101/2020.11.16.384826
10.1101/2020.01.15.907584
10.1101/2020.08.19.256859
10.1101/2020.09.04.282731
10.1101/2020.11.30.405225
10.1101/2020.10.07.328666
10.1101/2021.05.07.443126
10.1101/2020.05.26.116533
10.1101/2021.03.11.434989
10.1101/2021.03.05.434169
10.1101/2021.04.27.441651
10.1101/2021.01.22.427834
10.1101/2021.02.02.429395
10.1101/2020.12.08.393595
10.1101/2021.06.12.448196
10.1101/2021.01.12.426394
10.1101/2021.03.02.433577
10.1101/2020.06.08.140392
10.1101/2021.04.29.442028
