### ISSUE TITLE
Twitter cards for user pages are personalised according to the user

### ISSUE THREAD

**Issue by hdrury1** [sciety/sciety#850]
Acceptance criteria:

- [x] `og:title` matches `<title>`, e.g. `Hannah Drury | Sciety`
  - [x] assess whether `| Sciety` is needed for the `og:title`
- [x] `og:description` shows the number of articles they have saved and the number of groups they follow e.g. `7 Saved articles | 3 Followed groups`

**Comment by thewilkybarkid** [comment]
https://github.blog/2021-06-22-framework-building-open-graph-images/ might be interesting for inspiration.
