### ISSUE TITLE
Link the search form to example searches

### ISSUE THREAD

**Issue by kevinrutherford** [sciety/sciety#916]
Acceptance criteria:

- [x] Clicking on an example search term should redirect to the search results page with that term populating the search box

# Checklist

- [x] Release
- [x] Ask Google to spider us

**Comment by giorgiosironi** [comment]
> URL was added to a priority crawl queue. Submitting a page multiple times will not change its queue position or priority. Learn more.

(refers to `https://sciety.org`)

**Comment by giorgiosironi** [comment]
Progress can be monitored at https://search.google.com/search-console/inspect?resource_id=sc-domain%3Asciety.org&id=ENH7H44ENxcVqgIJPu6JLA
