### ISSUE TITLE
SPIKE: Support arxiv  & OSF preprint servers

### ISSUE THREAD

**Issue by kevinrutherford** [sciety/sciety#960]
## arxiv
- [x] Implications for article version information?
- [x] Implications for ingestion?
- [x] Other considerations?
  - [ ] Maybe try adding one event for an Arxiv article?
- [ ] Timebox 90 minutes
- [x] Is Arxiv supported on EuropePMC search?

Map of desired tasks, how we do them now, and how we might approach doing them with arxiv: https://miro.com/app/board/o9J_ksK0wlg=/?moveToWidget=3074457362039197658&cot=14

**Comment by BlueReZZ** [comment]
A note on my recent experience using EuropePMC to help Colab. We found that using `JOURNAL` in the search did not work well for finding all bioRxiv preprints but that is what is offered if you use the advanced search menu - in search on Sciety we use `PUBLISHER:bioRxiv`.

However, a quick check on `PUBLISHER:arxiv` doesn't return anything yet `JOURNAL:arxiv` does but only has ~4000 results: https://europepmc.org/search?query=%28JOURNAL%3A%22ArXiv%22%29

**Comment by kevinrutherford** [comment]
Arxiv uses `id`s instead of DOIs to identify articles. So one proposal would be to introduce an `ArticleId` type to map to DOIs or arxiv ids.

**Comment by kevinrutherford** [comment]
The only information in the API that gives information about versions seems to be https://arxiv.org/help/api/user-manual#title_id_published_updated, in which the later version is indicated by an `updated` tag. We don't know whether multiple versions results in multiple `updated` tags.

**Comment by will-byrne** [comment]
Sample from prelights that is on arxiv:
```xml
<item>
<category>
<![CDATA[ <a name = "highlight">highlight</a> ]]>
</category>
<title>Fully Unsupervised Probabilistic Noise2Void</title>
<link>https://prelights.biologists.com/highlights/fully-unsupervised-probabilistic-noise2void/</link>
<guid isPermaLink="false">https://prelights.biologists.com/?post_type=highlight&p=16203</guid>
<author>Mariana De Niz</author>
<image>
<url>https://prelights.biologists.com/wp-content/uploads/2020/01/Noise2Void.png</url>
</image>
<pubDate>Sat, 11 Jan 2020 15:27:36 +0000</pubDate>
<!--  Echo content and related posts  -->
<oneLineSummary>Advancing image denoising: Improvements to Probabilistic Noise2Void (PN2V), a method to train convolutional neural networks for image denoising.</oneLineSummary>
<content:encoded>
<![CDATA[ <h1 style="text-align: justify;">Background</h1> <p style="text-align: justify;">Image denoising is the first step in many biomedical image analysis pipelines, and it boils down to separating an image into its two components: the signal <em>s</em>, and the signal-degrading noise <em>n</em>. For this purpose, discriminative deep learning based methods are currently best performing. Previously,&hellip; ]]>
</content:encoded>
<doi>https://doi.org/10.1242/prelights.16203</doi>
<!--  Links to Biorxiv -->
<preprints>
<preprint>
<preprinturl>https://arxiv.org/abs/1911.12291v1</preprinturl>
<preprintdoi>abs/1911.12291</preprintdoi>
<preprintauthorresponse>Yes</preprintauthorresponse>
<preprintauthorresponseurl>https://prelights.biologists.com/highlights/fully-unsupervised-probabilistic-noise2void/#author-response-1</preprintauthorresponseurl>
<preprintauthorresponseexcerpt>
<![CDATA[ 1. In your preprint you touch on the question why self-supervised methods are not competitive with models trained on image pairs. Can you expand further on your explanation? This is an interesting question and it is important to answer with respect to the problem one intends to address. N2V, PN2V,&hellip; ]]>
</preprintauthorresponseexcerpt>
</preprint>
</preprints>
</item>
```

**Comment by will-byrne** [comment]
Meta data retrieval may not be possible from crossref so will need to be retrieved from arxiv?

**Comment by davidcmoulton** [comment]
Map of desired tasks, how we do them now, and how we might approach doing them with arxiv: https://miro.com/app/board/o9J_ksK0wlg=/?moveToWidget=3074457362039197658&cot=14
