### ISSUE TITLE
No longer existing DOI referenced by NCRC evaluation

### ISSUE THREAD

**Issue by erkannt** [sciety/sciety#972]
- article in question 10.1101/32793914
- currently on page four of evaluation: https://staging.sciety.org/groups/62f9b0d0-8d43-4766-a52a-ce02af61bc6a/evaluated-articles?page=4
- entire page fails resulting in `Oops` page (503 code)
- no acceptance test for this scenario exists

**Comment by davidcmoulton** [comment]
This occurs when the `journal` column contains 'medrxiv', and the `link` column links to 'ncbi' rather than 'medrxiv.org'. May be guarded against by checking the link is to medrxiv when the journal is medrxiv. We expect this to occur rarely.
